### ISSUE TITLE
Some components aren't in this repository

### ISSUE THREAD

**Issue by User8395** [pop-os/cosmic-epoch#101]
COSMIC components like COSMIC Time and COSMIC Text do not exist as submodules here.

Is this normal?

If so, when will they be added?

**Comment by Drakulix** [comment]
They are libraries used to implement the desktop components. cosmic-time is an animation library and cosmic-text is a text rendering library.
Both are sub-dependencies of some of the components in this repository, but they don't need to be installed directly.
As such they don't need to be (and will not be) included in this repository.
