### ISSUE TITLE
[BUG] COSMIC Terminal closed/crashed when returning from suspend

### ISSUE THREAD

**Issue by 71nuxadd1ct** [pop-os/cosmic-epoch#1027]
If the COSMIC terminal was left open before a suspend action, it is no longer open when returning from suspend.

**Comment by iamkartiknayak** [comment]
It worked fine on my system. Are you on `popdev:master`?

**Comment by 71nuxadd1ct** [comment]
I installed thru apt.  But, you're right: hasn't happened in a while.

**Comment by iamkartiknayak** [comment]
It might be a one-time thing or may only happen under certain conditions. If only we could reproduce this to find the cause. For now it might be safe to close if it’s no longer an issue.

**Comment by 71nuxadd1ct** [comment]
It definitely happened every time my laptop would suspend.
Closing.
