### ISSUE TITLE
[Feature Request] Add a fullscreen toggle hotkey

### ISSUE THREAD

**Issue by kode54** [pop-os/cosmic-epoch#1030]
As the title says, add a hotkey to toggle fullscreen mode for the current window, possibly not mapped by default. It's at least what I map to Super+F on wlroots compositors.

**Comment by git-f0x** [comment]
You can already toggle fullscreen (on apps that support it) with F11.

**Comment by kode54** [comment]
Somebody replied to this that I could use applications' built-in fullscreen toggle hotkeys to do this. The point is that I want a compositor level hotkey. It appears they deleted their comment immediately after it sent the email notification.

**Comment by edrex** [comment]
Duplicate of https://github.com/pop-os/cosmic-comp/issues/646, let's close this and continue there.
