### ISSUE TITLE
Suggestion: Combine desktop dock and panel

### ISSUE THREAD

**Issue by mejobloggs** [pop-os/cosmic-epoch#1036]
Feel free to disregard this suggestion, as it personal opinion and it may not be an appropriate place for suggestions, or fit in with the cosmic ideals.

To my mind it's much more useful to have dock and panel together in a single thingy that I can autohide, and access in 1 action. Rather than having to access 2 places. I don't see the value in separating them.

See my screenshot for a quick edit of an idea for combining the two panels.

![combineddockpanel](https://github.com/user-attachments/assets/902033c5-66eb-4a4d-aae5-b8cee333753e)

All my general computer operating mouse pointer actions are now in 1 location instead of split

**Comment by git-f0x** [comment]
You can already do this. Just disable the dock, and add more applets to the panel.

**Comment by mejobloggs** [comment]
Nice I didn't realise you could add an App Tray to the panel. Thanks very much.

Pity the Workspaces and Applications applets show as words instead of icons on the smaller sizes.

1 step up from small is the perfect size for me, but then Workspaces/Applications are not in icon format, just words

**Comment by git-f0x** [comment]
It will be configurable, once per-applet settings are implemented.
Until then, you can create a configuration file to force them to display as icons.
Create a file called `configs` in `~/.config/cosmic/com.system76.CosmicPanelButton/v1/`, with the following contents:
```
{
    "Panel": (force_presentation: Some(Icon))
}
```
