### ISSUE TITLE
Keyboard shortcuts for both workspaces and launcher at the same time

### ISSUE THREAD

**Issue by tobico** [pop-os/cosmic-epoch#1050]
I've been testing the COSMIC alpha and so far the biggest obstacle I've run into is that it doesn't seem to be possible to perform common window management tasks without moving my cursor all the way to the corner of the screen to click on the workspaces and/or applications buttons.

Switching between windows using Alt+Tab is currently broken to the point of not being usable, so the only viable method of switching windows is the workspaces view. The only way I can find to open the workspaces view quickly with the keyboard is to change the window management option to make the "Super" key open workspaces instead of the launcher, but if I switch to that option then I no longer have any convenient way to open the launcher and start new applications using the keyboard.

I think it would be good for COSMIC to have a simple default way that these two common operations can both be quickly accessed using the keyboard.

Some suggestions:

1. Have some kind of dashboard view that combines the workspaces view and the launcher into one. This is what GNOME does and it's IMO a brilliant design decision and is the main reason I'm still using GNOME despite its many shortcomings.
2. Have an alternate keyboard combination to open whatever isn't selected as the default, e.g. Super opens workspaces, Super+Space opens launcher.
3. Automatically switch from the workspaces view to launcher when text is typed while it's open. This would provide the convenience of the first approach without needing any visual change to the design, although it would be less discoverable. This could potentially be added in addition to other approaches.
4. Copy Windows behavior - Super opens the launcher, and Super+Tab opens workspaces.
5. Copy Mac OS behavior - F3 opens workspaces, and F4 opens launcher.

My preference is obviously for the first approach, but literally any of these would make a huge difference to my ability to use COSMIC as a desktop.

**Comment by chdalski** [comment]
"... so the only viable method of switching windows is the workspaces view."

That's wrong - every time you open the launcher (super key) you'll be presented with the list of currently available windows. 
So if you want to switch between those you can just select the one you want from the launcher or use the given shortcut (Ctrl + <window number>).

**Comment by git-f0x** [comment]
Also, the default shortcuts for those components are:
Launcher: <kbd>Super</kbd> + <kbd>/</kbd>
Workspaces: <kbd>Super</kbd> + <kbd>W</kbd>
App Library: <kbd>Super</kbd> + <kbd>A</kbd>
You can configure them on the Keyboard shortcuts page.

**Comment by tobico** [comment]
> "... so the only viable method of switching windows is the workspaces view."
> 
> That's wrong - every time you open the launcher (super key) you'll be presented with the list of currently available windows. So if you want to switch between those you can just select the one you want from the launcher or use the given shortcut (Ctrl + window number).

Oh, I didn't see those at all! I think because they're presented as launcher items I must have assumed these options were to launch new windows, not switch to existing ones.

I'd love if these items could include a screenshot of how each window looks, as that just makes a lot more sense to my brain, but its certainly an adequate way of switching windows for now.

**Comment by tobico** [comment]
> You can configure them on the Keyboard shortcuts page.

Awesome, thanks! I think I'll be using Super+W a ton. I hadn't seen the keyboard shortcuts settings page at all, and it wasn't super easy to find even now that I know about it. To my mind, configuring a keyboard shortcut for window management would be changing something about window management, not changing something about my keyboard. Perhaps we could have a link in the settings from the window management page to the keyboard shortcuts page?

**Comment by tobico** [comment]
> I'd love if these items could include a screenshot of how each window looks, as that just makes a lot more sense to my brain, but its certainly an adequate way of switching windows for now.

I've just discovered another problem, the launcher only shows 8 windows even if you have more than that open, so it's not adequate as a primary method for switching windows. Now that I know about the keyboard shortcuts though, I can safely change my default super action to workspaces!
