### ISSUE TITLE
Cosmic toolbar/GUI controls not working??

### ISSUE THREAD

**Issue by esteelpaz** [pop-os/cosmic-epoch#106]
Folks:

I added Cosmic DE to my jammy Pop_OS system a couple months ago on my '20 Sys76 Gazelle . . . logged into it, thought it was like Openbox where right clicking provides the menus, but . . . nope.  Eventually figured out to use the super key to get stuff going . . . and then didn't check back on it, until today.

Logged into the exciting desktop background image . . . clicking around on stuff, like the master menu items did not do anything??  I can see the choice for "Integrated" graphics is showing, volume control, and power applets are showing, but clicking on them does nothing . . . right clicking on them, also does nothing.

When I used super b to open the browser the number 2 showed up upper left, but clicking on what I assumed would be "desktops" . . . nothing happens.  When I clicked on the date and time applet, or right-clicked I saw the command, "sudo apt install happiness" ??? which is amusing . . . .  I didn't run the command.  : - (

I used super t to get to a terminal window . . . forgot about "exit" which I was trying to just log out to log in manager to get back to Pop; had to sudo reboot to get there.  I don't recall having to do that previously to get out of Cosmic.

I messed with Pop on Wayland, but there also seems to be issues there, sticking to Pop for the most part--didn't check it today.  I was hoping that Pop would at least upgrade to kinetic . . . but one of the techs that responds to issues said, "It's all going into Cosmic these days . . . ."  I have a mantic edition of Lubuntu on another machine . . . jammy is getting "old," but Cosmic still seems to be "pre-Alpha"????  

Is it the system being buggy or is it "pilot error" that is at work on the toolbar applet dysfunction that I am experiencing???

**Comment by jokeyrhyme** [comment]
https://github.com/pop-os/cosmic-epoch/blob/master/README.md :

> Currently an incomplete pre-alpha.

You can use Super+Slash to get a launcher where you can search for things like "log out" and "reboot"

But yes, it's incomplete, and we're not supposed to expect everything on the screen to be functional just yet :people_hugging:

**Comment by esteelpaz** [comment]
No worries.  I guess I just took my time to report what you already knew . . . but, thanks kindly for the super / tip.  I do have other stuff to do . . . .  Sys76 has been posting about cosmic for many months if not a year on IG, seems that was a bit early???

**Comment by leviport** [comment]
>Sys76 has been posting about cosmic for many months if not a year on IG, seems that was a bit early???

Not sure what you mean. Our posts talk about the development process, and there have not yet been announcements about it being ready for alpha testing. Since the project is open source, users are free to install it early, but we can make no guarantees about the stability of Cosmic DE while it is still under such heavy development.

**Comment by leviport** [comment]
I'm sorry we gave you an incorrect impression, that was certainly not the intention. The bug you mentioned is known, so there is no need to report it again. There is no timeline at this time for an alpha. It will be announced once we are closer to an MVP.

**Comment by esteelpaz** [comment]
@leviport 

Not really a problem, I'm just a multi-boot type of guy, running a few rolling edition and stepping into Lubuntu editions as soon as the repos have something to install . . . .  Pop is running fine . . . jammy is just getting to be . . . "old."  But Cosmic seems to be NRfPT . . . .

On the bug report . . . my question was for adding my name to the "this bug affects me" list . . . as nvidia does make a nice product, but they don't seem to stay up with developments in linux . . . not on filing another bug report.  But, no worries on that either.

Guess I'll check back to Cosmic in a few months or later in the year . . . .
