### ISSUE TITLE
Dock extends to screen edges when apps are maximized, regardless of dock settings

### ISSUE THREAD

**Issue by martinhiriart** [pop-os/cosmic-epoch#1061]
I'm testing out the Pop!_OS COSMIC alpha 2 build on my 2017 Razer Blade Stealth, and have noticed that whenever I maximize an app, the dock gets extended to the edges of the screen, even if I disabled that setting in the Dock section of the Settings app.

Is this part of the design of the COSMIC DE, or is this a bug?

Here's a screenshot of my settings app:
![image](https://github.com/user-attachments/assets/243cdd0a-81ca-4415-bfbb-4fe9ba9ce098)

Here's a screenshot of the dock with Chrome maximized:
![image](https://github.com/user-attachments/assets/8bf052c1-468a-4884-8db2-e6e81d352a60)

Here's a screenshot of the dock when an app isn't maximized:
![image](https://github.com/user-attachments/assets/a97d3ebc-861f-423d-9fea-21d99e1ce3be)

So far, I've really been enjoying all of the hard work y'all have been putting into this!

**Comment by rtheodoro** [comment]
> That is intended behavior.

Can you explain why?

**Comment by git-f0x** [comment]
You can see here: https://github.com/pop-os/cosmic-panel/pull/601

But good news is that an option to not have that happen will come.

**Comment by rtheodoro** [comment]
> You can see here: [pop-os/cosmic-panel#601](https://github.com/pop-os/cosmic-panel/pull/601)
> 
> But good news is that an option to not have that happen will come.

Thanks a lot!
