### ISSUE TITLE
Firefox fullscreen of video freezes DE

### ISSUE THREAD

**Issue by SiebenCorgie** [pop-os/cosmic-epoch#1079]
Hi,

Since last Friday, Firefox freezes the whole DE when changing a video into full-screen on Cosmic.

I'm on Archlinux using the official cosmic package group (1.0.0.alpha.2-1 atm.). 
Using Mesa 1:24.2.4-1 on AMD-RX6800-XT / Ryzen 9 5900X.

According to [this crash dump](https://crash-stats.mozilla.org/report/index/b937f90d-862d-439c-a9a8-bb01f0241006#tab-details) the problem is: `Error reading events from display: Broken pipe` for Firefox. 

I verified that this does not happen on Gnome X11/Wayland, which is why I'm posting the error here. 

It also does not happen when starting Firefox in safe-mode, which lets me believe this has something to do with GPU acceleration / ffmpeg.

This might be a problem with Firefox in the end, but It would be nice if Cosmic would be resilient against crashing full-screen windows.

If I can supply more / better information,  please let me know.

Cheers!

**Comment by onlyreportingissues** [comment]
> Hi,
> 
> Since last Friday, Firefox freezes the whole DE when changing a video into full-screen on Cosmic.
> 
> I'm on Archlinux using the official cosmic package group (1.0.0.alpha.2-1 atm.). Using Mesa 1:24.2.4-1 on AMD-RX6800-XT / Ryzen 9 5900X.
> 
> According to [this crash dump](https://crash-stats.mozilla.org/report/index/b937f90d-862d-439c-a9a8-bb01f0241006#tab-details) the problem is: `Error reading events from display: Broken pipe` for Firefox.
> 
> I verified that this does not happen on Gnome X11/Wayland, which is why I'm posting the error here.
> 
> It also does not happen when starting Firefox in safe-mode, which lets me believe this has something to do with GPU acceleration / ffmpeg.
> 
> This might be a problem with Firefox in the end, but It would be nice if Cosmic would be resilient against crashing full-screen windows.
> 
> If I can supply more / better information, please let me know.
> 
> Cheers!

Try kernel 6.10 or apply this patch: https://github.com/pop-os/cosmic-comp/issues/887#issuecomment-2380399199

There is an issue with fullscreen caused by a problem with direct scanout.

**Comment by SiebenCorgie** [comment]
This was indeed the problem, downgrading to Linux 6.10 fixed it for me. Thanks for the fast reply!
