### ISSUE TITLE
Black Icons and other after build for Debian unstable

### ISSUE THREAD

**Issue by misterhsp** [pop-os/cosmic-epoch#1083]
I have built packages for Debian unstable. But everywhere where there should be small icons there are only small black squares in the file manager. And the cosmic-edit is completely black in the text window. Even the close icon at the top right is just a small black square. Am I missing something or is it still like this? Everything is fine with Archlinux.

**Comment by git-f0x** [comment]
I've previously seen such issues reported in Arch, caused by missing/incorrect Vulkan drivers.

**Comment by misterhsp** [comment]
That's it, thank you.

...


Am 07.10.24 um 20:59 schrieb Vukašin Vojinović:
