### ISSUE TITLE
Installing via flatpak causes gear icons in the menu

### ISSUE THREAD

**Issue by JoostvandenOever** [pop-os/cosmic-epoch#1085]
When installing via flatpak, the icons show up as gears in the menu and launcher

![screenshot-2024-10-07-17-57-03](https://github.com/user-attachments/assets/29c681c4-5f30-4304-bce8-e0690a13eeb4)

**Comment by git-f0x** [comment]
It's a common issue when first installing flatpak apps across desktop environments. They should display correctly after a reboot (and maybe logging out and back in).

**Comment by JoostvandenOever** [comment]
You were correct. My bad!
