### ISSUE TITLE
"Workspaces Span Displays" keyboard navigation issue

### ISSUE THREAD

**Issue by Ravengood** [pop-os/cosmic-epoch#1092]
On Pop!_OS 22.04 with COSMIC DE installed, extra monitor attached to Dell laptop, "Workspaces span Displays" activated with Workspace Orientation Horizontal.

![image](https://github.com/user-attachments/assets/5e72ebd3-1f1b-4ed5-bda5-9bc8e3783cd1)

keyboard navigation is broken when i move a window to another workspace or display ... window focus is left behind on the workspace I left (probably focusing last active window) instead of following the window i'm moving to the new workspace/display (very often i need to move it further or interact with the window, but to do that i need to regain focus) ... this seems like a bug since working with "Seperate Workspaces" works the way I would expect?

Please let me know if you need further information

**Comment by Ravengood** [comment]
this.is probably a duplicate of https://github.com/pop-os/cosmic-workspaces-epoch/issues/95

**Comment by leviport** [comment]
Ah yep, I think you're right. If you want to add that info about horizontal workspaces being affected, that should help make that bug report more complete. I'll close this for now, and we can reopen it later if needed.
