### ISSUE TITLE
[Feature Request] Super+L Logout Shortcut

### ISSUE THREAD

**Issue by vemerce** [pop-os/cosmic-epoch#1127]
Coming from Windows to Fedora, I got used to using Super+L as a hotcut to logout of the operating system. (Return to login screen.)

I'm sure it's a hotkey that a lot of Windows folks are familiar with when they first transition over to Linux. And since System76 builds Linux computers with the Pop!_OS preinstalled, (probably being a lot of people's first experience with Linux) I think this would be a useful shortcut to add.

Thank you.

**Comment by Serkan80** [comment]
Super+L locks your screen on Windows :)

and in Gnome this is configurable under Settings > Keyboard. 

Something similar should also be available in Cosmic.

**Comment by leviport** [comment]
Super + Esc is the default screen lock hotkey in Pop. Super + L is used for window navigation, and we don't wish to make this change to the default shortcut mappings. Users are free to customize their own shortcuts according to their own tastes and needs, but keeping Vim direction hotkeys for window navigation by default is far more desirable to us at this time.
