### ISSUE TITLE
(Question) Do you plan to implement the picom's compositor transparency?

### ISSUE THREAD

**Issue by hardBSDk** [pop-os/cosmic-epoch#1177]
The [picom](https://github.com/yshui/picom) compositor is the most used program for window transparency with blur on Linux customizations.

**Comment by Drakulix** [comment]
`picom` is X11-only, while COSMIC is a wayland-only desktop, so it can't work on COSMIC. However we will implement some transparency and blur options, though certainly not everything that `picom` can do.
