### ISSUE TITLE
[BUG] Opening the application menu doesn't transfer focus

### ISSUE THREAD

**Issue by GetPsyched** [pop-os/cosmic-epoch#1186]
I updated COSMIC to all the latest versions today and a regression was introduced.

I have my application menu bound to Super+D, when I open it, the focus goes to the search bar which means I can start typing immediately; but now that isn't the case, I have to either click on it with my mouse, or press Tab to shift focus. Since I open the application menu several times a day, this is really annoying.

**Comment by Thatoo** [comment]
I face the same issue

**Comment by bflanagin** [comment]
Pop!_OS 24.04 
cosmic-app-library 0.1.0\~1729804328\~24.04\~3dd148d
cosmic-comp 0.1~1729848475~24.04~eb64fda

**Comment by GetPsyched** [comment]
This was fixed in some commit; I updated today and the issue was resolved. If anyone else has this still, feel free to re-open.

**Comment by GetPsyched** [comment]
This was fixed in https://github.com/pop-os/cosmic-applibrary/pull/186
