### ISSUE TITLE
[BUG] Lockscreen backdoor

### ISSUE THREAD

**Issue by LavaHeron** [pop-os/cosmic-epoch#1214]
**Cosmic-files version:**
0.1.0~1730233777~22.04~20f9292 (Pop!_OS 24.04 LTS - COSMIC Alpha 3)

**Issue/Bug description:**
If you turn on the lock screen `Super + Esc` and then use the standby button. You have to wait until the system is in standby, then wake it up, and you are in an unlocked system. If I do this several times in a row, it leads to 100% usage of my RAM and the system crashes.

**Steps to reproduce:**
Press `Super + Esc` (lock screen) > Press the standby button > Wait until the system is asleep > Wake it up > System is unlocked

**Expected behavior:**
The lock screen remains locked after standby.

**Other notes:**

**Comment by jokeyrhyme** [comment]
When you say "standby button", do you mean your system hibernates or suspends?

Or are you talking about the button on your monitor?

**Comment by LavaHeron** [comment]
As soon as you are on the lock screen, the user and password field is displayed on the right and a clock is displayed on the left. Below that are 4 buttons. **I mean the 4th button with the little crescent moon on it.**

I'm not sure if the button triggers a sleep or a hibernation state.

I don't mean the physical button on the PC or the button on the monitor, but of course the monitor switches off/goes into standby too because there is no longer a signal coming from the PC. That's why I added the reference to `cosmic-greeter#151`.

**Comment by jokeyrhyme** [comment]
Okay, it looks like in alpha 3 (on my system at least) that button is hardcoded to suspend, and doesn't auto-select hibernation as a fallback if suspend is disabled

So, I had to unlock, and then run `systemctl hibernate` in a terminal

I did see the `cosmic-greeter` lock screen take over immediately, then the screen turned  off for a bit, then turned back on but nothing was responsive, then the entire system turned off

Then, when I booted, it correctly resumed from hibernation and `cosmic-greeter` was the first thing I saw after that, and I had to put in my passphrase to unlock

I wonder if some combination of `cosmic-greeter` and suspend/resume on your system is enough to change the way it behaves in this regard? I wouldn't have thought suspend to be significantly different from a userland software perspective, but I guess it is?

**Comment by LavaHeron** [comment]
It seems that the problem depends on the monitor, or how the screen deals with the lack of a signal. I have tried different screens, the bug can only be reproduced with one. But actually it is about whether the connection is completely cut.

So I experimented a bit and found a variant that is 100% consistent for me and works with all my screens. (Cabled via HDMI to HDMI.)

It is the same bug as with `cosmic-greeter#151` and yes, I end up on a fresh desktop.

**Cosmic-comp version:**
0.1~1730396996~24.04~90883c6 (Pop!_OS 24.04 LTS - COSMIC Alpha 3)

New steps in **bold**:
Press `Super + Esc` (lock screen) > Press the standby button > Wait until the system is asleep > **Remove the HDMI cable from one of the two ports (PC or screen)** > Wake it up > **Plug the HDMI cable back in** > System is unlocked

Can someone try this and tell me if it is reproducible?

**Comment by GabrielDTB** [comment]
I had this same problem with my desktop using an external monitor, but not with my laptop, until I updated on Nov. 13th. On NixOS, using [this flake](https://github.com/lilyinstarlight/nixos-cosmic).

I used to just have to turn off my monitor and turn it back on, and boom the lock screen was gone. Now that doesn't happen. Unplugging the HDMI cable doesn't trigger this behavior either.

**Comment by LavaHeron** [comment]
Yes, I can no longer reproduce the bug either. The patch from mid-November seems to have fixed the problem. So I'm closing this issue.
