### ISSUE TITLE
input sources applet not showing

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#1216]
![image](https://github.com/user-attachments/assets/3cf13a50-5d4e-48d4-823e-3f6ce93ffe04)

As the input sources doesn't display, I can't easily change between keyboard layouts.

**Comment by joshuamegnauth54** [comment]
Hi again! Can you move this issue to [COSMIC Applets](https://github.com/pop-os/cosmic-applets) for more visibility? I'll take a look into it too but I can't replicate it so maybe someone else will be able to fix it.

**Comment by Thatoo** [comment]
I opened this issue then https://github.com/pop-os/cosmic-applets/issues/725
