### ISSUE TITLE
External screen goes black when closing windows in tiling mode

### ISSUE THREAD

**Issue by BVildljung** [pop-os/cosmic-epoch#1220]
**The setup**

I have an external monitor connected to my laptop. The screen is connected via a USB-C -> Display port cable. I use tiling as my window management style. 

**The problem**

When I open a larger number of windows (8-10, usually testing with cosmic terminal) and then closes them again, from the middle, in rapid succession the screen goes black. Some times for just a second or two, but some times it is much longer. When it takes a long time I can work around it by using SUPER+ESC to lock the screen. That brings the image back. The laptop screen is un-affected, and I can keep using it while the external monitor is black.

It does not seem to be the monitor going to sleep or anything like that, the back-light is on even when the screen is black.

I think this has to do with tiling the windows. Cosmic is trying to re-arrange the windows while I am closing them, and somehow it fails and something crashes(?). The tiled windows left when the image comes back are not always arranged in a way that makes sense from what it looked like before the screen went black.

This problem can not be reproduced 100% of the time, as per my experience.

**Comment by canadaduane** [comment]
I'm not sure if this is related to your hardware, but on my Intel GPU i915 there seems to be a kernel bug outstanding that causes high-bandwidth external displayport/USB connections to cause the external screen to go black. The tell-tale sign is a "CPU Pipe B Fifo Underrun" message in dmesg (logs).

See https://gitlab.freedesktop.org/drm/i915/kernel/-/issues/5455

**Comment by BVildljung** [comment]
Great catch! I get `i915 0000:00:02.0: [drm] *ERROR* CPU pipe A FIFO underrun: port,transcoder` when the problem was triggered. So then it is not a Cosmic issue, I will close this.
