### ISSUE TITLE
Some dock/panel icons are transparent/missing

### ISSUE THREAD

**Issue by solkriegert** [pop-os/cosmic-epoch#1221]
Some of the icons on the taskbar are transparent and some of them are replaced by a placeholder(?). On the top right side some of the icons are transparent. The previews in settings are also missing.

Using Artix
![screenshot-2024-11-05-19-37-13](https://github.com/user-attachments/assets/6fda155f-291d-4eee-8811-8847caf66ec6)
![screenshot-2024-11-05-19-39-59](https://github.com/user-attachments/assets/2254431d-38e3-428e-8e3f-5726e693c5f1)
![screenshot-2024-11-05-19-40-37](https://github.com/user-attachments/assets/cb8442dc-758b-42d9-a5c0-ede55baaa8e7)

**Comment by danix1234** [comment]
I also have similar problem. Especially, whenever i move a slider, the percentage value disappear
![screenshot-2024-11-08-01-07-32](https://github.com/user-attachments/assets/7b8c6aca-2435-4804-bd34-41fffc154e9c)

I also have the same problem with app showing the default icon. Although for me it only happens with flatpak apps
![screenshot-2024-11-08-01-07-01](https://github.com/user-attachments/assets/66550495-f1e6-4ff9-816a-66b9d7b7dfb1)
(in the image, obs is the only app installed via flatpak)

**Comment by solkriegert** [comment]
UPD: i dont know what caused that to happen but after fully reinstalling the system the icons are

**Comment by solkriegert** [comment]
UPD: i dont know what caused that to happen but after reinstalling my system the icons are now present.

**Comment by mcrislip** [comment]
Same thing just occurred to me, my screens look as above. Tried other icon options, didn't help. Don't really want to reinstall to fix it.  Up to date alpha 4 on a lemur

**Comment by mcrislip** [comment]
Got an update, problem gone. That was fast
