### ISSUE TITLE
Input East-Asia Korean  languge.

### ISSUE THREAD

**Issue by gitnewbie8** [pop-os/cosmic-epoch#1246]
I am Korean. So, I tried to use ibus (ibus-hangul) and fcitx5 (fcitx5-hangul) to input Korean, but it doesn’t work at all in Cosmic apps. 

In other apps (like Firefox, Gedit, etc.), Korean input works just fine. 

However, in all Cosmic apps, such as Cosmic File, Cosmic Editor, and so on,,, neither ibus nor fcitx5 functions at all. Therefore, Korean language(Hangul) input is impossible

**Comment by gitnewbie8** [comment]
Now it worked very WEEEEEL! THANKS to Cosmic TEAM!

**Comment by ghost** [comment]
Fcitx5-unikey isn't working yet for me, should i open another issue or report it here?
