### ISSUE TITLE
Dual boot with windows 11

### ISSUE THREAD

**Issue by jkpjkpjkp** [pop-os/cosmic-epoch#1250]
I am trying to dual boot pop!os 24.04 alongside win11. 

since no guide is provided in issues or internet, is this not recommended? 

will update if succeeded/failed.

**Comment by jacobgkau** [comment]
COSMIC Epoch being a desktop environment, it doesn't really have anything to do with dual-booting. Pop!_OS 24.04 (alpha) uses the systemd-boot bootloader on EFI systems, just like 22.04 did. The same general guidance provided by the existing Pop!_OS support articles would still apply to 22.04: https://support.system76.com/articles/windows/#dual-booting-windows

**Comment by jkpjkpjkp** [comment]
Wow! thanks for the instant reply. 

I'm adding cosmos aside of my current windows, and it's rumored 3 months ago that 24.04 will not prompt for a dual boot w/ windows. (https://www.reddit.com/r/pop_os/comments/1ent5px/cosmic_x_pop_os_2404_how_is_your_experience/)

so that's what i'm concerned with. if everything works out i'll close this issue asap.

**Comment by jkpjkpjkp** [comment]
works. 

need to manually allocate / /home /boot/eft /data swap etc. cheers.
