### ISSUE TITLE
Where are the apps downloaded from cosmic store?

### ISSUE THREAD

**Issue by jkpjkpjkp** [pop-os/cosmic-epoch#1256]
where can i find the executable of apps downloaded from cosmic store? i'd like to add that to PATH for a good shell experience. cheers.

**Comment by git-f0x** [comment]
Apps are installed wherever your distro puts that package type, nothing related to COSMIC Store specifically.
For native distro apps, it's usually `/usr/bin`.

**Comment by jkpjkpjkp** [comment]
hmmm.. my vscode is definitely not in /usr/bin, or anywhere i'd normally looked into/suggested by llm. I actually did a `find` for 'code' and still missed it. same with google-chrome.

**Comment by jkpjkpjkp** [comment]
O i found it. e.g. for vscode its `/home/[username]/.local/share/flatpak/app/com.visualstudio.code/current/active/files/extra/vscode/code`

thks. silly of me lol.
