### ISSUE TITLE
Can't see icons on Ubuntu 22.04

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-epoch#126]
I don't know if this is intended ?
![2023-07-19-19-14-47-170](https://github.com/pop-os/cosmic-epoch/assets/78230769/7090903e-8dd0-4400-ba4f-78a099905481)
also, i copied the content of this [file](https://github.com/pop-os/cosmic-comp/blob/master_jammy/config.ron) inside `/etc/cosmic-comp/config.run` but shortcut doesn't works.

**Comment by Drakulix** [comment]
> i just figured out that it's config.ron instead, but by changing it, i get a black screen after login

Make sure to use the config file from the `cosmic-epoch` repo (in cosmic-epoch/cosmic-comp), if you installed it via those instructions. Otherwise you might have copied a too new config file for the version of cosmic-comp you are running, which will result in a black screen.

> I don't know if this is intended ?

You need the pop-icon-theme currently. `apt install pop-icon-theme`

**Comment by mmstick** [comment]
I'm not sure how updated Ubuntu's package is. You can get an updated jammy package from https://apt-origin.pop-os.org/release/pool/jammy/icon-theme/, or install it from source at https://github.com/pop-os/icon-theme

**Comment by wiiznokes** [comment]
indeed, i managed to make the shortcuts and icons work. thank both. just curious for the tiling, is there a particular order for the windows being displayed ? it looks great!

**Comment by Drakulix** [comment]
> is there a particular order for the windows being displayed?

Since the point of tiling is to avoid windows overlapping, I am not entirely sure which order you are referring to. Could you elaborate?

**Comment by wiiznokes** [comment]
For example, the last opened windows will take most of the place, then the second, ect.

**Comment by Drakulix** [comment]
Oh you mean, when switching into tiling mode? That is currently not defined, though the windows should be added to the tiling tree in order they were opened.

Once you are in tiling mode, new windows will split the currently focused window.
