### ISSUE TITLE
cosmic-applet-time memory leak, soft-locks system until automatically killed

### ISSUE THREAD

**Issue by Seltonu** [pop-os/cosmic-epoch#1264]
Reliably after a few hours using my system for general web browsing/coding, the cosmic-applet-time suddenly begins to take up all available system memory. I can tell when it's happening because my laptop fans begin to spin up to max and my CPU begins to throttle heavily, I imagine something is causing an infinite loop. My laptop also draws ~50w during this time when typical is closer to 15w

Generally after about a minute of this my system will soft-lock completely (unable to move mouse, etc.) until the applet gets automatically killed. If I am quick enough to kill the time applet I can prevent the soft lockup and my system will return to normal, however the time applet is of course gone from the panel.

Here is a screenshot I manage to get quickly before lockup. Happy to do any additional testing, I can reproduce reliably but randomly. Has been happening for at least about ~2 weeks now

![screenshot-2024-11-20-05-03-34](https://github.com/user-attachments/assets/6f8715c3-393d-4ded-ae9a-89e758aafe29)

**Comment by git-f0x** [comment]
What version of `cosmic-applets` do you have?

**Comment by joshuamegnauth54** [comment]
Related:

* pop-os/cosmic-applets#723
* pop-os/cosmic-epoch#1252

**Comment by joshuamegnauth54** [comment]
Actually this looks to be more specific to `time`. :thinking: You might want to check the first issue I mentioned above to see if you can provide extra info there.

**Comment by wash2** [comment]
This is most likely fixed if you try the latest commit from cosmic-panel

**Comment by Seltonu** [comment]
Apologies for the delayed response, I've been waiting to collect more info on this the next time it happens and it just... never happened again 😅 I think you may have been right @wash2 , this was likely fixed shortly after I posted this. Closing this issue!
