### ISSUE TITLE
Strange Blue Outline Appeared

### ISSUE THREAD

**Issue by Android789515** [pop-os/cosmic-epoch#1278]
When I switched to my fifth workspace this strange blue outline has appeared and will not go away.

![Blue Box](https://github.com/user-attachments/assets/0461822d-9f6f-4301-804a-8ae9e29ceca1)

**Comment by git-f0x** [comment]
That usually appears if you drag but not drop something over the desktop. I can be fixed by dropping anything on the desktop (e.g. an image from a browser).
It's a known issue.
