### ISSUE TITLE
White glitching windows and top panel

### ISSUE THREAD

**Issue by traklo** [pop-os/cosmic-epoch#1283]
Laptop screen works well after boot but gradually starts developing white artifacts on one of the inactive windows, this also affects the top panel in an unpredictable fashion. Changing scaling does not affect the issue. The issue cannot be seen in OBS so I am attaching a video recorded from a phone:

https://github.com/user-attachments/assets/10c572f0-5661-4ba5-aea9-a4d40a750703

Here is my device info list:

* Hardware
	+ Hardware model: LENOVO LNVNB161216
	+ Memory: 30.54 GiB
	+ Processor: AMD Ryzen 7 7840HS with Radeon 780M 
* Resolution of the affected screen:
	+ 2880x1800
* Graphics
	+ NVIDIA GeForce RTX 4060 Max-Q / Mobile (rev a1)
* Operating System
	+  Pop_OS 24.04 LTS
* Desktop Environment
	+ COSMIC (Alpha 3)
* Windowing System
	+ Wayland

**Comment by traklo** [comment]
The issue continues after upgrading to Alpha 4. It affects only the laptop screen, not the external display.

**Comment by traklo** [comment]
Here's my logs, in this case I triggered artifact a few minutes after the boot by moving tiled windows across workspaces and between my laptop screen and external display.  The issue became visible around 20:15:00. 

```
-- Boot --
Dec 12 20:10:03 user cosmic-comp[3172]: failed to read local shortcuts config 'system_actions': NoConfigDirec>
Dec 12 20:10:03 user cosmic-comp[3172]: Key-Binding 'Period' only matched case insensitive for "period"
Dec 12 20:10:03 user cosmic-comp[3172]: Key-Binding 'Comma' only matched case insensitive for "comma"
Dec 12 20:10:03 user cosmic-comp[3172]: Key-Binding 'Period' only matched case insensitive for "period"
Dec 12 20:10:03 user cosmic-comp[3172]: Key-Binding 'Comma' only matched case insensitive for "comma"
Dec 12 20:10:03 user cosmic-comp[3172]: tiling exceptions custom config error: GetKey("tiling_exception_custo>
Dec 12 20:10:03 user cosmic-comp[3172]: Unable to become drm master, assuming unprivileged mode
Dec 12 20:10:03 user cosmic-comp[3172]: Unable to become drm master, assuming unprivileged mode
Dec 12 20:10:03 user cosmic-comp[3172]: Failed to destroy old mode property blob: No such file or directory (>
Dec 12 20:11:32 user cosmic-comp[3172]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 48 > 24)
Dec 12 20:11:46 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:47 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:47 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:48 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:48 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:49 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:49 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:49 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:11:50 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
Dec 12 20:15:43 user cosmic-comp[3172]: Client bug: Unable to re-configure repositioned popup.
```

Are there any other logs I can provide to help diagnosing the issue?

Btw. my resolution is 2880x1800 with 175% Scale.

**Comment by Drakulix** [comment]
Can you try setting `COSMIC_DISABLE_DIRECT_SCANOUT=y` in `/etc/profile.d` and see if that solves it. Given you internal monitor is likely attached to the Radeon 780M, it might be an amdgpu bug, we might be able to work around with said environment variable.

**Comment by traklo** [comment]
Yes, this solved it, thank you.

**Comment by Drakulix** [comment]
That is not a fix, just a work-around. Thanks for reporting back.
