### ISSUE TITLE
numpad not working in almost every cosmic apps

### ISSUE THREAD

**Issue by paqwak** [pop-os/cosmic-epoch#1290]
I can use the numpad to log my user password at the login screen, but mostly every cosmic app like terminal, cosmic text editor, shop, file manager,  don't recognize the numeric keys. "Finder" works however, and obviously Firefox.

Fresh epoch install, everything updated.
(Keyboard is a steelseries).

(ofc I try the numpad lock ;))

**Comment by git-f0x** [comment]
Same issue as #1193, and pop-os/libcosmic#702. It affects rebased apps (the greeter isn't yet rebased, so it works on the login screen).
