### ISSUE TITLE
Workspaces Design Implementation

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-epoch#13]
Before considering various configurations it's worth mentioning that COSMIC workspaces are represented visually as a row of workspaces that stretches in one given direction. By default, workspaces are vertical and go from top to bottom. 
Keyboard shortcuts and gestures are built around that idea, helping one to navigate their desktop in any given direction, including possible setups with multiple displays. 

### Dynamic Workspaces
This is a default setting. Workspaces are dynamic, same as on Pop!_OS 22.04. There is always a new empty workspace created at the end of the workspace row. If one ends up with an empty workspace between other workspaces with windows open, this empty workspace is automatically removed. 

### Fixed number of workspaces
One can add or delete workspaces from the overview. When someone deletes a workspace with open windows, move windows to the neighboring workspace - previous workspace in most of the cases (one workspace up in the default configuration), next one if someone removes first workspace. 
When someone switches to fixed number of workspaces, keep the number of workspaces that was previously in use removing empty workspaces. For example, if one had 4 workspaces and an automatic empty workspace, leave 4 workspaces and remove the empty one. 

## Multi-monitor Behavior
There are two options for workspace behavior on Multiple Displays.

### Workspaces Span Displays
This is a default setting. All displays comprise a single workspace. The workspace switches on all of the displays when one moves to another workspace. 

### Displays have separate workspaces
Each display has its own set of workspaces. 

When displays are unplugged, move workspaces from that display to the “primary” (most internal, e.g. laptop screen) display. If we can remember, on a technical level, which workspaces were on that display we should re-place them on the same external display when it is plugged in again.

## How the shortcuts will work with multiple displays and workspaces

There are keyboard shortcuts that allow one to navigate windows and workspaces ([the shortcut system can be found here](https://github.com/pop-os/cosmic-epoch/issues/46)).

When **navigating windows with the keyboard shortcut** displays take priority over workspaces. So when the focus reaches the edge of the display and there is an adjacent display, the focus should move to that display. If there is no adjacent display but there is an adjacent workspace, move focus there.
![Dynamic-workspaces-span-displays](https://user-images.githubusercontent.com/57502897/191097989-02f42745-6164-41d6-bcc1-95cf1157a9e2.png)

When **switching to another workspace**, keyboard shortcut allows one to cycle through workspaces on Display 1 before jumping to an adjacent display. In other words, it progresses through workspaces in a direction until it reaches the end of workspaces on that display, at which point it progresses to the visible workspaces on the next display in that direction (if there is one).
When moving a window to another display, the behavior is the same as for switching to another workspace. In case when workspaces are dynamic, using the shortcut to move a window will skip over the dynamic workspace (the “empty” workspace) if moving to the empty workspace would leave the previous workspace empty (and would be deleted).
![workspaces-fixed-separate](https://user-images.githubusercontent.com/57502897/191098066-fe655ccd-c730-4bf3-869a-1f47b5520539.png)

## Workspace Orientation

Workspaces can be set to vertical (default) or horizontal. As mentioned above, keyboard shortcuts should work in any given direction by default. So when someone switches to horizontal workspaces, keyboard shortcuts will continue to work. If someone customizes the keyboard shortcuts prior to changing workspace orientation, we assume the change was intentional and the user will remember it.

In the beginning, gestures will not be customizable and will change based on the workspace orientation to match the direction of workspaces and placement of the workspace picker. The change will be reflected in Settings (mockup coming soon).

Workspaces Overview designs can be found [here](https://github.com/pop-os/cosmic-workspaces-epoch/issues/50).

**Comment by WillyWonksters** [comment]
You mentioned the automatic removal of empty workspaces, so here is a [related issue](https://github.com/pop-os/shell/issues/1602#issue-1636774524) I created.

**Comment by rosseljost** [comment]
It would be awesome if we could move whole workspace between displays.
For example: I have all my chat apps open on the secondary monitor, but would like to move the whole workspace over if I have a longer conversation without moving single windows.
As you already consider moving workspaces on display connects, this would be an awesome addition I think
