### ISSUE TITLE
Firefox Picture-in-Picture sticky-window does not work (cannot right click)

### ISSUE THREAD

**Issue by Seltonu** [pop-os/cosmic-epoch#1302]
Firefox has had a built in PiP video feature for a few years now, and in previous versions of Pop it was possible to stick this small pop-out window to be placed in front of all windows (it might have even been automatic, I don't quite remember).

In COSMIC, this behavior is absent. I am unable to right click the PiP window to select "sticky window".

To test load up any youtube video, hover your mouse over it, and click the pop-out button that appears. Then try to right click it and see that no context-menu appears.

**Comment by Drakulix** [comment]
There is a way to do this currently, by binding the "Sticky window" shortcut in settings.
Opening the compositor context menu requires the client to request it, which is usually done for titlebars, but firefox pip window lacks that by design, so you only get the firefox context menu.

See also https://github.com/pop-os/cosmic-comp/issues/909 for a request to provide a way to access the menu without a shortcut.

**Comment by Seltonu** [comment]
@Drakulix ah my apologies, thank you for pointing me in the right direction I missed that when I searched issues for Firefox PiP. It looks like the discussion there covers exactly what I'm looking for, so I will go ahead and close this issue!

**Comment by MagnetosphereLabs** [comment]
If anyone is still having these types of issues on Pop!_OS COSMIC, we have an automated workaround with Firefox picture in picture that we demonstrate [here](https://www.youtube.com/watch?v=PiUm4cZYG3Q). And we uploaded it [here](https://github.com/MagnetosphereLabs/cosmic-firefox-pip-fix) on GitHub if you would like to try it.

**Comment by leviport** [comment]
@MagnetosphereLabs please don't spam that comment across multiple threads.

**Comment by MagnetosphereLabs** [comment]
The people affected were in different threads so I was including all the people who said they were affected by this that I saw. I don't think helpful information is spam, but I'll stop posting here about this if you'd like.
