### ISSUE TITLE
Gaps can't get below 3 in the Comsic settings

### ISSUE THREAD

**Issue by VasilisManol** [pop-os/cosmic-epoch#1315]
In Cosmic Settings it is impossible to set the "Gaps around tiled windows" to below 3 no matter the value of the "Active window hint size". It is possible to set them in the config file but not from the UI.

**Comment by bhh32** [comment]
I'll look into it.

**Comment by VasilisManol** [comment]
Thanks! Here  is the issue https://github.com/pop-os/cosmic-settings/issues/805 .
