### ISSUE TITLE
 I'm trying to Screenshare using Teams PWA (Wayland), which closes when I start sharing,

### ISSUE THREAD

**Issue by gilvbp** [pop-os/cosmic-epoch#1319]
Journalctl log: ERROR xdg_desktop_portal_cosmic::screencast_thread] screencopy failed: Value(BufferConstraints). https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/112

**Comment by git-f0x** [comment]
Please don't create duplicate issues. It's a known issue and is being worked on.
