### ISSUE TITLE
Cosmic donf profile missing

### ISSUE THREAD

**Issue by Samq64** [pop-os/cosmic-epoch#1321]
The COSMIC dconf profile is missing which breaks the excremental GTK theming and causes some programs such as steam to crash. I this wasn't a problem on alpha 3. I also have Hyprland and Plasma installed.

COSMIC version: Alpha 4
OS: Arch Linux

**Comment by Drakulix** [comment]
We pushed a fix yesterday, that was necessary for Pop!_OS and might need to be adopted for arch linux. https://github.com/pop-os/cosmic-session/pull/95

We don't maintain the arch linux packaging, so raise this issue with your packager please.
