### ISSUE TITLE
Firefox video and overlay issue

### ISSUE THREAD

**Issue by whitaar1** [pop-os/cosmic-epoch#1333]
In Firefox when watch video in full screen and you increase volume or display brightness and the overlay percentage bar appears either the video control disappear and resize the video leaving a empty box on the bottom of the screen or just  resize the video leaving a empty box on the bottom of the screen until you leave full screen and return to it.
![screenshot-2024-12-09-17-23-11](https://github.com/user-attachments/assets/dbc021b5-1fb3-4d5c-9f81-96ad7979ba16)

**Comment by git-f0x** [comment]
Same issue as pop-os/cosmic-comp#487.
