### ISSUE TITLE
[Bug] Crash when mirroring one screen to another

### ISSUE THREAD

**Issue by herrdiener** [pop-os/cosmic-epoch#1348]
Trying to mirror my laptop screen to any external monitor via HDMI on Alpha 4 crashes Cosmic with the following error:

```
thread 'main' panicked at 'Callback creating object zwlr_output_configuration_head_v1@9[39] did not provide any object data.': /build/cosmic-comp-SKtFZZ/cosmic-comp-0.1~1733758395~24.04~9b50d0f/vendor/wayland-backend/src/rs/server_impl/common_poll.rs:288
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /build/cosmic-comp-SKtFZZ/cosmic-comp-0.1~1733758395~24.04~9b50d0f/vendor/wayland-backend/src/rs/server_impl/handle.rs:179
````

[journalctl output](https://github.com/user-attachments/files/18099829/screencrash.log)

Extending the desktop to another screen works perfectly, the crash happens only upon choosing the mirroring option in the screen settings.

OS: Pop_OS! 24.04
DE: Cosmic Alpha 4
CPU: Intel i7-1355U
GPU: NVIDIA GeForce RTX 2050
NVIDIA driver: Proprietary 560.35.03
Compositor: Wayland

**Comment by ids1024** [comment]
This should be fixed by https://github.com/pop-os/cosmic-comp/pull/1047.
