### ISSUE TITLE
Feature Request: Make VPN connections available from within the Wifi selection menu.

### ISSUE THREAD

**Issue by mrust1219** [pop-os/cosmic-epoch#1360]
In Gnome and KDE it's possible to access VPN connections from within the wifi menu in the panel. It's possible to do this in Cosmic with the Network-Manager-Applet, however it is redundant to have the applet in the system tray when Cosmic has it's own applet.

Furthermore, within the Cosmic-Settings, it works when you initially authenticate to a VPN, however if you disconnect and reconnect, and you use 2FA codes appended to a password, this causes subsequent connections to fail. This is also solved by utilizing Network-Manager-Applet.

I believe what causes this is the Cosmic-settings automatically save the initial credentials you give it, and this could be solved by prompting for the password each time, like how Gnome and KDE do it.

**Comment by leviport** [comment]
Some designs have already been made for VPN connections in the network applet, so we should track this feature in https://github.com/pop-os/cosmic-applets/issues/623
