### ISSUE TITLE
idea 3: Option to move window buttons to left and... "intelligent close button"

### ISSUE THREAD

**Issue by ardnod** [pop-os/cosmic-epoch#1371]
Like on Firefox after my little modification

https://github.com/user-attachments/assets/bcd6470f-383a-4609-b17c-c22a58aa7c4c

**Comment by git-f0x** [comment]
Duplicate of #850 and #640.

**Comment by ardnod** [comment]
In the video I showed how closing the stacked window on the bar can behave in this case (window buttons on left):
the application icon disappears and the close button appears.
I think this is a good idea.

**Comment by ardnod** [comment]
![stacked](https://github.com/user-attachments/assets/d81672ab-a14f-4ada-b770-22c022b241d2)

**Comment by leviport** [comment]
We can track this request in those other issues. Duplicates just make things more difficult to manage. Thank you for the request though.
