### ISSUE TITLE
Clipboard manager

### ISSUE THREAD

**Issue by ardnod** [pop-os/cosmic-epoch#1373]
But with better behavior than in GNOME (e.g. via extensions).
I prefer the behavior like in KDE.

**Comment by git-f0x** [comment]
There's a clipboard manager applet: https://github.com/cosmic-utils/clipboard-manager

**Comment by OwczarekGit** [comment]
Hello, perhaps you could consider providing 1st party clipboard manager with the DE itself?
The mentioned clipboard-manager has not been very reliable in my experience, there is plenty of problems with it including hard locking of applications.

IMHO relying on 3rd party solution for such a core functionality seems to introduce unnecessary friction.
