### ISSUE TITLE
"Run as root" in context menu for apps

### ISSUE THREAD

**Issue by bala7s** [pop-os/cosmic-epoch#1374]
There should be a GUI method running apps as root user besides using command line and sudo. For some reason there is no DE having this simple feature.

![screenshot-2024-12-17-11-08-02](https://github.com/user-attachments/assets/cdd9b0fc-8d40-4b8a-9609-eeb18216d370)

**Comment by Drakulix** [comment]
Because GUI apps running as root is by default not accessible with modern X11 (as it is a security concern) and impossible with Wayland. Applications needed elevated privileges should request these permissions through polkit instead.
