### ISSUE TITLE
Security Warning in Tor Browser on Pop!_OS with COSMIC

### ISSUE THREAD

**Issue by archalchemy** [pop-os/cosmic-epoch#1378]
On Pop!_OS with the COSMIC desktop environment, the Tor Browser displays a security warning stating:
"Some of Tor Browser's security features may offer less protection on your current operating system."

This message appears persistently when launching Tor Browser, even though the operating system and browser are properly configured.

![screenshot-2024-12-17-21-13-29](https://github.com/user-attachments/assets/6f48e98c-3774-4780-b7d7-b437249cb0e4)

**Comment by git-f0x** [comment]
It's a known issue on the Tor GitLab, unrelated to COSMIC: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/43101

**Comment by archalchemy** [comment]
> It's a known issue on the Tor GitLab, unrelated to COSMIC: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/43101

Thank you, I will now close the Issue.
