### ISSUE TITLE
Fedora, no more disk space

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-epoch#138]
After building the DE on Fedora, i feel like it messed up my install. I post an issue on Fedora forum already https://discussion.fedoraproject.org/t/why-i-have-no-more-disk-space-in-usr/89997 
but they redirect me here.

basically, i can't install package because `/usr` is full (but it say it fill at 1%), and `/usr` is in read-only.

I executed `sudo setenforce 0` and reseted it to 1.

gdm package is not installed.
```
sudo systemctl restart gdm
Failed to restart gdm.service: Unit gdm.service not found.
```
If you have an idea on how can i repair my install, please let me know :pray:

**Comment by PixelDoted** [comment]
I had the same "read-only filesystem" issue on PopOS 22.04
and this seems to be the cause: [freedesktop systemd-sysext](https://www.freedesktop.org/software/systemd/man/systemd-sysext.html)
`System extension images are strictly read-only, and the host /usr/ and /opt/ hierarchies become read-only too while they are activated.`

Disabling `systemd-sysext` will fix the issue, which will also disable your `cosmic-epoch` build.
```
sudo systemctl disable systemd-sysext
```

**Comment by wiiznokes** [comment]
thanks, that works :pray: . I will add `sudo systemctl stop systemd-sysext` if someone will have the same issue

**Comment by Drakulix** [comment]
The systemd-extension installation method is meant as an easy way to test the desktop, while proper packaging is not available, without modifying your system. It is not meant as a permanent installation method (at least not on normal mutable installations, on read-only systems like silverblue this is more feasible).

Feel free to submit a PR highlighting this in the README and explaining the effects.
