### ISSUE TITLE
Install pop-launcher with apt?

### ISSUE THREAD

**Issue by hongquan** [pop-os/cosmic-epoch#1384]
Hi,
I tried to build cosmic-epoch on Ubuntu, the guide tells to install `pop-launcher` with `apt`. But I don't know where `pop-launcher` is from. It is not in Ubuntu repo.

**Comment by git-f0x** [comment]
You can build `pop-launcher` from source, since it isn't packaged for Ubuntu. It's available in the Pop!_OS, Fedora, Arch and some other repos.

**Comment by hongquan** [comment]
Ah, thanks.
