### ISSUE TITLE
Gaps around window when snapping

### ISSUE THREAD

**Issue by FlamingPhoenix40** [pop-os/cosmic-epoch#1400]
From both Windows and earlier versions of PopOS, when I snap a window by dragging it to the side of my screen, I'm used to seeing the window snap to the edges in that region. Now however, the window no longer snaps to the edges, causing whatever is behind it to be visible. This happens to all partial snaps, maximizing doesn't have this problem. For example, say I snap a window to the right, now I can see my wallpaper around the top, bottom, and right edges of the window. The amount of gap also isn't equal at every side. I have my dock set to auto-hide, and the gap at the bottom seems to be only 1 or 2 pixles high, where the other sides are pretty substantial.

This behaviour is also different from what I've seen in screenshots in blogposts. There the window does seem to snap to the edges properly.

I will add a screenshot of my situation. I downloaded, installed and updated yesterday, so this version is pretty recent.
![screenshot-2024-12-25-12-51-29](https://github.com/user-attachments/assets/d6894add-0b53-4339-ae3f-677b9b0a1ee8)
![screenshot-2024-12-25-12-52-16](https://github.com/user-attachments/assets/6a88248f-2ec4-4a09-887c-ac40bf48fca9)

**Comment by git-f0x** [comment]
This is intended behavior. It matches your **Gaps around tiled windows** setting in COSMIC Settings.

**Comment by bhh32** [comment]
> From both Windows and earlier versions of PopOS, when I snap a window by dragging it to the side of my screen, I'm used to seeing the window snap to the edges in that region. Now however, the window no longer snaps to the edges, causing whatever is behind it to be visible. This happens to all partial snaps, maximizing doesn't have this problem. For example, say I snap a window to the right, now I can see my wallpaper around the top, bottom, and right edges of the window. The amount of gap also isn't equal at every side. I have my dock set to auto-hide, and the gap at the bottom seems to be only 1 or 2 pixles high, where the other sides are pretty substantial.
> 
> 
> 
> This behaviour is also different from what I've seen in screenshots in blogposts. There the window does seem to snap to the edges properly.
> 
> 
> 
> I will add a screenshot of my situation. I downloaded, installed and updated yesterday, so this version is pretty recent.
> 
> ![screenshot-2024-12-25-12-51-29](https://github.com/user-attachments/assets/d6894add-0b53-4339-ae3f-677b9b0a1ee8)
> 
> ![screenshot-2024-12-25-12-52-16](https://github.com/user-attachments/assets/6a88248f-2ec4-4a09-887c-ac40bf48fca9)
> 
> 

You might want to check your active hint and gap size in the settings. As the last reply was it's intended. Active hint can be smaller than gaps but gaps can't be smaller than active hint. This would cause this behavior if your active hint is 0 and your gap size was not.

**Comment by FlamingPhoenix40** [comment]
I see, I completely missed that setting haha. However, it seems that while I can turn Active Hint to 0, gaps around tiled windows cannot go lower than 3. This doesn't change whether I turn active hint on or off in the toggleable setting either. Is that also intended? Because your answer hints to that it should be possible.

In the meantime I have switched to a different distro, because I wanted a newer base than the older 22.04, but Cosmic is not finished enough for my daily use yet with missing features and stuff that's broken like the other issue I posted about panel indicators not updating.

**Comment by FlamingPhoenix40** [comment]
Finally got it to work haha. Initially after reinstall I still couldn´t get it, but after updating and a reboot, now it works. This is one of the quirks I've noticed haha Settings not always working properly right away, needing a reboot or quit and reopen, but that is to be expected of an alpha :)
