### ISSUE TITLE
Steps to test on Fedora 39 Beta Gnome Edition

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-epoch#141]
Feel free to close this issue if this is not wanted. This will help me to remember the steps for next time and also maybe help some people.

# Rustup
if you're using rustup
```
rustup default stable
```

# Dependencies
```
sudo dnf install just rustc libglvnd-devel libseat-devel libxkbcommon-devel lld libinput-devel glib2-devel dbus-devel wayland-devel clang-devel cargo mesa-libgbm-devel pipewire-devel -y
```

# Clone + Build
```
git clone --recurse-submodules https://github.com/pop-os/cosmic-epoch
cd cosmic-epoch
just sysext
```

# Copy system extension
```
sudo mkdir -p /var/lib/extensions
sudo rm -rf /var/lib/extensions/cosmic-sysext/
sudo cp -r cosmic-sysext /var/lib/extensions
```

# Copy cosmic-comp config file (enable tilling at the end of the file)
```
sudo mkdir /etc/cosmic-comp
sudo cp cosmic-comp/config.ron /etc/cosmic-comp
sudo -e /etc/cosmic-comp/config.ron
```

# Install pop-os icons
```
cd ..
git clone https://github.com/pop-os/icon-theme pop-icon-theme --depth=1 --branch=master
sudo dnf install meson -y
cd pop-icon-theme
meson build
sudo ninja -C "build" install
```

# Enable system extension
```
sudo systemctl enable --now systemd-sysext
sudo systemd-sysext refresh
```

# Disable permission tool used by Fedora
```
sudo setenforce 0
```

# Quick Disable/Enable

## enable (start testing)
```
sudo systemctl enable --now systemd-sysext
sudo systemd-sysext refresh
sudo setenforce 0
sudo systemctl restart gdm
```

## disable (stop testing)
```
sudo setenforce 1
sudo systemctl disable systemd-sysext
sudo systemctl stop systemd-sysext
```

# Log
```
journalctl --user _EXE=/usr/bin/cosmic-session -r -S -10m > ~/log.txt && code ~/log.txt
```

**Comment by wiiznokes** [comment]
I really hope too. Use cosmic as system extension is very limiting. But I don't think it will land in federa repo before an alpha release. 
I tried to package cosmic as rpm one day but I don't think it make sens to having build files upstream. But idk because there is debian, nix, so why not rpm afterall

**Comment by KaseyTheJackal** [comment]
On Fedora 39 KDE I had to install pam-devel and gtk3-devel, so for me the whole command to install stuff is

`sudo dnf install just rustc libglvnd-devel libseat-devel libxkbcommon-devel lld libinput-devel glib2-devel dbus-devel wayland-devel clang-devel cargo mesa-libgbm-devel pipewire-devel pam-devel gtk3-devel meson -y`

**Comment by lucamosca1** [comment]
After having installed updated dependencies I still not able to build it. Error is

  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags flatpak flatpak >= 1.11.1

  The system library `flatpak` required by crate `libflatpak-sys` was not found.
  The file `flatpak.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `flatpak.pc`.

warning: build failed, waiting for other jobs to finish...
error: Recipe `build-debug` failed on line 34 with exit code 101
error: Recipe `build` failed on line 23 with exit code 101

**Comment by wiiznokes** [comment]
@lucamosca1 maybe it's because you don't have flatpak installed on your system. Try `sudo dnf install flatpak`. Idk where this crate is used tho

**Comment by lucamosca1** [comment]
flatpak is already installed on a clean fedora 39

**Comment by ErikReider** [comment]
> flatpak is already installed on a clean fedora 39

You need `flatpak-devel`

**Comment by lucamosca1** [comment]
I confirm I needed also flatpak-devel, the list of pre-requisite should be updated. After that I'm still not abe to test in a virtual machine, but this should be an other issue

**Comment by bhh32** [comment]
I also confirm I needed flatpak-devel. However, after I successfully built and logged in to COSMIC, my super key didn't bring any search up and I could get to anything but the settings applet.

**Comment by mmstick** [comment]
@bhh32 Do you have `/etc/cosmic-comp/config.ron`?

**Comment by steveyackey** [comment]
These tips were all super helpful! I got to the same spot as @bhh32. I'm on Fedora 39, installed the extra packages listed, and made sure config.ron was present. Seem to not be getting any additional output when running `cosmic-launcher` from the terminal either. Any ideas of additional logs I may be missing for hints?

**Comment by Drakulix** [comment]
> These tips were all super helpful! I got to the same spot as @bhh32. I'm on Fedora 39, installed the extra packages listed, and made sure config.ron was present. Seem to not be getting any additional output when running `cosmic-launcher` from the terminal either. Any ideas of additional logs I may be missing for hints?

For cosmic-launcher to work correctly as a frontend, you need the backend-service pop-launcher installed as well: https://github.com/pop-os/launcher/. That is not part of this repository.

**Comment by steveyackey** [comment]
Thanks so much, that took care of it!

**Comment by RyzenDew** [comment]
wish these where added to the readme.

**Comment by RyzenDew** [comment]
```rust-pam-sys-devel``` is needed also

**Comment by skewballfox** [comment]
> ```
> sudo systemctl enable --now systemd-sysext
> sudo systemd-sysext refresh
> ```
> 
> # Disable permission tool used by Fedora
> ```
> sudo setenforce 0
> ```
> 
> # Quick Disable/Enable
> ## enable (start testing)
> ```
> sudo systemctl enable --now systemd-sysext
> sudo systemd-sysext refresh
> sudo setenforce 0
> sudo systemctl restart gdm
> ```
> 
> ## disable (stop testing)
> ```
> sudo setenforce 1
> sudo systemctl disable systemd-sysext
> sudo systemctl stop systemd-sysext
> ```
> 
> # Log
> ```
> journalctl --user _EXE=/usr/bin/cosmic-session -r -S -10m > ~/log.txt && code ~/log.txt
> ```

@wiiznokes could you edit this to put `setenforce 0` before enabling systemd-sysext. On the current version of fedora (40), this seems to break both use of sudo and user login, and at least on my system seems to also break the boot process. so the only way I've found so far is to boot from a usb and change selinux to permissive in `/etc/selinux/config`. I suspect it might be related to [this closed systemd issue](https://github.com/systemd/systemd/issues/23971)

**Comment by mmstick** [comment]
@skewballfox If you're on Fedora, there's no need to use systemd system extensions. You can get COSMIC officially from here: https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/

**Comment by skewballfox** [comment]
> @skewballfox If you're on Fedora, there's no need to use systemd system extensions. You can get COSMIC officially from here: https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/. Packages are in the process of being reviewed and accepted into the official repositories.

In my case I'm testing changes related to a PR I'm working on for cosmic-session, so can't really use the COPR.

**Comment by wiiznokes** [comment]
You shouldn't rely on this issue, use the copr instead

**Comment by skewballfox** [comment]
> You shouldn't rely on this issue, use the copr instead

like I said [I'm testing changes related to a PR](https://github.com/pop-os/cosmic-session/pull/54). I think it's worth updating the initial post with the order requirements because, at least *some* of the people who look this issue up are trying to eat their own dogfood.

**Comment by mmstick** [comment]
None of us are using this for developing on COSMIC. You can clone a specific repo and build/install it locally. No need to go through this for that.

**Comment by wiiznokes** [comment]
Oops, didn't see the previous responses, but yeah, idt using systemd extensions is a good way to testing things
