### ISSUE TITLE
Implementation of widget

### ISSUE THREAD

**Issue by unknownK19** [pop-os/cosmic-epoch#146]
Hello there,
 It will be good, if widget are implement on Cosmic DE, I suggest you to implement this [Eww](https://github.com/elkowar/eww)
Thank you ;)
here's a sample you may like it.
https://i.ytimg.com/vi/TUnvG6VMkcU/maxresdefault.jpg
We can make own widget ;)

**Comment by Drakulix** [comment]
Eww on wayland just requires the wlr-layer-shell protocol, which we already support.

**Comment by unknownK19** [comment]
It will be nice if Cosmic DE comes with Eww like KDE widget

**Comment by wiiznokes** [comment]
This makes me think, will desktop icons be implemented? And if so, maybe the widgets can be integrated on the desktop

**Comment by gabriele2000** [comment]
> will desktop icons be implemented?

I remember a reply by @mmstick on reddit at the same question, question that I made months ago.
Yes, they're gonna implement them!
