### ISSUE TITLE
rust dm

### ISSUE THREAD

**Issue by daktras420** [pop-os/cosmic-epoch#157]
my suggestion since the desktop is written in rust and all the apps it would make a lot of sense to change the display manager aka login manager to a rust based 
heres a project i am testing out as i write this
https://github.com/coastalwhite/lemurs

**Comment by wiiznokes** [comment]
I think there is already https://github.com/pop-os/cosmic-greeter whitch is use for this

**Comment by PixelDoted** [comment]
> I think there is already https://github.com/pop-os/cosmic-greeter whitch is use for this

That's the lock screen, #15 is for the display manager

**Comment by wiiznokes** [comment]
> That's the lock screen, #15 is for the display manager

Looking at https://blog.system76.com/post/locked-and-loaded-with-new-cosmic-de-updates , you can login with it🤔

**Comment by wiiznokes** [comment]
no worry, I never tested it either, idk how to activate it

**Comment by daktras420** [comment]
So i have confirmed the rust dm from tue aur package cosmic-epoc did not install it. And i found thanks to the reference but cant find the repo to compile and test. Once i compile it ill be able to figure out implementing and testing ill help make a guide to.

**Comment by PixelDoted** [comment]
> Looking at https://blog.system76.com/post/locked-and-loaded-with-new-cosmic-de-updates , you can login with it🤔

It's probably talking about the design, not the implementation.

`cosmic-greeter` won't start without a compositor, which a display manager wouldn't need...?

**Comment by wiiznokes** [comment]
> It's probably talking about the design, not the implementation.

I don't think so, i think it is implemented

**Comment by jackpot51** [comment]
coamic-greeter is not just the lock screen for cosmic, it is also a log in screen for greetd, which is also written in Rust. At the moment it is not hooked up by this repository, as doing so is highly distribution specific

**Comment by daktras420** [comment]
Ok cool ill set up thanks for clarification.

**Comment by daktras420** [comment]
So i can conferm either its my setup when using cosmic-comp as the wayland compositer.
Cage cosmic-greeter
Works for the most part
Settings and other buttons don't 
Changing the session does 
And you can login with it.

**Comment by Vixea** [comment]
Does it make sense to close this considering the original issue is resolved?

**Comment by jokeyrhyme** [comment]
I did ask about https://github.com/pop-os/cosmic-comp/issues/213 a while back, which would mean we could replace `cage` with `cosmic-comp` here

**Comment by Drakulix** [comment]
> I did ask about [pop-os/cosmic-comp#213](https://github.com/pop-os/cosmic-comp/issues/213) a while back, which would mean we could replace `cage` with `cosmic-comp` here

Using cage at the moment is a short-term solution. Replacing it is on our radar, but not a huge priority atm.
