### ISSUE TITLE
Running on a raspberry pi not working

### ISSUE THREAD

**Issue by kyteware** [pop-os/cosmic-epoch#164]
When attempting to use `cosmic-epoch` on my raspberry pi 4, I get flashes of black, white and grey on my monitor and I am forced to restart. Anyone have any solutions or hunches? I'm happy to take any logs if needed.

**Comment by Drakulix** [comment]
How are you launching it?

**Comment by Dworv** [comment]
To launch it, I just followed the instructions (I'm running pop-os for rasp pi).
- `apt install cosmic-*`
- `sudo service gdm3 restart`
- Log out
- Login using COSMIC

When it launches, there is a pink flash, and then a grey screen with a cursor in the top left briefly flashes every few seconds before going back to the black screen.

**Comment by kyteware** [comment]
I'll close this since its been a while and you have enough issues as is.
