### ISSUE TITLE
Feature Request: Add Stacked Windows Functionality in Tiling Mode like i3wm

### ISSUE THREAD

**Issue by rmasad** [pop-os/cosmic-epoch#174]
I've noticed that one feature common in other window managers, especially i3wm, is missing - the ability to have stacked windows in the tiling mode.

The stacking feature in i3wm allows windows to be 'stacked' on top of each other in a single tile, with the user being able to switch between them easily. This is particularly useful for organizing and managing multiple applications within the same workspace without sacrificing the benefits of tiling.

I believe adding this functionality to Cosmic's tiling mode would greatly enhance its usability, especially for users who transition from i3wm or similar window managers. It would offer a more versatile and efficient way of managing windows, catering to a wider range of user preferences.

![image](https://github.com/pop-os/cosmic-epoch/assets/49078/5f915707-7d51-41ad-9bf7-5e36448df8b5)

**Comment by mmstick** [comment]
This is already implemented
