### ISSUE TITLE
There is no app to connect bluetooth devices

### ISSUE THREAD

**Issue by gantryyork** [pop-os/cosmic-epoch#183]
- Settings doesn't have a "Connected Devices" or "Bluetooth" set of features
- There is no tool bar applet showing Bluetooth on

**Comment by gabriele2000** [comment]
> * Settings doesn't have a "Connected Devices" or "Bluetooth" set of features

They still have to build the screen

>     * There is no tool bar applet showing Bluetooth on

I have it, that's weird
![Screenshot_2024-01-16_11-06-25](https://github.com/pop-os/cosmic-epoch/assets/12186181/e548356f-11fd-40e5-b828-378b8a6147e0)

**Comment by gantryyork** [comment]
I'm using a Lemur Pro with the latest version of Cosmic.  I don't see the icon at all.  
Unfortunately, I can not take a screenshot.  cosmic-screenshot throws an error when I run it.  I reported that in a different issue.

**Comment by gabriele2000** [comment]
> I'm using a Lemur Pro with the latest version of Cosmic. I don't see the icon at all. Unfortunately, I can not take a screenshot. cosmic-screenshot throws an error when I run it. I reported that in a different issue.

Hmm... did you try to see if the applet is enabled?

**Comment by gabriele2000** [comment]
@gantryyork so what fixed the issue?
The applet was really disabled?
