### ISSUE TITLE
[Feature Request] Focus follows cursor

### ISSUE THREAD

**Issue by gantryyork** [pop-os/cosmic-epoch#185]
It seems Cosmic is only click to focus.  It would be nice if point to focus were available too.

**Comment by snaggen** [comment]
I suggest to specify this as "sloppy focus" , since that changes focus on mouse pointer enter. This is normally what people mean with point to focus I think. However, there is also another mode where focus is lost on exit. So, I cast a vote for sloppy focus.

**Comment by gabriele2000** [comment]
While we're talking about focus, doesn anyone else has Spotify (flatpak) fighting with discord and firefox over who has the focus?

**Comment by Drakulix** [comment]
> While we're talking about focus, does anyone else has Spotify (flatpak) fighting with discord and firefox over who has the focus?

Known Xwayland bug.

**Comment by gabriele2000** [comment]
> Known Xwayland-specific bug.

Heh, I knew it!
Thanks for confirming it.

> It seems Cosmic is only click to focus. It would be nice if point to focus were available too.

Now that I'm thinking of it, cosmic-terminal has "point to focus" mode, you need to activate "focus follow mouse" in its settings.
Other apps? No(t yet?).

**Comment by LunNova** [comment]
I'd like this. Most implementations of focus follow mouse have a configurable delay before focus moves and it'd be good to have that here.

**Comment by MrGamerDoesGames** [comment]
Second this, focus follow mouse would be awesome

**Comment by kekkoudesu** [comment]
I've found Focus Follows Cursor really useful on a KDE system with multiple monitors. But KDE and GNOME alike implement in a way that frustrates me. When I switch workspaces, I'll regularly find my cursor directly over a window, but it won't be focused; a window on another monitor will be focused instead. The way to get the window under my cursor focused is to move my cursor from the current monitor to another monitor and back to re-focus it (or to click it).

I'm not quite sure what causes it, but I'd love if COSMIC implemented a Focus Follows Cursor feature that didn't do that :slightly_smiling_face:

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/issues/564

**Comment by Drakulix** [comment]
Fixed via https://github.com/pop-os/cosmic-comp/pull/582
