### ISSUE TITLE
Oryx Pro w/Nvidia Missing icons

### ISSUE THREAD

**Issue by bhh32** [pop-os/cosmic-epoch#188]
When I installed COSMIC on Pop!_OS today from the pop repo, the icons are missing for min, max, and exit on the windows. The icon for the launcher on the bottom of the screen also is missing, and clicking the launcher doesn't do anything.

**Comment by bhh32** [comment]
Here are some screenshots to show the icon issues. I had to take them with my phone camera because I could not get any screenshot application to work while using COSMIC.
![cosmic_dock_icons](https://github.com/pop-os/cosmic-epoch/assets/17814219/a53b57e3-30f2-406e-83bc-d5f5d8ef9e35)
![cosmic_files_icons](https://github.com/pop-os/cosmic-epoch/assets/17814219/de407182-19fb-47bc-983d-ec6eac0067ce)
![cosmic_term_icons](https://github.com/pop-os/cosmic-epoch/assets/17814219/f97b0fbf-da6c-4c6b-8889-ce85db2e2bd9)

**Comment by James-Randall-14** [comment]
Hello, I am having a similar issue on arch linux. How did you fix this?

**Comment by privatefound** [comment]
https://github.com/pop-os/cosmic-epoch/issues/451
Read this :)
