### ISSUE TITLE
Convergence?

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#191]
Will Cosmic provide a consistent experience, whether one is using it on a big screen with mouse and keyboard or on a small touchscreen?

**Comment by gabriele2000** [comment]
> Will Cosmic provide a consistent experience, whether one is using it on a big screen with mouse and keyboard or on a small touchscreen?

You mean "responsive design"?

**Comment by Thatoo** [comment]
Something like responsive design for website indeed except that we are talking about an OS

**Comment by mmstick** [comment]
First party applications are being optimized for tiling environments, so they will be responsive to wide and narrow widths.

**Comment by Thatoo** [comment]
applications I'm sure it will but what about Cosmic itself, the top bar with date? icon with menu? the app launcher?

**Comment by gabriele2000** [comment]
> applications I'm sure it will but what about Cosmic itself, the top bar with date? icon with menu? the app launcher?

Of course, everything is (obviously) scaled according to the screen size.
