### ISSUE TITLE
Issue in install on Pop!_OS

### ISSUE THREAD

**Issue by lucamosca1** [pop-os/cosmic-epoch#192]
In main page https://github.com/pop-os I followed the steps to install it on Pop!_OS 22.04 just downloaded from website and installed in a VirtualBox virtual machine (installation from scratch)

But the step
sudo setenforce 0
ends in command not found.

Is something missing?

**Comment by mmstick** [comment]
Pop!_OS doesn't have SELinux. That is for Fedora.

**Comment by jacobgkau** [comment]
We don't have SELinux by default. I guess it's possible to manually install? Otherwise, that note should probably be in a separate section from `Installing on Pop!_OS`.
