### ISSUE TITLE
Set Keyboardlayout

### ISSUE THREAD

**Issue by koleesch** [pop-os/cosmic-epoch#201]
Hello,

I use the german keyboard layout and in gnome it is set. But if I start cosmic the cosmic desktop, the layout is the us keyboard layout. How can I set the keyboard layout?

Greetings

**Comment by wiiznokes** [comment]
I succeed to set it to azerty this way:

```
nano .config/cosmic/com.system76.CosmicComp/v1/xkb_config
```
and write this in it
```
(rules:"",model:"",layout:"fr",variant:"azerty",option:none)
``` 
But idk if this is a good way of doing it

**Comment by mash-graz** [comment]
I stumbled over the same issue...

I can't change any language/keyboard related settings via the config GUI and WLAN control also doesn't work.

**Comment by sandboiii** [comment]
Thank you @wiiznokes for pointing out config file. I've managed to setup switching keyboard layout with caps lock using same values I use for Hyprland config.

<h5 a><strong><code>.config/cosmic/com.system76.CosmicComp/v1/xkb_config</code></strong></h5>

```
(
    rules: "",
    model: "",
    layout: "us,ru",
    variant: "lang",
    options: Some("grp:caps_toggle"),
)
```

**Comment by pauldesmondparker** [comment]
@sandboiii Your response is from four hours ago and I can't get it to work with `dvorak`.

I did not have a `com.system76.CosmicComp` directory on my install, so I created it.
I have copied the `xkb_config` file into every `v1` sub-directory (since removed).
I've restarted `gdm`.
I've rebooted.

My `xkb_config` file looks like this:
```
(
    rules: "",
    model: "pc105",
    layout: "us",
    variant: "dvorak",
    options: Some("caps:none"),
)
```

**Comment by wiiznokes** [comment]
But there is an UI in cosmic settings for this anyway

**Comment by mmstick** [comment]
Implemented in cosmic-settings

**Comment by sandboiii** [comment]
@mmstick bump submodules please

**Comment by BbIXOD** [comment]
I still cant take it to work. Is this really implemented?
![screenshot-2024-07-03-15-29-16](https://github.com/pop-os/cosmic-epoch/assets/108470719/0be7b0a9-7bd2-43fe-b235-814ce82afd25)

**Comment by LmbMaxim** [comment]
After updating to the version that adds "Input Devices" "Input Sources" settings
I can't change `xkb_config` directly, after logout it changes `options:` to default `terminate:ctrl_alt_bksp`.

With `'sudo chattr +i xkb_config'` I'am able to set `'grp:alt_shift_toggle, ctrl:nocaps'`.

**Comment by montvid** [comment]
@mmstick i don't know what you implemented but it does not work - I can't find a GUI way to change keyboard layout between languages via keyboard keys. Now will be trying via config file. AND my numeric part of keyboard odes not work...    options: Some("grp:alt_shift_toggle")
