### ISSUE TITLE
Please modify Fedora Cosmic Atomic SIG Readme to include prep steps for backtracking if desktop doesn't work 

### ISSUE THREAD

**Issue by omac777** [pop-os/cosmic-epoch#207]
I just read the announcement about a call for a special interest group for Fedora Silverblue Cosmic.
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/F5G4DOPVSOACS3BRC7ZPBF2TO6JIODMU/
https://old.reddit.com/r/linux/comments/1at9u14/proposing_a_fedora_sig_for_the_upcoming_cosmic/

Please modify the readme for the fedora cosmic atomic:
https://github.com/ryanabx/fedora-cosmic-atomic
It mentions one command for the rebase.  Please ensure users that do that read the "how to rebase" so that they can backtrack if something goes wrong.
https://fedoramagazine.org/how-to-rebase-to-fedora-linux-39-on-silverblue/

### Disable selinux first
https://tecadmin.net/how-to-disable-selinux-on-fedora/

```
sudo nano /etc/selinux/config
SELINUX=disabled
```

### update the system first

```
sudo rpm-ostree update
```

### Pin the current deployment in GRUB so you can backtrack if things go wrong

```
sudo ostree admin pin 0
```

### Now finally rebase the system to welcome our new cosmic desktop overlords

```
sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ryanabx/fedora-cosmic-atomic-silverblue:latest-amd64
```

if something goes wrong you can rollback:

```
rpm-ostree rollback
```

**Comment by mmstick** [comment]
You should send this to the Fedora members involved with this. We are not members of Fedora so we aren't involved with this.

**Comment by omac777** [comment]
The above SIG stated issues are to be reported to this github project.
