### ISSUE TITLE
Add just install method

### ISSUE THREAD

**Issue by RyzenDew** [pop-os/cosmic-epoch#208]
I normally pull this down then update all submodules to master and then compile just sysext then copy and paste usr folder to /root i know that’s messy so can you guys add just install as well please thanks! 

Yes i tried just install and it doesn’t work lol

**Comment by yochananmarqos** [comment]
@Drakulix That didn't work as `rootdir` and `prefix` are not defined. One should be able to define both like in all the other justfiles:

```
just prefix="<prefix>" rootdir="$<dir>" install
```
