### ISSUE TITLE
Panic when starting after `just install`, works with `just sysext`

### ISSUE THREAD

**Issue by ywnkmn** [pop-os/cosmic-epoch#211]
epoch works when` just sysext`, yet panics with `sudo just install` while starting with GDM, SDDM or from a TTY

`2024-02-23T05:53:21.753269Z  INFO cosmic-notifications: cosmic_session::notifications: 2024-02-23T05:53:21.752116Z  INFO i18n_embed::requester: Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]   
2024-02-23T05:53:21.753375Z  INFO cosmic_session::comp: sending 1 fds
2024-02-23T05:53:21.753409Z  INFO launch_pad: starting process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:2 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=50 PORTAL_WAYLAND_SOCKET=44 /usr/libexec/xdg-desktop-portal-cosmic '

2024-02-23T05:53:21.761520Z ERROR panic: thread 'main' panicked at 'failed to start /usr/libexec/xdg-desktop-portal-cosmic': src/main.rs:405

   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}`

However, `term`, `settings` and `files` just work under the GNOME session.

What am I missing here?

**Comment by RyzenDew** [comment]
same issue under sddm and gdm on arch and fedora. where it was fine yesterday!

**Comment by ywnkmn** [comment]
> > 2024-02-23T05:53:21.761520Z ERROR panic: thread 'main' panicked at 'failed to start /usr/libexec/xdg-desktop-portal-cosmic': src/main.rs:405
> 
> cosmic-session can't start `xdg-desktop-portal-cosmic` for some reason. You could check what permissions `/usr/libexec/xdg-desktop-portal-cosmic` has, if the file was copied correctly (shasum) etc.

We are both using it on Arch, did `sudo just install`

**Comment by RyzenDew** [comment]
> > > 2024-02-23T05:53:21.761520Z ERROR panic: thread 'main' panicked at 'failed to start /usr/libexec/xdg-desktop-portal-cosmic': src/main.rs:405
> > 
> > 
> > cosmic-session can't start `xdg-desktop-portal-cosmic` for some reason. You could check what permissions `/usr/libexec/xdg-desktop-portal-cosmic` has, if the file was copied correctly (shasum) etc.
> 
> We are both using it on Arch, did `sudo just install`

Arch and Fedora and Ubuntu is my testing ground FYI

**Comment by ywnkmn** [comment]
BTW, simply did: `sudo ln -s /usr/local/libexec/xdg-desktop-portal-cosmic /usr/libexec/xdg-desktop-portal-cosmic` to resolve it for now

**Comment by jokeyrhyme** [comment]
There doesn't seem to be a mention of using `sudo just install` in the README yet

So maybe this isn't yet intended to work, but nice for someone to test it (once it does work, perhaps the README can be updated)

**Comment by joshuamegnauth54** [comment]
Related issue: #87 

It may be helpful to take a look at the [AUR package](https://aur.archlinux.org/packages/cosmic-epoch-git), particularly the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cosmic-epoch-git) which handles the issue raised here.
