### ISSUE TITLE
Any way to compile all submodules concurrently?

### ISSUE THREAD

**Issue by road2react** [pop-os/cosmic-epoch#213]
Right now compiling takes a lot of unnecessary time, since shared dependencies have to be compiled repeatedly, and there is a bottleneck in compiling the final binary and linking for each submodule. Perhaps a cargo workspace would work? Then cargo can decide which order to compile everything with more information, so there should be less bottlenecks.

**Comment by mmstick** [comment]
You can install and configure sccache and mold for use with Rust/Cargo.

**Comment by Drakulix** [comment]
> Perhaps a cargo workspace would work?

Can't because we have workspaces inside the projects and nested cargo workspaces are not a thing. As @mmstick already pointed out, sccache and mold are your friends.

**Comment by RyzenDew** [comment]
To much ram gets used to compile everything now and I can’t afford anyone and compiling one by one is fine but set and forget is what i want … so maybe we can split things up or limit the amount of applets that compile? Say only 5 or something cause this makes testing impossible
