### ISSUE TITLE
dock: app icons too small, set good defaults and allow manual resizing

### ISSUE THREAD

**Issue by boredsquirrel** [pop-os/cosmic-epoch#219]
![traditional-panel](https://github.com/pop-os/cosmic-epoch/assets/113100745/7e9024ff-aa37-4aea-a4c3-8256ddc6349f)

- scale 125%
- bottom panel set to small, otherwise too big
- added nearly all panel widgets

**Comment by WatchMkr** [comment]
Application icons are now larger at small panel sizes and a traditional panel can be setup, moved to the bottom with the dock disabled. This is how I run my setup.
