### ISSUE TITLE
FR: panel, allow changing the spacing between widgets

### ISSUE THREAD

**Issue by boredsquirrel** [pop-os/cosmic-epoch#221]
Like in Dash to panel, it would be useful to be able to reduce the spacing between widget elements, especially in the system tray part.

alternatively, the padding could always use a fraction of their size as default, often removing the need of such a feature.

See this panel layout at the bottom right, where the icons are set to small.

![traditional-panel](https://github.com/pop-os/cosmic-epoch/assets/113100745/a5e816b5-22a6-4946-8066-edd2c65356db)

**Comment by WatchMkr** [comment]
Thanks for the suggestions. We've incorporated improvements that improve a traditional panel while keeping in line with COSMIC design and style.
