### ISSUE TITLE
FR: traditional panel layout

### ISSUE THREAD

**Issue by boredsquirrel** [pop-os/cosmic-epoch#222]
Hey, I am trying COSMIC on ryanabx's atomic image, based on Fedora 40.

I recreated a traditional panel layout, and want to collect issues preventing that from being feature complete.

![traditional-panel](https://github.com/pop-os/cosmic-epoch/assets/113100745/4fdca87e-4bf6-45d4-b059-a36a5983cc81)

- [ ] #3 (and add a single setting to create this preset)
- [x] #219
- [x] #220
- [x] #221

**Comment by Anikmoujegy** [comment]
like this?

![Uploading screenshot-2024-05-24-07-43-47.png…]()

**Comment by Anikmoujegy** [comment]
just removed all plugins from panel and put everything in dock changed transperancy of the panel to zero and move it to down under the dock that it.
