### ISSUE TITLE
Feature Request/Query - desktop files and icons on main screen display? 

### ISSUE THREAD

**Issue by pheonixfirewingz** [pop-os/cosmic-epoch#225]
I wanted to know if there is going to be an option to show the files and app launch icons in the desktop DIR as it is one of the main locations I access my OS. e.g.
![Screenshot from 2024-03-04 02-26-54](https://github.com/pop-os/cosmic-epoch/assets/26938574/afa2f895-4224-4626-a458-f9866e36f6dc)

files are random examples for the image

I like to use my main screen.

I'm not one for an empty-looking desktop personaly

**Comment by wiiznokes** [comment]
This will be supported

**Comment by pheonixfirewingz** [comment]
What about alpha 2? Is it possible for that sub window?

**Comment by xe1st** [comment]
I'm glad they're addressing that. It's frustrating that such a fundamental feature like drag-and-drop on the desktop is missing in Gnome. Hopefully, Cosmic won't repeat that mistake.  Just letting users drag and drop files and folders, or create new ones with a right-click, would be a huge improvement. Cosmic is shaping up to be really exciting.

**Comment by onlyreportingissues** [comment]
This and alt + tabbing are crucial features in my opinion to attract also traditional desktop users.

**Comment by pheonixfirewingz** [comment]
Cosmic is basically gnome done the correct way

**Comment by DavidHaltinner** [comment]
I see this was implemented, but no way to disable them for those who dont want them. It also shows entire home directory, not Desktop folder for me.

**Comment by WatchMkr** [comment]
@DavidHaltinner check the XDG_DESKTOP_DIR in ~/.config/user-dirs.dirs
