### ISSUE TITLE
Mangohud showing on Terminal and Appstore

### ISSUE THREAD

**Issue by Azure-Orit** [pop-os/cosmic-epoch#230]
Mangohud is showing its overlay on terminal and appstore even when global mode is disabled, it can be workaround with "env MANGOHUD=0" on the .desktop file but it needs to be reconfigured every time those softwares are updated.

**Comment by mmstick** [comment]
What does  Mangohud use to determine if an application needs an overlay?

**Comment by Azure-Orit** [comment]
I think it looks for an OpenGL or Vulkan window but I'm not sure

**Comment by Azure-Orit** [comment]
update on this, the solution I found was to blacklist on `$XDG_CONFIG_HOME/MangoHud/MangoHud.conf` every cosmic app with `blacklist=cosmic-term, cosmic-store, cosmic-files, cosmic-edit`
