### ISSUE TITLE
[bug] graphical miss alignment in file picker

### ISSUE THREAD

**Issue by pheonixfirewingz** [pop-os/cosmic-epoch#235]
![screenshot-2024-03-20-02-52-12](https://github.com/pop-os/cosmic-epoch/assets/26938574/2be6cf30-7cac-48b7-856d-e24aca7d6021)

as you can see in the image above when using the file picker there is a graphical issue with the padding on the left side of the file descending menu. 

sorry I can't provide any more information to fix the issue.

**Comment by mmstick** [comment]
COSMIC will have a different file picker soon
