### ISSUE TITLE
[bug] header bar can make impossible to close app graphical

### ISSUE THREAD

**Issue by pheonixfirewingz** [pop-os/cosmic-epoch#236]
![screenshot-2024-03-20-02-54-27](https://github.com/pop-os/cosmic-epoch/assets/26938574/5f42231e-86e3-4a66-8ecc-2e98a7bd6ebf)

due to the way the window is allowed to clip with the top bar it can cause the close, shrink and maximise bar to be covered and is unable to be accessed. This makes the window "soft locked" in gaming terms and I have to use the terminal or system monitor to kill the program when I want to close it.

this is all the information I can give at this time.

**Comment by cybin** [comment]
You can move the window with Super+Shift+Arrow. But yes, it's annoying anyway. :smile:

**Comment by WatchMkr** [comment]
We're tracking this issue here: https://github.com/pop-os/cosmic-comp/issues/257
