### ISSUE TITLE
New COSMIC apps take several seconds to open

### ISSUE THREAD

**Issue by nathansgithub** [pop-os/cosmic-epoch#238]
I haven't seen anyone bring this up, so close this if this is a known issue. But the new COSMIC files, edit, store, and terminal programs all take around 8 seconds to load when I open a new window in a COSMIC session on Pop!_OS. The new settings and screenshot programs, and all other programs start up as quickly as expected.

I installed the cosmic-session using apt, and my system is up-to-date. I am running the latest Pop!_OS on a Lemp10 machine.

**Comment by Drakulix** [comment]
Sounds similar to https://github.com/pop-os/cosmic-comp/issues/348.
Do you have the nvidia driver installed by chance?

**Comment by nathansgithub** [comment]
It does sound similar. But I don't think I have any NVIDIA drivers installed, and I don't have any reason to. What's the best way to check to rule that out?

**Comment by Drakulix** [comment]
You might just have it, if you used the nvidia variant of the Pop!_OS ISO when installing.

Theoretically checking the package should be enough, but lets be super paranoid. The component causing the slow down is nvidia's vulkan driver. So if you run `ls /usr/share/vulkan/icd.d` in a terminal, does the resulting list contain `nvidia_icd.json`?

**Comment by nathansgithub** [comment]
I do see that, and the NVIDIA drivers now. I guess I should run `sudo apt purge ~nnvidia` and report back?

**Comment by Drakulix** [comment]
yes, that should work. :)

**Comment by nathansgithub** [comment]
That fixed it, and it's fast now! Thanks for your help.

**Comment by Himi-Deb** [comment]
Facing similar issue. Application launch times are disproportionately high - native cosmic (files, screenshot tool) as well as other. I do not have any nvidia_icd. I had these following ones - 
radeon_icd.json, gfxstream_vk_icd.json, asahi_icd.json

Which I moved out to some temporary folder and it did improve the laggyness which sometimes is present while switching (for example tabs). But application launch times are still high.

OS Version: 24.04LTS
Processor: Intel Core Ultra 5 225H
Graphics: Intel Arrow Lake-P

**Comment by mmstick** [comment]
@Himi-Deb Launch them in a terminal with logs enabled. Such as  `env RUST_LOG=debug cosmic-settings`. Find the logs that are printed around the time that it hangs. Usually this indicates that Vulkan failed to initialize on a GPU and it had to fallback to OpenGL or software rendering.

**Comment by Himi-Deb** [comment]
Found the fix, turns out it was the cosmic media player which had multiple instances open. 
Helpful reference which helped:
https://medium.com/@vijeta004/how-a-simple-media-player-ddosd-my-cpu-pop-os-900dfe8bb8f1?postPublishedType=repub
