### ISSUE TITLE
impossible to share the screen with flatpak slack

### ISSUE THREAD

**Issue by jbdamiano** [pop-os/cosmic-epoch#242]
On cosmic-epoch, the screen sharing is not working. If I rollback on pop session on wayland I'm able to share it.

This selecting window is not displayed like this example on session on pop on wayland

I'm on pop os 22.04 and cosmic installed with apt package

![image](https://github.com/pop-os/cosmic-epoch/assets/3286076/1ee77440-4801-4251-ac46-107a7aeecdd3)

**Comment by luccahuguet** [comment]
i'll add that I can't share my screen in cosmic, neither in Meet, in the browser, nor in the Discord desktop app

in meet, the only thing that works is tab sharing, but not window and not the whole screen

**Comment by jokeyrhyme** [comment]
I just tested the Jitsi web app in Firefox in flatpak, and was able to share the screen, against https://github.com/pop-os/cosmic-epoch/pull/245

I haven't tried electron or more native apps yet

**Comment by jokeyrhyme** [comment]
COSMIC has bindings for pipewire, and I suspect that on some systems these do not line up with the version of pipewire that is installed

Depending on how often you update your system, I find it sort of unpredictable about whether this works or not

**Comment by boredsquirrel** [comment]
GPU Screen Recorder Flatpak, and BlueRecorder Flatpak did not request pipewire access via a portal, at least on `cosmic-silverblue:40` image.

**Comment by jbdamiano** [comment]
Could be related to #26

**Comment by WatchMkr** [comment]
This is indeed being track on the other issue as mentioned above: https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/48

We will have the portal UI completed for the first alpha.
