### ISSUE TITLE
Keyboard issues

### ISSUE THREAD

**Issue by Luigi2898** [pop-os/cosmic-epoch#247]
Hi! My laptop has an Italian keyboard, in pop_os with gnome I'm able to set the Italian keyboard in settings, while, recently I've installed COSMIC but I'm not able to properly set the keyboard language.
Any idea? Can I do anything to fix this?

**Comment by quadbyte** [comment]
Hi, please search the issue queue, before opening new ones.
Duplicate of #201

**Comment by leviport** [comment]
A lot of work is currently happening on the keyboard section of Cosmic Settings, so we should be seeing that pretty soon
