### ISSUE TITLE
Opencpn window shrinks vertically in 1 second steps.

### ISSUE THREAD

**Issue by ArjenR** [pop-os/cosmic-epoch#255]
OpenCPN either installed from (default) apt repo or from flatpak.
When the application is started the main window starts to shrink from the bottom up in steps. Each step is about a second.

I have tried to disable all window elements I could (various status bars) and disable hardware rendering. This has no influence. 

The 1 second step may be related to elements in the chart and status bars being updated every second. 

EDIT: This is both in tiling and floating window mode.

```
OS: Pop!_OS 22.04 LTS x86_64
Host: 82MS Yoga Slim 7 Pro 14ACH5
Kernel: 6.8.0-76060800daily20240311-generic
Uptime: 7 hours, 45 mins
Packages: 2191 (dpkg), 74 (flatpak)
Shell: bash 5.1.16
Resolution: 3440x1440
DE: COSMIC
Theme: Pop-dark [GTK3]
Icons: Adwaita [GTK3]
Terminal: cosmic-term
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 4.463GHz
GPU: AMD ATI 03:00.0 Cezanne
Memory: 2710MiB / 13836MiB
```
```
cosmic-app-library/jammy,now 0.1.0~1711651474~22.04~3349462 amd64 [geïnstalleerd,automatisch]
cosmic-applets/jammy,now 0.1.0~1711670064~22.04~71cb9e6 amd64 [geïnstalleerd,automatisch]
cosmic-bg/jammy,now 0.1.0~1710263065~22.04~742a344 amd64 [geïnstalleerd,automatisch]
cosmic-comp/jammy,now 0.1~1711646504~22.04~3da08ed amd64 [geïnstalleerd,automatisch]
cosmic-edit/jammy,now 0.1.0~1711669018~22.04~cf433f7 amd64 [geïnstalleerd,automatisch]
cosmic-files/jammy,now 0.1.0~1711634659~22.04~2d0c2e3 amd64 [geïnstalleerd,automatisch]
cosmic-greeter-daemon/jammy,now 0.1.0~1711161779~22.04~d133e60 amd64 [geïnstalleerd,automatisch]
cosmic-greeter/jammy,now 0.1.0~1711161779~22.04~d133e60 amd64 [geïnstalleerd,automatisch]
cosmic-icons/jammy,now 0.1.0~1708631590~22.04~ee87327 amd64 [geïnstalleerd,automatisch]
cosmic-launcher/jammy,now 0.1.0~1711691471~22.04~7bc6e65 amd64 [geïnstalleerd,automatisch]
cosmic-notifications/jammy,now 0.1.0~1710884844~22.04~4ea0564 amd64 [geïnstalleerd,automatisch]
cosmic-osd/jammy,now 0.1.0~1711592480~22.04~929a741 amd64 [geïnstalleerd,automatisch]
cosmic-panel/jammy,now 0.1.0~1711690917~22.04~75e74bd amd64 [geïnstalleerd,automatisch]
cosmic-randr/jammy,now 0.1.0~1705615670~22.04~88c570c amd64 [geïnstalleerd,automatisch]
cosmic-screenshot/jammy,now 0.1.0~1708922594~22.04~f853446 amd64 [geïnstalleerd,automatisch]
cosmic-session/jammy,now 0.1.0~1711555474~22.04~d5d9c58 amd64 [geïnstalleerd]
cosmic-settings-daemon/jammy,now 0.1.0~1711460452~22.04~a949447 amd64 [geïnstalleerd,automatisch]
cosmic-settings/jammy,now 0.1.0~1711719828~22.04~8ef9450 amd64 [geïnstalleerd,automatisch]
cosmic-store/jammy,now 0.1.0~1711161754~22.04~84466d1 amd64 [geïnstalleerd]
cosmic-term/jammy,now 0.1.0~1711149944~22.04~ab832cc amd64 [geïnstalleerd,automatisch]
cosmic-workspaces/jammy,now 0.1.0~1711393415~22.04~7c8fddc amd64 [geïnstalleerd]
gnome-shell-extension-cosmic-dock/jammy,jammy,now 72~ubuntu2pop0~1664903880~22.04~6700449 all [geïnstalleerd,automatisch]
gnome-shell-extension-cosmic-workspaces/jammy,jammy,now 0.1.0~1654603041~22.04~c5f2c5d all [geïnstalleerd,automatisch]
pop-cosmic/jammy,jammy,now 0.1.0~1706558821~22.04~608a095 all [geïnstalleerd,automatisch]
xdg-desktop-portal-cosmic/jammy,now 0.1.0pop1~1711393396~22.04~db02412 amd64 [geïnstalleerd,automatisch
```

**Comment by curiousercreative** [comment]
I haven't even got it to load fully on my laptop running COSMIC.

**Comment by ArjenR** [comment]
> I haven't even got it to load fully on my laptop running COSMIC.

Flatpak version works for me.

**Comment by ArjenR** [comment]
The flatpak version works now. The deb packages do not. Will try to get logs.

**Comment by ArjenR** [comment]
Flatpak works. Packaged version may have another issue. Closing this as resolved.

**Comment by curiousercreative** [comment]
@ArjenR yes, I've also noticed that I'm able to get OpenCPN to launch fully now (on Intel integrated graphics at least). I also ended up launching an X11 session to use OpenCPN before finding it launchable in COSMIC, so maybe that's relevant? While I can get OpenCPN (flatpak) to launch in COSMIC now, I'm still unable to use it. All of my mouse interactions are registered elsewhere from where my cursor is visible.

**Comment by curiousercreative** [comment]
Aha, it seems you must have your display scaled to reproduce my issue.
1. Open Display settings and select 125% for scale and confirm
2. Launch OpenCPN
3. Right click somewhere in OpenCPN
    ER: a context menu should appear adjacent to your mouse/trackpad cursor
    AR: the context menu appears elsewhere, perhaps 300px to the right
4. Close OpenCPN
5. Return to display settings and select 100% for scale and confirm
6. Launch OpenCPN
7. Right click somewhere in OpenCPN
    ER/AR: a context menu appears adjacent to your mouse/trackpad cursor
