### ISSUE TITLE
Requested functionality for iced apps.

### ISSUE THREAD

**Issue by Anikmoujegy** [pop-os/cosmic-epoch#258]
Move back button to header bar when back button is not visible on the page anymore.
Because it is annoying to scroll up then go back in large pages.
Else you can add a floating button on the page to go to top at once like many websites are offering this functionality.

**Comment by wiiznokes** [comment]
I noticed that on cosmic- settings. I think the back button should be in the header bar

**Comment by mmstick** [comment]
This is app-specific

**Comment by mmstick** [comment]
Any requests to change visual design requires approval from @pop-os/ux

**Comment by maria-komarova** [comment]
Design prototypes include making the part with back button and page header sticky on scroll but it hasn't been implemented yet and I'm not sure on the timeline for this. 
We've considered moving the back button to a header but decided against it for various reasons including window resizing to a narrow width.

**Comment by mmstick** [comment]
Then I'll make issues for decoupling the scrollable in libcosmic's application trait, and then making page headers static.

**Comment by maria-komarova** [comment]
Thanks @mmstick

**Comment by git-f0x** [comment]
Sorry for commenting here, but since the page headers will be static, will they also eventually have blur for content scrolling beneath them (like the header bars in the early COSMIC Figma designs)?
