### ISSUE TITLE
Dock and Panel invisible

### ISSUE THREAD

**Issue by litLizard69** [pop-os/cosmic-epoch#259]
Hi,

I've been trying to run Cosmic-Desktop on Pop!_OS in a VMware virtual machine, but I'm running into a problem where both the dock and panel are not visible. You can click the buttons where the dock and panel should be but they themselves are not visible.

![Screenshot 2024-04-13 163554](https://github.com/pop-os/cosmic-epoch/assets/94228143/b65d4e8e-2ca7-4985-a2c6-739e6598b659)

Although keep in mind that I am running this in a virtual machine, so this could just be a virtual-machine-only issue.

**Comment by mmstick** [comment]
You don't have a sufficient level of GPU support

**Comment by litLizard69** [comment]
> You don't have a sufficient level of GPU support. Use KVM/QEMU instead.

Thank you.
Therefore I'm closing this issue.

**Comment by litLizard69** [comment]
After Cosmic has been updated over the months this issue is now solved and even in virtual machines the dock and panel is visible.
