### ISSUE TITLE
Building on Gentoo stable: couldn't find  libclang.so

### ISSUE THREAD

**Issue by joostruis** [pop-os/cosmic-epoch#260]
As in the title the build-system fails to find libclang although this is present in the build chroot.

I tried passing LIBCLANG_PATH="/usr/lib/llvm/17/lib" LLVM_CONFIG_PATH="/usr/lib/llvm/17/bin/llvm-config"

Please see attached log.

[layerscosmicepochgit0013_spec-build.txt](https://github.com/pop-os/cosmic-epoch/files/14971590/layerscosmicepochgit0013_spec-build.txt)

**Comment by joostruis** [comment]
It seems that after properly setting ENV in my build chroot I got passed this. Perhaps nice if packagers didn't have to fiddle with that!

**Comment by mmstick** [comment]
Packagers can submit PRs to the crate that handles clang path detection, and then it'll be applied to all Rust projects using the clang crate.

**Comment by joostruis** [comment]
So this crate is your upstream? Pardon my ignorance. I am new to this build infra.
