### ISSUE TITLE
Setting prefix doesn't seem to work?

### ISSUE THREAD

**Issue by joostruis** [pop-os/cosmic-epoch#261]
Hi.

I am trying to build this against Gentoo stable tree and I got everything compiled. However it seems that everything gets installed in /usr/local. So I tried to change the prefix, and noticed arch used a patch that changes the justfile. After trying to apply that I noticed everything still got installed in /usr/local causing things not to work. 

Any advice on this?

Thanks!

**Comment by mmstick** [comment]
Variables are sensitive to command line argument positioning. The prefix is set before the recipe name.

**Comment by joostruis** [comment]
Thanks! Giving that a shot. Need to recompile everything due to our workflow but that is no issue, we have the infra for it.
I'll report back!

**Comment by joostruis** [comment]
Trying that actually gets me back to the initial problem I got it seems:

 INFO error: Variable `prefix` overridden on the command line but not present in justfile

**Comment by mmstick** [comment]
I see that you're trying to apply that argument to the justfile in this repository. The justfile here doesn't have a root level variable for setting the prefix. See the [install recipe here](https://github.com/pop-os/cosmic-epoch/blob/master/justfile#L28).  You should be running `sudo just install prefix=/usr` here.

**Comment by joostruis** [comment]
After trying the [patch](https://aur.archlinux.org/cgit/aur.git/tree/justfile.diff?h=cosmic-epoch-git) from Arch again, and this time apply it for the 100%, it now works as expected. (Thank you Arch people!)

Trying to set or change the prefix directly from the command-line never worked for me no matter what I tried.

Thanks for the help though! Very much appreciated!
