### ISSUE TITLE
super + right click to resize windows

### ISSUE THREAD

**Issue by svin24** [pop-os/cosmic-epoch#270]
Primarily useful for:
- Floating mode windows.
- Trackball users
- Accessibility users.

For reference see: KDE. most window managers(river as an example)

**Comment by wiiznokes** [comment]
Duplicate of https://github.com/pop-os/cosmic-comp/issues/429

**Comment by bartv42** [comment]
This was also included in #363

**Comment by svin24** [comment]
Since this is a duplicate I am closing it
