### ISSUE TITLE
weekly cargo updates?

### ISSUE THREAD

**Issue by soloturn** [pop-os/cosmic-epoch#272]
rust itself has a github workflow to weekly update dependencies, called "weekly cargo update", example:
https://github.com/rust-lang/rust/pull/124213

implemented like this:
https://github.com/rust-lang/rust/blob/master/.github/workflows/dependencies.yml

would this be acceptable for cosmic as well?

**Comment by Drakulix** [comment]
No, this would force an update for our various git-dependencies. So these kinds of updates have to be managed manually.
