### ISSUE TITLE
Considering add binary package for AUR

### ISSUE THREAD

**Issue by Dangerise** [pop-os/cosmic-epoch#281]
half hour past since 'yay -S cosmic-epoch-git' , it still compiling on my i7-10750h and 16gb ram laptop, with the help of mold and sccache

**Comment by Vixea** [comment]
The aur packages are not controlled by system76 you should make your request on the aur

**Comment by XandrCopyrighted** [comment]
> half hour past since

mine took 2 hours lmao

was gonna add binary packages but decided not to

**Comment by Dangerise** [comment]
Finally, it took me more than an hour

**Comment by Drakulix** [comment]
We are not responsible for the aur-package and we will neither host our own arch-repo nor do the packaging for upstream. If you want binary packages, consider submitting the packages for inclusion in the official arch repos.
