### ISSUE TITLE
How to modify key bindings

### ISSUE THREAD

**Issue by mkeco** [pop-os/cosmic-epoch#288]
I want to modify the key bindings but I can't find the configuration file.

**Comment by wiiznokes** [comment]
Long run, probably Global shortcut portal: https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/4
Short run: modify the `/etc/cosmic-comp/config.ron` file. But last time i try to modify shortcut this way, it didn't worked.

**Comment by theshatterstone** [comment]
@wiiznokes It worked for me! Here's my config.ron, for reference: https://gitlab.com/theshatterstone/dotfiles/-/blob/e96536882a208bbc1e335865740395743d4289c1/Cosmic/etc/cosmic-comp/config.ron (I also have some basic themes, if you go up a few directories)

**Comment by MrGamerDoesGames** [comment]
I think it'd be cool if this was implemented on a per-user basis, or with integration in the settings app.

**Comment by lukejcollins** [comment]
Agreed @MrGamerDoesGames - that would be excellent!

**Comment by mmstick** [comment]
The config file is temporary until settings are properly implemented with cosmic-config and cosmic-settings-daemon.
See https://github.com/pop-os/cosmic-settings/issues/32
