### ISSUE TITLE
[Feature Request] Grouping of applets in the panel & dock

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-epoch#289]
It would make it look less crowded, if applets could be grouped on the panel & dock.

What I image is something like this > 
![1-app-groups-android](https://github.com/pop-os/cosmic-epoch/assets/103491514/ffa971fd-6023-48af-ab33-cc2a8f982663)

**Comment by wiiznokes** [comment]
related to https://github.com/pop-os/cosmic-epoch/issues/289

**Comment by onlyreportingissues** [comment]
Duplicate https://github.com/pop-os/cosmic-applets/issues/336

**Comment by onlyreportingissues** [comment]
Duplicate https://github.com/pop-os/cosmic-applets/issues/336
