### ISSUE TITLE
Cosmic Tasks naming convention & installing cosmic through sudo apt install cosmic-*

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-epoch#295]
It's nice that the community maintained app(https://github.com/pop-os/cosmic-tasks/) is packaged in Pop repository But I've some concerns.

Cosmic Epoch repo & in users in various reddit posts suggests installing cosmic in Pop OS using `sudo apt install cosmic-*`
![image](https://github.com/pop-os/cosmic-tasks/assets/58325574/9bcefeff-2cae-47ff-be04-c8c95af40a80)

The problem that arises with that & this app having cosmic name is that the users would install this application unknowingly even when it is not officially developed by System76.
This also causes friction in the ux & affects user expectations of Cosmic as this application does not match the design language of the official applications aside from sidebar & menus.

Maybe the better option would be to change installation command from `sudo apt install cosmic-*` to `sudo apt install cosmic-session` & recommending cosmic-greeter when it is more stable.

**Comment by WatchMkr** [comment]
README has been updated to suggest `cosmic-session`
