### ISSUE TITLE
Gaps around tiled windows should be exclusive to the active window hint size

### ISSUE THREAD

**Issue by chdalski** [pop-os/cosmic-epoch#296]
Currently if the `Gaps around tiled windows` (Window Management settings) is lower than the `Active window hint size` the Active window hint size is not displayed correctly because the Gaps around windows include the active window hint size.

So for example if the gaps around tiled windows is set to `0` and the active window hint size is set to `2` the active window hint size displays to be `1` instead of `2`. This behavior can be easily observed when in tiling mode.

Instead of the current behavior the active window hint size should be exclusive, meaning that the active window hint size determines the minimum gaps around tiled windows, and the actual gaps around tiled windows is the `active window hint size` plus the `gaps around tiled windows` setting.

**Comment by wiiznokes** [comment]
You could let this open ig, as the settings app can currently cause this
