### ISSUE TITLE
[Feature Request] Add right-click context-menu to panel & dock

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-epoch#297]
Like this e.g.
![Bildschirmfoto vom 2024-05-06 14-36-12](https://github.com/pop-os/cosmic-epoch/assets/103491514/688625cf-45cc-410c-9965-12db3ede8c28)

**Comment by git-f0x** [comment]
This is planned. pop-os/cosmic-panel#53

**Comment by onlyreportingissues** [comment]
> This is planned. [pop-os/cosmic-panel#53](https://github.com/pop-os/cosmic-panel/issues/53)
