### ISSUE TITLE
[Feature Request] Single panel as an alternative to split dock/top bar

### ISSUE THREAD

**Issue by ssoto2** [pop-os/cosmic-epoch#3]
With Cosmic going away from gnome I see one of my most used extensions being taken away from me. Requesting a panel option instead of just dock?  

Right now I am using https://github.com/home-sweet-gnome/dash-to-panel and it has such a clean interface no need to waste space with a top ribbon bar and then a dock just combining it all into the panel 

A video of dash to panel in action
https://www.youtube.com/watch?v=XUaDjsv06sg

**Comment by Anikmoujegy** [comment]
![Uploading screenshot-2024-05-24-07-43-47.png…]()
like this ?
