### ISSUE TITLE
After logging in via GDM, the screen flashes and the cursor

### ISSUE THREAD

**Issue by issues-linux** [pop-os/cosmic-epoch#310]
I have a problem with the COSMIC environment starting after logging in, specifically the screen starts flickering from black to grey and the cursor also flickers. I got the output by using the command `/usr/bin/cosmic-session` in the tty3 environment. The output is [here](https://raw.githubusercontent.com/issues-linux/log-files/main/cosmic-log.txt).

I have enabled Wayland in the GDM3 settings (`/etc/gdm3/custom.conf`) and I installed it using `sudo apt install cosmic-*`.
The environment loads without any problems using only the `/usr/bin/cosmic-session` command in the running GNOME session, specifically, a window opens and COSMIC is loaded.

I tried it on Pop! OS 22.04 (in the virtual machine, specifically KVM).
What could be the problem?

**Comment by Drakulix** [comment]
> in the virtual machine, specifically KVM

This is most likely the problem, you need hardware acceleration for cosmic-comp to work currently.

Try adding `-vga qxl` to your qemu command line or search for options to enable hardware acceleration for your virtual gpu, if you are using some GUI.

**Comment by issues-linux** [comment]
I switched to the video QXL from Virtio in virt-manager and now it works correctly. Thank you for your help!
