### ISSUE TITLE
[question] How to work with cosmic-epoch components?

### ISSUE THREAD

**Issue by elevenhsoft** [pop-os/cosmic-epoch#315]
Hey,

I think it's not stupid question since I heard they are not exist ^^

I'm curious how to work with cosmic-epoch components. I wish to be able to make some little changes for workspace, comp, etc.

If I'm know how to do it with cosmic-term or edit because simple cargo run will do the job. But I'm not sure how to do it with core components. I'm used to work and every single change test via cargo run to see it on live "corpse" (?). 

How to properly work with cosmic-epoch components?

Also, I think there in README should be some info related to contributions. Thank you.

**Comment by mmstick** [comment]
You can `just && sudo just install`, then `killall {{applet-name}}` to have cosmic-session respawn the applets.

**Comment by mmstick** [comment]
If it's a panel applet, you can also kill the `cosmic-panel` to make it respawn all of its applets.

**Comment by elevenhsoft** [comment]
Oh yeah. Simple stuff. Thank you. Wonder if I'm able to add  something to workspaces. I have an idea but gonna test my skills haha
