### ISSUE TITLE
Scrolling stops working after use/Can't interact with applications

### ISSUE THREAD

**Issue by jklgrasso** [pop-os/cosmic-epoch#317]
After starting my laptop (2015 Macbook Pro 15") I can scroll once in any direction. After the initial scroll I cannot scroll or interact with any window. This happens (from what I've tested) in Microsoft Edge, VSCode. Firefox, and Cosmic Text Editor. I have seen some other people with this issue occasionally. If I turn on/off natural scrolling, it seems to "reset". I can scroll and interact with windows again temporarily. If I don't scroll at all, I can interact with applications just fine. This is on a relatively fresh install with Python modules, MS Edge, and VS Code installed.

**Comment by Kartonrealista** [comment]
https://github.com/pop-os/cosmic-comp/issues/552
