### ISSUE TITLE
Run dialog

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-epoch#32]
It's simple enough, so we might as well have a run dialog, triggered with alt+f2. `r` could send a command to `cosmic-session` to restart everything other than the Compositor.

**Comment by soloturn** [comment]
what is the difference between this run dialog and the one coming with super-/ ?

**Comment by ids1024** [comment]
Normally a run dialog takes a command, rather than searching through applications.

This isn't really an essential thing to offer, but seems to be a pretty common feature and is easy enough to provide.
