### ISSUE TITLE
What are the current ways and future ways of screen recording?

### ISSUE THREAD

**Issue by ludg1e** [pop-os/cosmic-epoch#328]
Hello!

I was curious to know in how many ways will the COSMIC DE support screen recording, currently I've thought of these, so I'd like to know which are supported or will be:
- Record entire screen
- Specifically record one screen in case of having multiple monitors

- Record selected region (ext-screencopy)
- Record window (ext-screencopy)
- Record one workspace (ext-workspace-unstable)

Thank you! Have a nice day.

Oh yes, sorry if this isn't the right place to ask.

**Comment by Drakulix** [comment]
Screen-recording capabilities will be available through xdg-desktop-portal.
While we will support ext-screencopy, once that lands upstream, access to this protocol will be restricted.

You are expected to be able to record either outputs or windows. Workspaces is technically possible, but not exposed atm. Capturing tools like OBS are expected to do cropping themselves for things like "recording a region".

**Comment by ludg1e** [comment]
Thank you!

Closing
