### ISSUE TITLE
[Suggestion] Alt + TAB should remember the last two windows it focused & switch between both when Alt + TAB is pressed only once again

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-epoch#348]
Currently, Alt + TAB always starts from the first window in the list and one has to keep pressing TAB while holding Alt to get to the window one wanna focus. Would be nice if the last two windows are focused instead, when Alt + TAB is pressed only once.

**Comment by STRAYKR** [comment]
I find it very frustrating losing the ability to switch easily between the most recently used windows. I lose track of where they are, so for example end up creating multiple windows to the same website because I lost track of the one I was working with. On Windows this is easy.

**Comment by git-f0x** [comment]
This is already planned, as described in this [issue](https://github.com/pop-os/cosmic-launcher/issues/135).

**Comment by curiousercreative** [comment]
I think this has been solved.
