### ISSUE TITLE
New swap windows mode design and animation

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-epoch#37]
This issue is a design proposal to introduce a different shortcut to swap windows, one that is separate than our current adjustment mode feature. 

## Designs

Super-X (tentative) will raise the active window, giving it a scaled-down effect. In place of the window will be a zone that indicates where the active window existed, and where the target swap window will appear after finalizing the swap.

![prototype-swapping-with-keyboard-before-confirmation](https://user-images.githubusercontent.com/106764128/181647729-e8e5479a-caa0-4c2c-bdab-c4d3af98c3d8.png)

Using the arrow keys will move the raised window over other visible windows. The raised active window will appear in the top left or right corner, whichever is closest to its origin position. Over the target window will appear a hint with the "Swap Window" caption indicating that you can hit the Enter key to finalize the swap.

![swap-windows](https://user-images.githubusercontent.com/106764128/181655749-58c88830-7003-4997-acd1-a604b4e52139.gif)

**Comment by maria-komarova** [comment]
After more discussions we'd like to treat Super+X as a kind of "mode" that is toggled on on the press of the combination and is toggled off on the release of the keys.

**Comment by Wulfheart** [comment]
Just to be sure: Is this also in Pop!_OS?

**Comment by maria-komarova** [comment]
This is only in COSMIC DE

**Comment by janvanveldhuizen** [comment]
Will this be part of 22.10 ?

**Comment by janvanveldhuizen** [comment]
Oh... there will be no 22.10 apparently.... https://huntingbears.nl/2022/09/30/pop_os-development-and-no-22-10-release/
