### ISSUE TITLE
[Bug]Extended titlebar when draging from fullscreen

### ISSUE THREAD

**Issue by engineerNg** [pop-os/cosmic-epoch#371]
The latest version of COSMIC DE.
When I want to drag the titlebar of a window to exit fullscreen, that happened.
![screenshot-2024-06-01-22-22-36](https://github.com/pop-os/cosmic-epoch/assets/54659261/727467cd-d82a-42c7-9ddd-275a9a51b723)
The grey block is just my edition, nothing to do with the bug.

It doesn't last long and return to normal size once I release my mouse button, which means it only happens when holding.

**Comment by WatchMkr** [comment]
Thanks for reporting. We're tracking this issue here: https://github.com/pop-os/cosmic-comp/issues/470
