### ISSUE TITLE
failed to install cosmic on archlinux

### ISSUE THREAD

**Issue by calvin0327** [pop-os/cosmic-epoch#373]
Using command `paru -S cosmic-epoch-git` to install cosmic,  an error occurred in the final step of the compilation.

<img width="951" alt="image" src="https://github.com/pop-os/cosmic-epoch/assets/45745657/ca060fae-ac32-40ec-85a3-3c626b25f52b">

Please help me figure out how to resolve this issue？thanks

**Comment by woodsb02** [comment]
This should really be reported to the relevant AUR package using the comments at the bottom of this page:
https://aur.archlinux.org/packages/cosmic-epoch-git
