### ISSUE TITLE
Fullscreen applications don't work

### ISSUE THREAD

**Issue by loddi-o** [pop-os/cosmic-epoch#377]
Steam big picture, games, lutris games.... nothing works. I am using pop os on desktop with ryzen 5600x and 3070ti.

while launching fullscreen stuff, rather i have a black screen that i am not able to close, or, with lutris games, i got a static image of the game. 

Also, when loggin in cosmic, i have this screen, forcing me to reboot: 

![errorcosmic](https://github.com/pop-os/cosmic-epoch/assets/160194780/8548fb07-1887-423c-b9de-bede1835a2f0)

**Comment by onlyreportingissues** [comment]
Fullscreen & borderless don't work yet, you can use bordered window instead.

**Comment by BurntKrispe** [comment]
Second this. 
It seems to bug out the display output. Using steam link I'm able to view the system as normal however.
If there's an existing issue tracker I'd appreciate it being linked.

**Comment by Drakulix** [comment]
Should be addressed by https://github.com/pop-os/cosmic-comp/pull/603.
