### ISSUE TITLE
Introduce "Select Outward" and "Select Inward" Keyboard Shortcuts to Tiling

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-epoch#38]
This issue is a design proposal to introduce the ability to "scale up" the focus from a window to a group or stack. Pending testing, we will use Super + Page Up and Super + Page Down to move focus "outward" and "inward," respectively. Outward will select the outer group, and inward will select an item within a group, when possible. Super + I and Super + U will also be purposed for outward and inward selection, to match the vim equivalents to Page Up and Down. This will allow us to select and move an entire stack with the keyboard only, which is not currently possible in Pop!_OS.

## Designs

When using Select Outward from a single window node, the focus should shift to the parent container. Items in the group will take on a 25% overlay of the active hint color, to aid in recognition. Continuing to hit the Select Outward shortcut will select parent groups until the focus has enveloped all the windows on the screen.

When a group is selected, the window movement shortcut will move that group as if it were a single window, [using our new tiling system and shortcut](https://github.com/pop-os/cosmic-epoch/issues/36).

![stack-moving](https://user-images.githubusercontent.com/106764128/181655635-bf0e51ce-e17c-43e9-9d04-d5c7cae8d87a.gif)

Selecting Inward should ideally return focus to the child element that was last selected; if you used Select Outward from a child element to select the containing group, Selecting Inward should then return focus to that same child.

Users can use the stack shortcut (currently Super + S in Pop!_OS) to turn a selected group of windows into a stack, and vice versa. Our orientation shortcut, while we expect it to be mostly overtaken by the new window movement shortcut, could still be used to change the orientation of multiple nodes at once to rotate a layout.

![stack-window-group](https://user-images.githubusercontent.com/106764128/181655665-694d664a-29aa-46eb-9c65-262b1378cd7d.gif)

![group-orientation](https://user-images.githubusercontent.com/106764128/181655667-f316c760-a129-4b5c-8c9a-6510b2d76511.gif)

**Comment by WillyWonksters** [comment]
I love the ability to turn a selected group into a stack!

I would also like to propose that a quick double tap of "Super + S" could group all windows from a display/workspace into a stack. This is similar to how vim uses repeated key shortcuts, like dd, yy, and cc.

**Comment by GrubBox** [comment]
You should have predefined tiling windows like in i3 and dwm. master stack or 3 column et c

**Comment by etrigan63** [comment]
> You should have predefined tiling windows like in i3 and dwm. master stack or 3 column et c

FYI, i3/sway is a manual tiler. bspwm, dwm, awesomewm, qtile, xmonad, hyprland are auto tilers. There is an app called `autotiling` that simulates that function in i3 and sway.
