### ISSUE TITLE
[Suggestion] Option to combine app launcher, app overview & places

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-epoch#380]
Here is an ugly picture of what I mean (don't mind the way it looks):

![uwuwuwe](https://github.com/pop-os/cosmic-epoch/assets/103491514/06dd18ee-1e8a-4dca-bad5-986659c53b91)

It would be nice, since more could be accessed quickly by doing less.

Left side shows places, mid apps, bottom search & right side app groups.

**Comment by mmstick** [comment]
We will not do this, but you're free to make your own applet.
