### ISSUE TITLE
Force an application in xwayland mode (equivalent of gtk GDK_BACKEND var maybe)

### ISSUE THREAD

**Issue by squalou** [pop-os/cosmic-epoch#413]
Hi,

I'm not sure this is the right place to ask and I apologize if it's not, I did not find the information, and I'm not sure at all which submodule would be best suited.

I'm used to gnome on wayland, but for some applications  (lets say, Tilix in quake mode for instance), it is required to run them in 'X', so using XWayland.

To do so, simply declare GDK_BACKEND=x11 before running the app. 

Is there a way to do such a thing within Cosmic ?
 
 thank you !

**Comment by Drakulix** [comment]
You should be able to do this for applications build upon winit with `WINIT_UNIX_BACKEND=x11`. Some however are build directly on sctk (most notably applets) and won't be compatible with anything but wayland.

**Comment by squalou** [comment]
thx, will give it a try !

**Comment by squalou** [comment]
Thx,
unfortunately for me it did not work for Tilix.

**Comment by squalou** [comment]
Answer to self : this is 'sort of' working 

`GTK_THEME="Adwaita-dark" GDK_BACKEND=x11 tilix --display :0.0 --quake`

or

`GTK_THEME="Adwaita-dark" GDK_BACKEND=x11 tilix  --quake` depending on... dunnown what

the widow is not "quake like" placed but at least it pops up / goes away on keyboard shortcut
