### ISSUE TITLE
Make design components available to the community

### ISSUE THREAD

**Issue by M00NJ** [pop-os/cosmic-epoch#416]
It would be great if the COSMIC UI components (sidebar, buttons, etc.) where made available to the community, so we can create mock-ups for community projects or proposals. Since the UI design was done in Figma,  they could be published in the community tab, similar to how [Material Design](https://www.figma.com/community/file/1035203688168086460/material-3-design-kit) does it.

**Comment by neoakris** [comment]
Note: Cosmic is based on Iced.  
(So I'm pretty sure what you're asking is already available via the upstream / nothing needs to be done by the System 76 team developing Cosmic DE. Even if they make any Cosmic specific improvements those will probably get up-streamed or made available via libraries given time, just need to be patient and let it cook.)

https://iced.rs/
^-- Cosmic DE is in their showcase

https://github.com/iced-rs/iced

**Comment by mmstick** [comment]
@neoakris Not relevant to COSMIC and its libcosmic GUI toolkit.

**Comment by M00NJ** [comment]
@neoakris This request is regarding the UI design files that were created by the COSMIC design team. 

In Figma, you can create components like a button and use instances of these components across a design file. This makes designing UI easier because it reduces duplication. I don't need to have a button, button-pressed, button-hover, etc. component. I can just design a button component with multiple states that shares all the other attributes. It also makes it easier to make changes later on. If I think the buttons in my mock-up are too small, I don't need to change every one of them individually. I can just edit the component, and all instances will reflect the change.

So my proposal is to publish a file in the Figma community tab with all the libcosmic components that have already been designed, so we can use instances of them for community projects. This would benefit the growing COSMIC ecosystem and is very much in line with the open-source philosophy of System76.

**Comment by M00NJ** [comment]
It's happening :)

https://www.figma.com/design/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=2132-3893
