### ISSUE TITLE
Terminal changes the size in Neovim in tiling mode

### ISSUE THREAD

**Issue by couchpotato007** [pop-os/cosmic-epoch#421]
The terminal changes the size when I enter a command in Neovim that either deletes or replaces something. E.g. dd, dw or cw etc .... In this case I'm using wezterm, but I've noticed it in cosmic terminal as well. This only happens in tiling mode.

https://github.com/pop-os/cosmic-epoch/assets/32217975/b06736e6-0a4f-4d90-9add-98ff3cf942e1

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/issues/555
