### ISSUE TITLE
[BUG] Firefox opened, no icon in luncher

### ISSUE THREAD

**Issue by xiaguangbo** [pop-os/cosmic-epoch#423]
Firefox app have, label page no have.
All use firefox default icon?
![图片](https://github.com/user-attachments/assets/658b3d7b-6786-4990-b204-79abb869d2a2)

**Comment by exstntlmsnthrp** [comment]
I do not have this issue with Firefox.

![Screenshot_20240712_154808](https://github.com/user-attachments/assets/5a7a411e-94b0-4b4a-9c21-76284266f48e)

What repository have you used to install Firefox?

**Comment by xiaguangbo** [comment]
> I do not have this issue with Firefox.
> 
> ![Screenshot_20240712_154808](https://private-user-images.githubusercontent.com/57594290/348380117-5a7a411e-94b0-4b4a-9c21-76284266f48e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTQ0MjYsIm5iZiI6MTcyMDgxNDEyNiwicGF0aCI6Ii81NzU5NDI5MC8zNDgzODAxMTctNWE3YTQxMWUtOTRiMC00YjRhLTljMjEtNzYyODQyNjZmNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE5NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTIyZmJlMDZlNDk5MTVmZjBmZjUyY2JmMjFlYzE0NzA4NWYzZjFlZmNkMGM0ODNmMTdkYmYzMWFkNDA3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EgeUsw1c5TDXCoVK6AVfENX1Khzd_g7msk6WJVO5Kng)
> 
> What repository have you used to install Firefox?

Open luncher before open a webpage in Firefox, can look this issue.

From system self.

**Comment by wiiznokes** [comment]
Could you describe the steps to reproduce?

**Comment by xiaguangbo** [comment]
Step 1: Firefox no run, search `f` in luncher, is ok.
![screenshot-2024-07-13-04-28-18](https://github.com/user-attachments/assets/693cc489-b75c-4968-923b-b9625ca0b4fd)

Step 2:  Open firefox, open luncher or search `f` in luncher, all have problem.
Look the `Mozilla Firefox`, that is webpage, no icon
![screenshot-2024-07-13-04-29-24](https://github.com/user-attachments/assets/6073b214-5f2a-4ece-8ea5-f7b6a45fc922)

**Comment by xiaguangbo** [comment]
is ok
