### ISSUE TITLE
[BUG] Interacting with menu on VS Code in Wayland mode causes desktop freeze

### ISSUE THREAD

**Issue by Hillard28** [pop-os/cosmic-epoch#429]
If I launch VS Code in native Wayland by adding environment variable `export ELECTRON_OZONE_PLATFORM_HINT=wayland` to .profile and/or .bashrc, and then begin interacting with the menu bar, this quickly causes the entire desktop to freeze and the only option is a hard shutdown. This does not occur in Gnome Wayland when using the "Pop on Wayland" option at login. Changing the VS Code setting "Window: Title Bar Style" to "Custom" (`"window.titleBarStyle": "custom"`) appears to fix the issue.

This issue does not occur when VS Code is run as default in XWayland, but since I have a HiDPI monitor and need to use 200% scaling, XWayland seems to read this as a fractional value and the image appears stretched.

The below video captures the behavior needed to cause the freeze in Cosmic, which I had to capture in Pop on Wayland. Please let me know if there is any additional detail that would be helpful! In the meantime, will test some other Electron apps.

EDIT: handful of Electron apps won't even launch with that parameter setting (or `export ELECTRON_OZONE_PLATFORM_HINT=auto`) so might as well stick with XWayland for the time being.

[20240715_vscode_wayland_cause.webm](https://github.com/user-attachments/assets/a33b2eda-4f96-47a0-9cb5-fbcc26e098fd)

**Comment by Drakulix** [comment]
Thanks for the detailed instructions, I was able to reproduce this and track it down into some upstream component. Will hopefully be resolved soon.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/989ee95858077aeb0f3e75e44bfeaf607c57f5c3

**Comment by Hillard28** [comment]
Yep, looks that way!
