### ISSUE TITLE
relm4-macros on arch with cosmic-applibrary and cosmic-launcher

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-epoch#43]
the affected repos are 

[cosmic-applibrary](https://github.com/pop-os/cosmic-applibrary)
[cosmic-launcher](https://github.com/pop-os/cosmic-launcher)

it happens when using the justfile as well as manually compiling them

**Comment by Absolucy** [comment]
What is it specifically that's happening?

**Comment by Quackdoc** [comment]
sorry didn't have time to investigate it last night
relm4-macros = { git = "https://github.com/AaronErhardt/Relm4" } needs changed to relm4-macros = { git = "https://github.com/Relm4/Relm4" } as the URL has changed, 

and rustc needs bumped to 1.61

**Comment by ids1024** [comment]
Hm, the URL should redirect fine, and I would expect `Cargo.lock` to reference a commit of relm4 that builds with the `rust-toolchain` version.

But both can be updated.

**Comment by ids1024** [comment]
Updated in https://github.com/pop-os/cosmic-applibrary/commit/5ab6488c5045798c612678a958129a108c9caf6c and https://github.com/pop-os/cosmic-launcher/commit/60dfef9fa57647641a7599a9e311435a4a70bbab.
