### ISSUE TITLE
why greeter is mandatory for cosmic session? or, minimal dependency list ...

### ISSUE THREAD

**Issue by soloturn** [pop-os/cosmic-epoch#447]
@yochananmarqos retired the cosmic-epoch arch linux package in favor of single packages, which is great. now one can install cosmic-session, and it has dependencies. the mandatory dependeny list seems to be excessive with below packages, it would be really cool to shift most of them to optional dependencies:

```
depends=(
  'cosmic-applibrary-git'
  'cosmic-applets-git'
  'cosmic-bg-git'
  'cosmic-comp-git'
  'cosmic-greeter-git'
  'cosmic-icons-git'
  'cosmic-launcher-git'
  'cosmic-notifications-git'
  'cosmic-osd-git'
  'cosmic-panel-git'
  'cosmic-randr-git'
  'cosmic-screenshot-git'
  'cosmic-settings-daemon-git'
  'cosmic-settings-git'
  'cosmic-workspaces-git'
  'otf-fira-mono'
  'otf-fira-sans'
  'xdg-desktop-portal-cosmic-git'
  'xorg-xwayland'
)
```

which ones of above are really mandatory, and why? without cosmic-greeter cosmic fails to start:

```
Jul 22 04:59:25  cosmic-session[53356]: starting process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=60 cosmic-greeter '
Jul 22 04:59:25  /usr/lib/gdm-wayland-session[53356]: 2024-07-22T02:59:25.788825Z  INFO cosmic_session::comp: sending 1 fds
Jul 22 04:59:25  /usr/lib/gdm-wayland-session[53356]: 2024-07-22T02:59:25.788883Z  INFO launch_pad: starting process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=60 cosmic-greeter '
Jul 22 04:59:25  cosmic-session[53356]: thread 'main' panicked at 'failed to start cosmic-greeter': src/main.rs:439
```

**Comment by git-f0x** [comment]
All those packages (except maybe fonts eventually, but not yet) are necessary to have a functional desktop. You can't install e.g. GNOME without workspaces, the top bar, or a way to launch apps.
cosmic-session can't really do much by itself. Its job is to start and restart processes as necessary.
cosmic-greeter is used for the lock screen (which is why it's required), as well as a display manager if configured.

**Comment by soloturn** [comment]
i tried it without coxmic-greeter, and it does not work. logging in from gdm starts cosmic, and it tries to start cosmic-greeter, cannot, and fails altogether. having cosmic greeter installed lets me lauch cosmic, but lock screen does not work. also - why would one need to have coscmic-screenshot installed to make it work. or why would one need a panel or dock? the only function necessary should be to stop cosmic after one started it.

**Comment by git-f0x** [comment]
The lock screen not working currently is a known issue.
>why one would need to have coscmic-screenshot installed as mandatory component

While not strictly mandatory, it is a part of the DE (same as how GNOME has a built in screenshot tool), and it makes sense to have some kind of screenshot functionality built-in. But that can certainly be changed in Arch, once it is officially packaged.
>why would one need a panel or dock?

That's a core package, without which you wouldn't be able to easily use any applet. If you don't want the Dock appearing, it can be turned off in Settings, and the Panel can be turned off with COSMIC Tweaks.

**Comment by yochananmarqos** [comment]
@soloturn I honestly don't understand the point here. I already answered your question before you asked and you've been able to reproduce it as you mentioned above.

As a packager, I follow upstream as best I can. As far as the dependencies for the `cosmic-session-git` AUR package, I based the dependencies on the [Debian control file](https://github.com/pop-os/cosmic-session/blob/master/debian/control).

**Comment by wiiznokes** [comment]
Technically, it might not be difficult to modularize all of this, but I think a lot of things are currently hard coded, so I would recommend to install all of the package for now

**Comment by ids1024** [comment]
We probably do want to make this more modular and configurable, but exactly how remains an open question.

Cosmic-comp tries to use standard Wayland protocols where possible, so it should be possible to use a third-party lock screen, panel, etc.

**Comment by Drakulix** [comment]
Imo there should be a meta-package for the whole desktop. On Pop!_OS this currently is `cosmic-session`, which also provides the equally named binary. Currently that isn't the worst model, given cosmic-session isn't skipping over missing components gracefully. I consider that a bug, but until that is fixed there really is no reason to split `cosmic-session`. Other components however shouldn't extensively depend on each other, e.g. `cosmic-comp` can be used standalone.

**Comment by soloturn** [comment]
ah, if the lock screen is just a bug, than all is clear, and if it follows wayland standard protocols, its perfect. having the dependencies to cosmic session makes a lot of sense to me.

i was just searching for a way to make the switch over from gnome or other desktop easy - which means leave the display manager in place in a first step, and later offer to switch it. for screenshot i was searching for something which does screen recording and remove the one which does not (yet).

we close the ticket, at least my questions are answered?
