### ISSUE TITLE
archlinux: all system icon are just black

### ISSUE THREAD

**Issue by woodgear** [pop-os/cosmic-epoch#451]

**Comment by woodgear** [comment]
![image](https://github.com/user-attachments/assets/75cce97a-e80e-4f59-838f-300c418ce6ab)

**Comment by woodgear** [comment]
still not work...
lspci |grep VGA
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)] (rev d9)

❯ yay -Q |grep vlk

❯ yay -Q |grep vul
djvulibre 3.5.28-6
vulkan-headers 1:1.3.285-1
vulkan-icd-loader 1.3.285-1
vulkan-radeon 1:24.1.4-2

**Comment by soloturn** [comment]
did you install cosmic-session-git from AUR or differently?

**Comment by woodgear** [comment]
yes 。
i install via yay -s cosmic-session-git

**Comment by 4EBOOT** [comment]
Hi! Having the same problem on intel integrated graphics.
```
[no@no]$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
[no@no]$ paru -Q | grep "vlk"
[no@no]$ paru -Q | grep "vul"
djvulibre 3.5.28-6
lib32-vulkan-icd-loader 1.3.279-1
vulkan-headers 1:1.3.285-1
vulkan-icd-loader 1.3.285-1
vulkan-tools 1.3.269-1
```

**Comment by chdalski** [comment]
I had the same issue and needed to install the vulkan-drivers for my graphic cards (Intel iGPU and nvidia dGPU) as @mmstick suggested.
How to depends on the drivers your using (open-source vs. closed-source).
For arch take a look [here](https://wiki.archlinux.org/title/Vulkan#Verification).

**Comment by woodgear** [comment]
make sure vulkaninfo works normal. and the icon display normal.

**Comment by piotr25691** [comment]
> The following command did the job for me: `paru -S vulkan-intel`.

Update: You do not need the AUR to install these drivers, just use the relevant `sudo pacman` command instead, eg.

```sh
# Intel Integrated GPUs
sudo pacman -S vulkan-intel
# AMD GPUs
sudo pacman -S vulkan-radeon
# NVIDIA GPUs
sudo pacman -S vulkan-nouveau
```

**Comment by soloturn** [comment]
what package needs this, cosmic-comp, @mmstick ?

**Comment by OfficiallySp** [comment]
I'm having this same issue as well as only having a single monitor instead of two. I'm running an nvidia card and Installing open nvidia drivers as well as Vulkan drivers didn't fix the problem.
