### ISSUE TITLE
Some shortcuts not working

### ISSUE THREAD

**Issue by michaelBelsanti** [pop-os/cosmic-epoch#475]
When using cosmic, some of the default shortcuts aren't working. It seems to be specifically all of the shortcuts in the System section of the settings, plus pressing Super is not doing the action set in the Desktop and Panel settings.

I haven't found any useful logs using journalctl, I'm unsure if there's anywhere else I should look.

I am running Cosmic on NixOS using the version of [nixos-cosmic](https://github.com/lilyinstarlight/nixos-cosmic/).

**Comment by git-f0x** [comment]
It will be fixed when cosmic-comp is updated in that repo.

**Comment by michaelBelsanti** [comment]
Got it, thanks!
