### ISSUE TITLE
Feature Request: add the option to set Underscan On from Cosmic-Randr

### ISSUE THREAD

**Issue by ITheCrusherI** [pop-os/cosmic-epoch#480]
I have an LED Tv as my second monitor, and it overscans when using 1920x1080 resolution. This is solved, in Gnome, using Xrandr as follows: 
xrandr --output [DEVICE PORT] --set "underscan hborder" [H-value] --set "underscan vborder" [V-value]
xrandr --output [DEVICE PORT] --set underscan on
I cannot do this on Cosmic. Would it be possible to add such a feature in COSMIC, or is it a problem with Wayland in general? Thanks!

**Comment by mmstick** [comment]
Your TV should have a setting to disable underscan.

**Comment by ITheCrusherI** [comment]
Sadly, it doesn't have one. I already checked every option and it doesn't have that option. It's an old TV :(

**Comment by Drakulix** [comment]
> I cannot do this on Cosmic. Would it be possible to add such a feature in COSMIC, or is it a problem with Wayland in general? Thanks!

It is not a problem in general and possible, but not at all implemented at the moment.

**Comment by ITheCrusherI** [comment]
Cool, good to know! Thanks everyone for taking the time
