### ISSUE TITLE
pressing alt-tab once doesn't change windows

### ISSUE THREAD

**Issue by mahershalal2** [pop-os/cosmic-epoch#483]
(Please let me know if I'm posting this in the wrong place)

I love the new alt-tab behavior, but one thing makes it hard for me to use, and that is that it doesn't switch windows if I only press alt-tab once. On every other DE this works but on Cosmic the focus always stays with the window at top of the application list.

Even if the list would be ordered by most recently used (which I hope it will be in the future), this problem would persist.

Suggestion: pressing alt-tab should select the *second* window in the application list.

Thanks!

**Comment by git-f0x** [comment]
This is a known issue, tracked [here](https://github.com/pop-os/cosmic-launcher/issues/135).

**Comment by mahershalal2** [comment]
Ok brilliant. I will close this. Thanks!

**Comment by mahershalal2** [comment]
Ok brilliant, thanks.
