### ISSUE TITLE
Repository is currently in an unbuildable state

### ISSUE THREAD

**Issue by kode54** [pop-os/cosmic-epoch#49]
```
error: failed to load source for dependency `smithay`

Caused by:
  Unable to update https://github.com/Smithay//smithay?branch=update/drm-0.7#382ac1a0

Caused by:
  object not found - no match for id (382ac1a0d2351222509d185e4e32231f20c1dda4); class=Odb (9); code=NotFound (-3)
make: *** [Makefile:27: all] Error 101
```

**Comment by Drakulix** [comment]
Sorry, the cosmic-comp submodule needed to be updated. I just pushed some changes, that should fix the issue.

**Comment by kode54** [comment]
Thanks, I'll check it out.

**Comment by Drakulix** [comment]
..and meson doesn't like no `--reconfigure` on already existing directories.
I pushed a commit that removes a previously existing build directory. Not the cleanest solution, but should get the job done.

Thanks for pointing this out.
