### ISSUE TITLE
Steam App wont reopen once closed to tray and won't respect tiling

### ISSUE THREAD

**Issue by hbacelar8** [pop-os/cosmic-epoch#497]
Steam app will only open the first time and if closed to tray it's impossible to reopen it, the process has to be killed in order to open it again.

Also, tiling manager never seems to work on steam window.

**Comment by codevski** [comment]
having this same issue. Seeing this also happening with discord once its closed the open

**Comment by Drakulix** [comment]
> Also, tiling manager never seems to work on steam window.

Because steam is in our (currently static) list of tiling-exceptions. You can still force it tiled with the shortcut. (or the headerbar context menu, if it would display that...)

**Comment by hbacelar8** [comment]
> > Also, tiling manager never seems to work on steam window.
> 
> Because steam is in our (currently static) list of tiling-exceptions. You can still force it tiled with the shortcut. (or the headerbar context menu, if it would display that...)

I noticed Win+G activates the tiling for it.

**Comment by TacticalNuke974** [comment]
The not able to open a closed window with minimized icon also happens with lunar client

**Comment by Department-stack** [comment]
I am having the same issue with the tray not popping back on on vlc

**Comment by jyue86** [comment]
The same happens with Slack as well. After closing the window, I am unable to open it again

**Comment by pvdrz** [comment]
I've noticed this same behavior with electron apps such as `spotify` and `signal-desktop`. By checking signal's logs it seems the app is actually trying to render the window:
```text
{"level":30,"time":"2024-08-30T16:28:54.162Z","msg":"System tray service: showing the window from the context menu"}
{"level":30,"time":"2024-08-30T16:28:54.162Z","msg":"System tray service: rendering the tray"}
{"level":30,"time":"2024-08-30T16:28:56.530Z","msg":"System tray service: hiding the window from the context menu"}
{"level":30,"time":"2024-08-30T16:28:56.530Z","msg":"System tray service: rendering the tray"}
{"level":30,"time":"2024-08-30T16:28:59.295Z","msg":"System tray service: showing the window from the context menu"}
{"level":30,"time":"2024-08-30T16:28:59.296Z","msg":"System tray service: rendering the tray"}
```

**Comment by GetPsyched** [comment]
Having the same issue with both Steam and Heroic.

**Comment by cywil5115** [comment]
Same for Discord flatpak.

**Comment by jyue86** [comment]
Slack and Discord open now after being closed. I'm not sure which commit fixes this issue

**Comment by GetPsyched** [comment]
I can confirm that it's working for me now as well.

@hbacelar8 can you update and check?

**Comment by leviport** [comment]
Sounds like this can be closed now. It can be reopened if needed.

**Comment by Zimrahin** [comment]
Hello! I just upgraded to 24.04 from 22.04 and have both issues mentioned here.
I can't reopen Steam and the tiling doesn't work by default (although I can make it work by pressing Super + G)
