### ISSUE TITLE
Tiling Design

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-epoch#5]

**Comment by maria-komarova** [comment]
Considering that tiling can be broken into multiple individual projects and features, we're going to file separate issues for each of those and link them to this master issue. 
1. [New tiling with keyboard designs](New Tiling With Keyboard Designs)
2. [Designs for tiling with the mouse](https://github.com/pop-os/cosmic-epoch/issues/35)

**Comment by WatchMkr** [comment]
Most design is complete. Currently working through when to stack windows once they become small as well as tiling behavior beneath minimum app advertised dimensions.

**Comment by maria-komarova** [comment]
Considering a lot of windows might not be very useful when they get too small and considering we'll have a minimum window size (360px), there is a suggestion that we should start stacking windows rather than splitting them in half after the tile reaches a certain size. 
Regarding minimum window size we'll have three groups of common display resolutions and when we should start stacking. 
- start opening new windows in a stack when the tile is 1/4th of the display (1280x720; 1366x768 displays)
- start opening new windows in a stack when the tile is 1/8th of the display for majority of common display resolutions (1440x900; 1536x864; 1600x900; 1920x1080)
- start opening new windows in a stack when the tile is 1/16th of the display for most ultrawide displays (2560x1080; 3440x1440; 3840x1080; 3840x1200; 3840x1600; 5120x1440; 5120x2160)
- start opening new windows in a stack when the tile is 1/32nd of the display for super uptra-wide (7680x2160).

We're thinking we can clip the content for apps that enforce larger minimum size than the point at which we start stacking windows.

**Comment by anzanhoshin** [comment]
Hello,
I suggest that stacking as a default based on size (and setting that size)
can be toggled on or off in settings by user.

**Comment by Nyabinary** [comment]
Different apps each have a different behavior maybe customizable in the settings?
