### ISSUE TITLE
No COSMIC option in display manager

### ISSUE THREAD

**Issue by kprasadvnsi** [pop-os/cosmic-epoch#50]
I have built and install Cosmic with the help of instruction in the readme. It works on Ubuntu 22.04 but COSMIC option did not show up in PopOS 22.04.

**Comment by senntore** [comment]
It could be because wayland is disable by default in pop os. You can enable it by changing WaylandEnable to true or commenting it out in /etc/gdm3/custom.conf
And then reboot.

**Comment by kprasadvnsi** [comment]
> It could be because wayland is disable by default in pop os. You can enable it by changing WaylandEnable to true or commenting it out in /etc/gdm3/custom.conf And then reboot.

Yes, This was the issue. thanks
