### ISSUE TITLE
Fullscreen Games Broken

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [pop-os/cosmic-epoch#507]
On the Cosmic Alpha, if you launch a full screen game, you'll get a black screen, and the display it was on will crash until you reboot. The sounds for the game are still running on the background. Tested with multiple games, and the same games that are breaking run (mostly) fine if you force them into windowed mode. They at least don't crash the display, but I've had a few games that run and only take input from the keyboard, completely ignoring the mouse. I've also tried turning window tiling off on all my monitors in case that was the issue, and it doesn't make a difference.

Nvidia GPU

**Comment by ryzendew** [comment]
Also amd gpu's and intel

**Comment by Drakulix** [comment]
It's certainly not all games, please report to this issue what exactly you tested and which distribution you are using: https://github.com/pop-os/cosmic-epoch/issues/311

**Comment by ryzendew** [comment]
> It's certainly not all games, please report to this issue what exactly you tested and which distribution you are using: #311

every game i own almost 2000 do this

**Comment by Drakulix** [comment]
> > It's certainly not all games, please report to this issue what exactly you tested and which distribution you are using: #311
> 
> 
> 
> every game i own almost 2000 do this 

Sounds more like a systematic problem then that might not be 100% related to just cosmic, given many games work fine on my machine.

what distro are you running cosmic on?

**Comment by ryzendew** [comment]
> > > It's certainly not all games, please report to this issue what exactly you tested and which distribution you are using: #311
> > 
> > 
> > every game i own almost 2000 do this
> 
> Sounds more like a systematic problem then that might not be 100% related to just cosmic, given many games work fine on my machine.
> 
> what distro are you running cosmic on?

the iso for cosmic de i also tested it on fedora 40 and Arch and all have the same issue

**Comment by Minc3** [comment]
@Drakulix I am having the same issue on fedora.

Full screen games just freeze the compositor but the game still runs. I can hear it on the main menu but the monitor thats fullscreen is frozen.

Running games in boarderless window allows me to play games.

GPU: 4090, Driver: 555.58.02

I'm currently re-installing on arch with no Gnome DE.

**Comment by Drakulix** [comment]
See this comment please for everyone experiencing a frozen screen on pop-os (or knows how to build cosmic-comp from source): https://github.com/pop-os/cosmic-comp/issues/702#issuecomment-2277706597
