### ISSUE TITLE
Switching to full-screen with brave browser  makes screen unresponsive

### ISSUE THREAD

**Issue by jsanchezba** [pop-os/cosmic-epoch#508]
When using Brave browser and after a few seconds of switching to full-screen becomes unresponsive.
Tried with flatpak version and also installing from official brave repository.

Seems like the overlay freezes. You cannot close the browser anymore, so you have to close session or restart.

Fresh Alpha-1 install with Nvidia ISO
Brave [Version 1.68.137 Chromium: 127.0.6533.100 (Build oficial) (64 bits)](https://brave.com/latest/)

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/issues/702

**Comment by jsanchezba** [comment]
I'll close this issue as there is one more relevant on the cosmic-comp repo.
