### ISSUE TITLE
GTK4 applications have broken icons and font rendering

### ISSUE THREAD

**Issue by sgued** [pop-os/cosmic-epoch#510]
This is visible in the screenshot: 

![screenshot-2024-08-08-20-24-04](https://github.com/user-attachments/assets/68ca60e2-996b-4072-b657-38e577497d58)

An icon is missing, and the text rendering is pixelated (it is very smooth on sway for comparison example).

This appear to affect all gtk4 apps, not just libadwaita.

I did not set the experimental "apply theme to gtk apps", and enabling it does not solve the issue.

The issue initially did not happen, i started happening once I started using the cosmic-xdg-desktop-portal through `~/.config/xdg-desktop-portal/portals.conf` with:

```
[preferred]
default=cosmic
```

I'm using alpha 1 on arch linux.

**Comment by exstntlmsnthrp** [comment]
I can confirm that I'm seeing this as well, testing in both Arch and Pop22.04. It started occurring after making the same config change. 

Not sure if it matters, but I'm also using an Nvidia 4070 graphics card - with no integrated graphics available. That has caused some similar issues in the past, so I wasn't sure if it was cosmic related or graphics card related.

**Comment by sgued** [comment]
This is not an NVidia problem, I'm on AMD 5800H + Radeon 6600M

**Comment by exstntlmsnthrp** [comment]
Well, Nvidia and Linux have had a complicated relationship over the years and haven't always played well together. This has included graphics anomalies at times. Just wasn't sure if this was one of them.

**Comment by Drakulix** [comment]
You shouldn't manually configure the xdg-desktop-portal. The xdg-desktop-portal-cosmic package has a config file setting everything up correctly with the required fallbacks to other portals, since we don't support all the portal-interfaces yet. What lead you to believe you needed to do that?

**Comment by sgued** [comment]
Ok, it's because I didn't launch `cosmic-session` correctly. I launched it from the TTY like I'm used with sway (`XDG_CURRENT_DESKTOP=cosmic cosmic-session`), and without the override for the portals it used `xdg-desktop-portal-gtk`, which isn't what's supposed to be used with cosmic.

Launching cosmic through a display manager (e.g. GDM) solves this issue. I'm not sure how to get cosmic-greeter to work as a display manager though. Launching it from the TTY does not work (it says its missing a compositor).
