### ISSUE TITLE
Feature request: fastfetch instead of neofetch

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-epoch#511]
As it's probably well-known by now, [neofetch](https://github.com/dylanaraps/neofetch) is EOL. Some distros like Arch, Fedora, and even [Ubuntu 24.10](https://packages.ubuntu.com/source/oracular/fastfetch), have opted to replace it with [fastfetch](https://github.com/fastfetch-cli/fastfetch) instead, which is a proper fetching app instead of a script, meaning it's much smaller and quicker.

**Comment by Drakulix** [comment]
I don't think this has any relevance for COSMIC, this is a distribution problem.

**Comment by hfc2x** [comment]
You're right. I'll move this issue into the proper repository.
