### ISSUE TITLE
Feature request: Blue light filter

### ISSUE THREAD

**Issue by nvkomata** [pop-os/cosmic-epoch#514]
a simple blue light filter (configurable temperature of your screens' colors?)

optionally should be able to disable/enable based on the time of day

**Comment by git-f0x** [comment]
This is planned, but since it's part of a larger color management story (including HDR), Night Light will be added post-release.

**Comment by jokeyrhyme** [comment]
Possibly a duplicate of https://github.com/pop-os/cosmic-epoch/issues/476

**Comment by leviport** [comment]
Closing as a duplicate of https://github.com/pop-os/cosmic-epoch/issues/476
