### ISSUE TITLE
Launching Battle.net client through Lutris results in CTD

### ISSUE THREAD

**Issue by pcallycat** [pop-os/cosmic-epoch#528]
Installed lutris using apt, and installed the battlenet launcher successfully.  Launcher loads sign in page with no issues.  Once the app tries to progress past the login, it will CTD with a failed request:badwindow error.  crash log notes below.  
Steps taken to resolve:
updated lutris to latest release
set to run specifically on dgpu
set to run specifically on igpu
verified all lutris dependencies were installed
hardware:  Asus FA617NT (AMD Advnatage Edition laptop).

Verified works on Nobara and Endeavour, not sure if this is a Cosmic issue or a Lutris issue

wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Initial process has exited (return code: 0)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x2e0000a
  Serial number of failed request:  783
  Current serial number in output stream:  795
Monitored process exited.
Exit with return code 0

**Comment by pcallycat** [comment]
This may be able to be closed.  On first blush, I didn't realize that about everything I was installing was coming down as a flatpak and not something useful (the sandboxing in snap and flatpak breaks a lot without fiddling and tweaking).  This may be resolvable by just giving lutris permissions, but I have not had the opportunity to test this

**Comment by Vantadaga** [comment]
Did you find a fix?, I have the same issue

**Comment by pcallycat** [comment]
I think there’s a bug or exception in the window handles for the compositor, but didn’t chase it down. Initially thought it was a flatpak sandboxing thing, but installed cosmic on arch for testing, and lutris from ‘not a flatpak’, and experienced the same result. Unfortunately, I did not find a resolution except to go back to kde for now. My intent is to reopen the bug report, but with better info than my first attempt, as for now, it is unresolved.

**Comment by leviport** [comment]
If it's unresolved, let's leave this open

**Comment by pcallycat** [comment]
I can no longer replicate this issue.  It may be possible to close if we can verify I'm not just lucky.

**Comment by Drakulix** [comment]
We fixed a bunch of BadWindow errors recently and the Fedora copr ships recent enough compositor builds. So I am inclined to call this fixed.

**Comment by Vantadaga** [comment]
I am still having this issue
