### ISSUE TITLE
Workspaces Settings Panel

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-epoch#53]
The **Workspaces** panel in COSMIC Settings is where users will go to change their workspaces behavior, orientation, and representation on the [Workspaces Overview](https://github.com/pop-os/cosmic-epoch/issues/47).

![Workspaces Settings Panel, detailed below.](https://user-images.githubusercontent.com/106764128/200682369-d445429c-1050-4873-a91c-33784cfca75c.png)

The **Workspace Behavior** section is where users can choose Dynamic Workspaces (the default) or Fixed. Because of changes we are making to Multi-Monitor Behavior (see below), it's possible that the user can have different numbers of fixed workspaces on each display, so the user will edit the number of workspaces in the overview, not in this panel.

We'll be adding a new **Multi-Monitor Behavior** option for displays having separate workspaces. With that option, each display can have multiple workspaces and switch between them independently. If the user wishes to retain the current Pop!_OS functionality of only having multiple workspaces on one display, they can still emulate that by only adding workspaces to displays as desired.

In addition, each option has an animation on hover. However, we are also choosing animations that, through testing, express the concepts clearly without animation.

![For Workspaces Span Displays, both monitors animate. For Displays Have Separate Workspaces, each monitor transitions workspaces independently.](https://user-images.githubusercontent.com/106764128/200681731-7f5ecd59-222e-4935-aaba-ab84464c4d91.gif)
_An example of animation in the multi-monitor behavior section._

**Workspace Orientation** will allow two orientations: Vertical and Horizontal. The monitor above that switch will update with a visualization that previews how the Workspace thumbnails will be arranged in the overview. Users can also choose on which side those thumbnails are placed.

That section will also show trackpad gestures, which are connected to the workspace orientation.

Workspace Overview Thumbnails has options for showing Workspace Number and Workspace Name on the [workspace overview](https://github.com/pop-os/cosmic-epoch/issues/47).

**Comment by SViN24** [comment]
looks great but will there be an option for a three finger gesture?

**Comment by carlwgeorge** [comment]
@SViN24 I asked the same thing on Mastodon and got [this response](https://fosstodon.org/@carlrichell/109317593421632926).

> the current plan is for three finger gestures to be configurable by the user in Settings. We haven’t fleshed out the available configurable three finger gestures but I image workspace switching could be an option as well.

See also #54.

**Comment by rayjaymor85** [comment]
"Displays have separate workspaces"

Just to clarify, does this mean Cosmic will have the same type of workspace management that MacOS has? If so I'll be dumping GNOME for Cosmic ASAP.

It's literally the only part of MacOS that I miss when I use my Linux system lol

**Comment by leviport** [comment]
@rayjaymor85 Sorry to not answer your question right away, but it might be helpful to the UX team to ask why you asked for this clarification based on the mockups above, and what you think would make the designs more clear?

**Comment by rayjaymor85** [comment]
Honestly the designs look pretty clear - I think it's more just shocking disbelief because I've been trying to find this function on Linux for over 2 years and had no luck!

**Comment by kewur** [comment]
> Honestly the designs look pretty clear - I think it's more just shocking disbelief because I've been trying to find this function on Linux for over 2 years and had no luck! 

i3 is the only wm that had this functionality on linux previously

**Comment by sanwablo** [comment]
> **Workspace Orientation** will allow two orientations: Vertical and Horizontal.

Will it be possible to set up a workspace grid (with both rows and columns, like 2x2 or 2x3)?

**Comment by WatchMkr** [comment]
The Settings GUI includes what will be included in the first release.

**Comment by saipavanc** [comment]
I have been very much looking forward to having a fixed number of workspaces as shown in this issue. I did not see this feature described elsewhere, is this feature still being implemented? If not is there a workaround to get a fixed number of workspaces in Cosmic?

**Comment by maria-komarova** [comment]
Yes, we just had a workaround feature design for fixed workspaces: https://github.com/pop-os/cosmic-workspaces-epoch/issues/108.
