### ISSUE TITLE
[feature request] system-wide custom font

### ISSUE THREAD

**Issue by YardQuit** [pop-os/cosmic-epoch#549]
I like to see the option to freely set a default system-wide font as I can
do in GNOME with command:

"gsettings set org.gnome.desktop.interface font-name "Liberation Mono 10"

**Comment by WatchMkr** [comment]
Add Font selection to Settings > Appearance > Experimental settings

**Comment by WatchMkr** [comment]
Tracking this here: https://github.com/pop-os/cosmic-settings/issues/649
