### ISSUE TITLE
iced error, unable to build

### ISSUE THREAD

**Issue by LethalManBoob** [pop-os/cosmic-epoch#55]
error: failed to get `iced` as a dependency of package `adw-user-colors-lib v0.1.0 (/home/joseph/cosmic-epoch/user-color-editor/adw-user-colors-lib)`

Caused by:
  failed to load source for dependency `iced`

Caused by:
  Unable to update https://github.com/wash2/iced?branch=custom-theme#4ff019b1

Caused by:
  object not found - no match for id (4ff019b1e8e520d27cf3e6aa635e43a47771a46a); class=Odb (9); code=NotFound (-3)
[2/3] Generating data/com.system76.UserColorEditor.metainfo.xml with a custom command
FAILED: src/user-color-editor 
/usr/bin/env CARGO_HOME=/home/joseph/cosmic-epoch/user-color-editor_build/cargo-home /usr/bin/cargo build --manifest-path /home/joseph/cosmic-epoch/user-color-editor/Cargo.toml --target-dir /home/joseph/cosmic-epoch/user-color-editor_build/src --release && cp src/release/user-color-editor src/user-color-editor
ninja: build stopped: subcommand failed.
error: Recipe `_meson_build` failed on line 11 with exit code 1

**Comment by RuneFFF** [comment]
I have the same problem. What distro are you on?

**Comment by LethalManBoob** [comment]
Arch Linux

**Comment by RuneFFF** [comment]
Hm, same here. I tried pop too but had the same issue there.

**Comment by RuneFFF** [comment]
Hm, same here. I tried pop too but had the same issue there.

**Comment by pyover180** [comment]
Workaround: go to `(master)/user-color-editor/adw-user-colors-lib` and edit the `iced` dependency in  `config.toml` to only have the git link. 

Though I'd imagine someone will have to come clean up that dependency at some point lmao

**Comment by wash2** [comment]
Hi thanks for reporting the issue! I was working on user-color-editor, but it has recently been archived and will shortly be removed from cosmic-epoch.

**Comment by LethalManBoob** [comment]
> Hi thanks for reporting the issue! I was working on user-color-editor, but it has recently been archived and will shortly be removed from cosmic-epoch.

please let us know when its removed in the git so we can build. thanks. :)

**Comment by wash2** [comment]
latest should build and run

**Comment by LethalManBoob** [comment]
> latest should build and run

Now its giving me errors about libcosmic not being installed.

**Comment by ids1024** [comment]
What specific error message is it showing?

Perhaps we could set up some sort of CI on this repository, that might help a bit.

**Comment by hojjatabdollahi** [comment]
@wash2  @ids1024  The error is because `cosmic-app-library` depends on the `sctk-cosmic-design-system ` branch of libcosmic which got merged recently.

**Comment by LethalManBoob** [comment]
> @wash2 @ids1024 The error is because `cosmic-app-library` depends on the `sctk-cosmic-design-system ` branch of libcosmic which got merged recently.

let me know when THIS is fixed as well. < u <

**Comment by wash2** [comment]
Ok, I'm in the process of updating everything to use the latest version of libcosmic. I'll update here again when it's done :)

**Comment by wash2** [comment]
Ok, this should be resolved now.

**Comment by hojjatabdollahi** [comment]
It indeed solved it. Getting `wayland-proxy-virtwl` was a little tricky. You need `libdrm-dev` installed and after installing `opam` you need to run `opam init`. But now I can run any program.

**Comment by LethalManBoob** [comment]
Its booting to a black screen with a blinking line. I run nvidia btw and on VMM - qemu/kvm

**Comment by wash2** [comment]
> Its booting to a black screen with a blinking line. I run nvidia btw and on VMM - qemu/kvm

cosmic is still mostly untested in VMs, so it may not work properly yet but this sounds like you may have an issue unrelated to the cosmic installation. Maybe make sure you've installed GDM and whatnot?

**Comment by LethalManBoob** [comment]
> > Its booting to a black screen with a blinking line. I run nvidia btw and on VMM - qemu/kvm
> 
> cosmic is still mostly untested in VMs, so it may not work properly yet but this sounds like you may have an issue unrelated to the cosmic installation. Maybe make sure you've installed GDM and whatnot?

its a full gnome install via archinstall

**Comment by LethalManBoob** [comment]
it works on my normal environment but I cant even access settings. I only get a grey screen with a taskbar with my desktop number, and options for volume, ethernet and power.

**Comment by jokeyrhyme** [comment]
> it works on my normal environment but I cant even access settings or anything really. I only get a grey screen with a taskbar with my desktop number, and options for volume, ethernet and power.

That's my experience, too, and the Super + Slash key combination ( https://github.com/pop-os/cosmic-comp/blob/3d31641c98f438f1088affe7370f763c0e2a84ec/config.ron#L85 ) doesn't seem to trigger the launcher (doesn't seem like any keyboard combinations work, weirdly enough)

But I can click to log out just fine

However, maybe we should take this to a separate issue and close this one (seems like the build issue is resolved) ?

**Comment by LethalManBoob** [comment]
I would say the only issue i had left with building it was that there are the two unlisted deps when building.
Clang and opam. But yes other than that the building goes off without issue.

**Comment by LethalManBoob** [comment]
Anyways, the build issue is all but resolved. I hope to see those deps listed and we can get to making cosmic more functional.
