### ISSUE TITLE
Cannot refresh systemd-sysext

### ISSUE THREAD

**Issue by Pebor** [pop-os/cosmic-epoch#56]
Hello, this is very much about me not knowing anything about this, but on arch, after building cosmic-epoch I moved all of `cosmic-sysext` to `/var/lib/extensions` but when I run `sudo systemd-sysext refresh` it outputs:
```
No suitable extensions found (1 ignored due to incompatible version).
```

**Comment by Drakulix** [comment]
> I interpreted this as move the contents of cosmic-sysext into /var/lib/extensions ("this will create a system-extension inside") , that's on me!
Sorry!

No worries! Feel free to submit a PR to update the wording, if you have any suggestions how to make it clearer.

I am glad you figured it out!
