### ISSUE TITLE
Cannot add shortcuts with Super in them.

### ISSUE THREAD

**Issue by reflog** [pop-os/cosmic-epoch#572]
In keyboard shortcuts, it's not possible to bind Super+Enter for example as a shortcut to lunch terminal.
Nothing happens when you press that combination (or any combination with Super)

Also, for 'Open the launcher' - the shortcut is 'Super', but when you open the edit shortcut screen - it appears empty

**Comment by almighty-atlas** [comment]
I realized there are a lot more default shortcuts, that don't appear in the shortcut list:
Super + T opens a terminal
Super + Q closes the current window
Super + A opens the application launcher
Super + F opens the file manager
and many more.

Would be great to see them inside the shortcut list and being able to override them.

**Comment by mauricekraus** [comment]
Because Super+Enter is not the correct Key, it is Super+Return (made the same mistake :D)

for reference these work on my machine:

Path: /home/mk/.config/cosmic/com.system76.CosmicSettings.Shortcuts/v1/custom

```ron

{
    (
        modifiers: [
            Super,
            Shift,
        ],
        key: "q",
    ): Close,
    (
        modifiers: [
            Super,
        ],
        key: "f",
    ): Maximize,
    (
        modifiers: [
            Super,
        ],
        key: "d",
    ): System(Launcher),
    (
        modifiers: [
            Super,
        ],
        key: "e",
    ): System(HomeFolder),
    (
        modifiers: [
            Super,
        ],
        key: "slash",
    ): Disable,
    (
        modifiers: [
            Super,
        ],
        key: "m",
    ): Disable,
    (
        modifiers: [
            Super,
        ],
        key: "q",
    ): Disable,
    (
        modifiers: [
            Super,
        ],
        key: "Return",
    ): Spawn("foot"),
    (
        modifiers: [
            Super,
        ],
    ): Disable,
}

```

**Comment by mauricekraus** [comment]
@almighty-atlas it worked for me (it is just a bit fiddely), either GUI or directly editing the config file worked.

**Comment by exstntlmsnthrp** [comment]
> I realized there are a lot more default shortcuts, that don't appear in the shortcut list:
> Super + T opens a terminal
> Super + Q closes the current window
> Super + A opens the application launcher
> Super + F opens the file manager
> and many more.
> 
> Would be great to see them inside the shortcut list and being able to override them.

If I remember correctly, most of those are default Pop_OS shortcuts and are not unique to cosmic.

**Comment by reflog** [comment]
nice, thanks
