### ISSUE TITLE
error: Recipe `build` failed with exit code 101

### ISSUE THREAD

**Issue by TiredJay** [pop-os/cosmic-epoch#58]
mkdir -p build
/usr/bin/just cosmic-applets/build
warning: /home/ja/cosmic-epoch/cosmic-applets/cosmic-applet-battery/Cargo.toml: unused manifest key: `dependencies.zbus.no-default-features`
warning: /home/ja/cosmic-epoch/cosmic-applets/cosmic-applet-network/Cargo.toml: unused manifest key: dependencies.zbus.no-default-features
   Compiling smithay-client-toolkit v0.16.0 (https://github.com/Smithay/client-toolkit?rev=73346019952f82ec7e4d4d15f5d66841b54e8b61#73346019)
   Compiling hashbrown v0.12.3
error: failed to run custom build command for `smithay-client-toolkit v0.16.0 (https://github.com/Smithay/client-toolkit?rev=73346019952f82ec7e4d4d15f5d66841b54e8b61#73346019)`

Caused by:
  process didn't exit successfully: `/home/ja/cosmic-epoch/cosmic-applets/target/release/build/smithay-client-toolkit-d69456ce026b4cca/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=XKBCOMMON_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=XKBCOMMON_STATIC
  cargo:rerun-if-env-changed=XKBCOMMON_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"xkbcommon\"` did not exit successfully: exit status: 1\nerror: could not find system library 'xkbcommon' required by the 'smithay-client-toolkit' crate\n\n--- stderr\nPackage xkbcommon was not found in the pkg-config search path.\nPerhaps you should add the directory containing `xkbcommon.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'xkbcommon' found\n"', /home/ja/.cargo/git/checkouts/client-toolkit-e56a3844de110279/7334601/build.rs:5:49
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: Recipe `build` failed with exit code 101
error: Recipe `build` failed on line 18 with exit code 101

**Comment by Drakulix** [comment]
Looks like you system is missing `libxkbcommon` for building :)

**Comment by Drakulix** [comment]
> = note: /usr/bin/ld: cannot find -lEGL: No such file or directory

Looks like you are missing a -debug or -devel package for your mesa-drivers. What kind of distribution are you on? Pop!_OS?
