### ISSUE TITLE
error: Recipe `build` failed on line 19 with exit code 1 - Attempting to build pre-release Alpha

### ISSUE THREAD

**Issue by p134c0d3** [pop-os/cosmic-epoch#59]
I am attempting to build the pre-release Alpha, and installed all required and optional dependencies, but the recipe 'build' is failing twice now with exit code 1. Log are below

`Build started at 2023-01-14T07:02:51.881852
Main binary: /usr/bin/python3
Build Options: -Dvendor=false -Dprefix=/usr
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /home/john/Downloads/cosmic-epoch/cosmic-applibrary
Build dir: /home/john/Downloads/cosmic-epoch/cosmic-applibrary_build
Build type: native build
Project name: cosmic-app-library
Project version: 0.1.0
Rust compiler for the host machine: rustc -C linker=cc (rustc 1.66.1)
Rust linker for the host machine: rustc -C linker=cc ld.bfd 2.38
Rust compiler for the build machine: rustc -C linker=cc (rustc 1.66.1)
Rust linker for the build machine: rustc -C linker=cc ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for 1 is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.72.4
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
-lglib-2.0
Run-time dependency glib-2.0 found: YES 2.72.4
Pkg-config binary for 1 is cached.
Determining dependency 'gio-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion gio-2.0` -> 0
2.72.4
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags gio-2.0` -> 0
-pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs gio-2.0` -> 0
-L/usr/lib/x86_64-linux-gnu -lgio-2.0 -lgobject-2.0 -lglib-2.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs gio-2.0` -> 0
-lgio-2.0 -lgobject-2.0 -lglib-2.0
Run-time dependency gio-2.0 found: YES 2.72.4
Pkg-config binary for 1 is cached.
Determining dependency 'gtk4' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion gtk4` -> 0
4.6.6
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags gtk4` -> 0
-mfpmath=sse -msse -msse2 -pthread -I/usr/include/gtk-4.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs gtk4` -> 0
-L/usr/lib/x86_64-linux-gnu -lgtk-4 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgraphene-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs gtk4` -> 0
-lgtk-4 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgraphene-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
Run-time dependency gtk4 found: YES 4.6.6
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program cargo found: YES (/home/john/.cargo/bin/cargo)
Configuring com.system76.CosmicAppLibrary.desktop.in using configuration
WARNING: Gettext not found, all translation targets will be ignored.

cosmic-applibrary/data/meson.build:6:0: ERROR: Can not assign None to variable.`

**Comment by jpierce-coder** [comment]
The error at the very end is referencing meson.build:6:0 
Below is snippet of file code:

![image](https://user-images.githubusercontent.com/70922864/212473154-652655a7-5cc9-449e-889e-0e246f9ff7e5.png)

**Comment by Drakulix** [comment]
@wash2 Since this is cosmic-applibrary failing here, are you aware of any build-time dependencies for the translation target?

> WARNING: Gettext not found, all translation targets will be ignored.

Looks like the gnu `gettext` tool is missing, I think that ships with `libintl`?

**Comment by wash2** [comment]
in the control file, `libgtk-4-dev` is probably what provides gettext from the applibrary control file, but maybe [intltool](https://packages.ubuntu.com/jammy/intltool) would be a better build dependency.
