### ISSUE TITLE
[Feature request] Wacom support

### ISSUE THREAD

**Issue by dklynx** [pop-os/cosmic-epoch#591]
I would like to request support for Wacom drawing tablets.
Personally I own a Wacom Intuos pro and it sort of works in the sense that it is reduced to a large touchpad, but the pen and buttons seem to be ignored by the system.
I believe this is due to Wayland issues?

**Comment by arkonbob** [comment]
Related Reddit discussion (I followed the instructions to install the staging version at the time, but like you @dklynx could only get touch support (in my VM)).
https://www.reddit.com/r/pop_os/comments/1dmaa3t/wacom_graphics_tablet_support_in_cosmic_de/

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic-settings/issues/141

**Comment by dklynx** [comment]
> Duplicate of [pop-os/cosmic-settings#141](https://github.com/pop-os/cosmic-settings/issues/141)


Ah! Thank you. I tried searching for anything wacom related, but it didn't show up.

**Comment by ricc3** [comment]
I posted the previous report in the wrong place so I'll link here ..

I have a Wacom Intuos ctl-490 graphics tablet [ data with tablet ].

system sees table:

```
sudo libinput debug-events
-event15  DEVICE_ADDED            Wacom Intuos S 2 Pen              seat0 default group6  cap:T  size 152x95mm
-event16  DEVICE_ADDED            Wacom Intuos S 2 Pad              seat0 default group6  cap:P buttons:4 strips:0 rings:0 mode groups:1
```
As far as I can see, the terminal records clicks as well as pen movement on the tablet, but I can't move the pointer either on the desktop or in any application. I checked in Blender downloaded from the website and in Xournal++

in the previous version of Pop (22.04) I had no problem with this

**Comment by abishekmuthian** [comment]
@dklynx Did you find a solution to get your pen working?

**Comment by dklynx** [comment]
@abishekmuthian No. From the looks of it. It is a Wayland issue. 
Now I'm a physiotherapist, not a programmer, but if I can help somehow resolve this, point me in the direction of how and I will try my best.
As stated I do have a Wacom Intuos pro and if I can do some testing of sorts, just say how.

**Comment by dklynx** [comment]
@abishekmuthian No. From the looks of it. It is a Wayland issue. 
Now I'm a physiotherapist, not a programmer, but if I can help somehow resolve this, point me in the direction of how and I will try my best.
As stated I do have a Wacom Intuos pro and if I can do some testing of sorts, just say how.

**Comment by frankenfr** [comment]
Hope this issue is solved in before the next release, there are more people using a tablet with pen then you can imaging, for example in my case able to cooperate with other engineers. 
Odd behavior:
OpenTabletDriver version 0.6.6.2 Info: Wacom CTL-6100WL Pressure: Enabled  

It's NOT in COSMIC yet

**Comment by VBtheFirbolg** [comment]
Is there a plan to have a GNOME like setting where I can edit what the different buttons do?

**Comment by CharlotteHutchins** [comment]
For the time being


https://github.com/pop-os/cosmic-comp/issues/1495

is how I got it to at least work some of the time
