### ISSUE TITLE
(b)top has misaligned cores

### ISSUE THREAD

**Issue by mhecker4891** [pop-os/cosmic-epoch#594]
![screenshot-2024-08-10-22-59-43](https://github.com/user-attachments/assets/6db2ac02-830c-4d7e-a6ca-df9d5a74c05d)

Wanted to inspect resources using btop, and noticed that cores 3 and 4 were appearing misaligned. Its nothing major, but figured it may be a simple fix. Specs: Lemp9 i7 running Fedora 40

**Comment by Riggs9715** [comment]
Same issue on btm (bottom) but I didn't make the connection to it being a cosmic issue. If it's happening on both though then there could be something there

**Comment by Drakulix** [comment]
cosmic-term bug: https://github.com/pop-os/cosmic-term/issues/275

**Comment by mmstick** [comment]
Closing as duplicate
