### ISSUE TITLE
Not an issue. But a question. 

### ISSUE THREAD

**Issue by rifqilubis** [pop-os/cosmic-epoch#597]
I'm still new in Linux world. But if i install cosmic DE Alpha LTS with pop os newest version. Does it will keep getting update to stable release or do i need download it again, every time there's major update?

**Comment by hfc2x** [comment]
Not a Pop developer, but yes, you should eventually get an update to the stable version when it comes out. That's usually how Ubuntu does it too, so this shouldn't be any different.

**Comment by rifqilubis** [comment]
Thanks. I really wanna try pop_os from the start.
