### ISSUE TITLE
[Bug] Whole desktop glitches.

### ISSUE THREAD

**Issue by vrihaspati110** [pop-os/cosmic-epoch#599]
![IMG_20240811_081115281](https://github.com/user-attachments/assets/ec26c810-9427-42ac-a6d2-67e180b6d0ff)

I was browsing store and tried to maximize it when it happened. It has happened before while browsing firefox as well and randomly in few other apps. It goes away when I lock the system with Super+esc. and log back in. 

My System Specs:
System : Lenovo Legion 5 Pro Gen 9 Laptop
OS : PopOs 24.04 cosmic Alpha
CPU: i9-14900hx
GPU: RTX 4070 8gb
Ram: 32 GB
Graphic Mode : Hybrid

Do let me know if you guys need anything else.
And Thank you for your hard work.

**Comment by peterkrull** [comment]
Are your actions leading to this bug similar every time you get it? Are you able to reproduce it on demand?

**Comment by vrihaspati110** [comment]
> Are your actions leading to this bug similar every time you get it? Are you able to reproduce it on demand?

No not really, it sometimes doesn't happen for hours. And I will be doing something else and this will happen suddenly. I can't reproduce it on demand, or I have not been able to figure out the requirement for this bug. Today, in morning, it happened twice in an hour that's when i decided to file the bug report, but since then it hasn't happend. Do let me know if you want some sort of log.
And Thank you for the reply.

**Comment by peterkrull** [comment]
Do you have the dock set to autohide when maximizing?

It is unlikely to show much in the logs if it is simply a calculation somewhere going wrong, but it is worth a try. If you know the approximate time it occurred, or it happens again, you could look in the system journal for cosmic-comp with:
```bash
journalctl --user --since 10:00:00 --until 11:00:00 _EXE=/usr/bin/cosmic-comp
```
which will show entries between 10 and 11 am, but you should try to change it to be when you believe it happened. You can also try replacing the last `_EXE=/usr/bin/cosmic-comp` part  with `| grep cosmic` to not just filter for cosmic-comp.

Try posting it here

**Comment by vrihaspati110** [comment]
Jesus Christ it produced a 60 mb txt file with this same error over and over

Aug 11 08:41:43 pop-os cosmic-comp[2070]: Failed to submit rendering: Failed to submit result for display

                                          Caused by:
                                              0: The underlying drm surface encountered an error: DRM access error: Page fli>
                                              1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card0")>
                                              2: Invalid argument (os error 22)
Aug 11 08:41:43 pop-os cosmic-comp[2070]: Failed to submit rendering: Failed to submit result for display

                                          Caused by:
                                              0: The underlying drm surface encountered an error: DRM access error: Page fli>
                                              1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card0")>
                                              2: Invalid argument (os error 22)

I can't submit it here. I had to open it in nano because it hangs the cosmic text editor as well.

**Comment by peterkrull** [comment]
Hmm, I have a bunch of entries like that as well, so I am not sure if it is related. I am not too familiar with the code base to comment on what could be wrong. I'm just trying to help in extracting potentially useful information

**Comment by vrihaspati110** [comment]
Thank you peter.. I did not know that command. Do you anymore commands which can help me to give more info on the subject?

**Comment by leviport** [comment]
I believe this is a duplicate of https://github.com/pop-os/cosmic-comp/issues/499

**Comment by vrihaspati110** [comment]
> I believe this is a duplicate of [pop-os/cosmic-comp#499](https://github.com/pop-os/cosmic-comp/issues/499)

Oh yeah you are right, I will close it.
