### ISSUE TITLE
error: Recipe `build` failed on line 21 with exit code 2

### ISSUE THREAD

**Issue by TiredJay** [pop-os/cosmic-epoch#61]
2/3] Generating data/com.system76.Cos...und.metainfo.xml with a custom command
/usr/bin/make -C cosmic-comp all
make: Entering directory '/home/ja/cosmic-epoch/cosmic-comp'
cargo build --release
   Compiling x11-dl v2.20.1
   Compiling libseat-sys v0.1.7
error: failed to run custom build command for `libseat-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/home/ja/cosmic-epoch/cosmic-comp/target/release/build/libseat-sys-b408b077d67a296e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBSEAT_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBSEAT_STATIC
  cargo:rerun-if-env-changed=LIBSEAT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "libseat"` did not exit successfully: exit status: 1
  error: could not find system library 'libseat' required by the 'libseat-sys' crate

  --- stderr
  Package libsystemd was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libsystemd.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'libsystemd', required by 'libseat', not found
  ', /home/ja/.cargo/registry/src/github.com-1ecc6299db9ec823/libseat-sys-0.1.7/build.rs:30:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:27: all] Error 101
make: Leaving directory '/home/ja/cosmic-epoch/cosmic-comp'
error: Recipe `build` failed on line 21 with exit code 2``

**Comment by Drakulix** [comment]
You are missing dev-packages for `libseat` and `libsystemd` on your system.
