### ISSUE TITLE
Starting a game with steam in fullscreen not using full display

### ISSUE THREAD

**Issue by N0m4n904** [pop-os/cosmic-epoch#615]
I have 2 1920x1080 displays and one 3440x1440 display. When I run a game like GTA-V on the 3440x1440 display it just renders on the top left corner with a resolution of 1920x1440. so not the resoultion of the monitor the window is placed in

**Comment by 0xFFFFFFFFFFFFFFFFFF** [comment]
This issue still persists within Alpha 6 and thus should be reopened. Using two displays, my games will also use the maximum resolution of my smallest display. As a workaround, you can disable the smaller display and enable it again after starting the game.
