### ISSUE TITLE
[BUG] all shortcut in system category are not working 

### ISSUE THREAD

**Issue by Sir-Thom** [pop-os/cosmic-epoch#617]
All shortcut does not do what they should do in the system section for example Super + A  does not open the app library , 
Super + /  does not  not open the launcher , etc ...  Also the shortcut in Desktop/Desktop and Panel does also not work .

**Comment by Sir-Thom** [comment]
OS: openSUSE Tumbleweed 
Architecture : x86_64
Kernel Version : 6.10.3-1-default 
I am using it on my laptop  a Lenovo Legion 5.  I try to do the shortcut via the build in  keyboard and also via  keyboard plug via the usb port of my laptop. The cosmic setting are pretty much the default one. I do not know if this could help but I also have KDE install.  Also if there is some place where I could get some logs please tell me And I will send them here.

**Comment by mmstick** [comment]
You may want to ask the openSUSE maintainer.
