### ISSUE TITLE
Not enough permissions to move files

### ISSUE THREAD

**Issue by dreampop602** [pop-os/cosmic-epoch#619]
This is replicable on all machines all the time. Try moving a file into a folder using the terminal or the file explorer. An error will appear saying you don't have enough permissions to do that 
![screenshot-2024-08-11-18-34-57](https://github.com/user-attachments/assets/90a08b8e-8e54-41e5-83f4-19151733e0e1)

Reported on PopOs Alpha 1 Intel

**Comment by igeljaeger** [comment]
show the file paths with ls -alhr and check the permissions for the path(s). Edit permissions with "sudo chown -R user:group path" and "sudo chmod -r 765 path" and it should work. This isn't related to cosmic.

**Comment by mmstick** [comment]
Doesn't appear to be related to COSMIC
