### ISSUE TITLE
Full screen video sometimes crashes DE

### ISSUE THREAD

**Issue by jasonwitty** [pop-os/cosmic-epoch#621]
Intermittently opening a video full screen from within applications such as slack or brave will crash entire DE, cntrl-alt-f3 allows me to exit so I assume only the DE has crashed.  This was occurring 100% of the time on a previous release of cosmic before the alpha but on the newest alpha this only happens sometimes.

---

OS    ➜  Garuda Linux x86_64Linux 6.10.3-zen1-2-zen
1996 (pacman)
fish 3.7.1
cosmic-comp (Wayland)
BeautyLine [Qt], Papirus-Dark [GTK2/3]
Bibata-Modern-Ice (24px)
alacritty 0.13.2
 FiraCode Nerd Font Mono (12pt)
12th Gen Intel(R) Core(TM) i9-12900KF (1z
NVIDIA GeForce RTX 2080 SUPER @  GHz
3.94 GiB / 31.15 GiB (13%)
0 B / 31.15 GiB (0%)
179.16 GiB / 953.57 GiB (19%) - btrfs
2560x1440 px @ 143.869 Hz - 600x340 mm ()
2560x1440 px @ 143.869 Hz - 600x340 mm ()

--

just as a note, i ran into this issue again and verified that if i cntrl-alt-f3, open btop and kill recent brave processes, then contrl-alt-f1 back into cosmic DE i am able to recover from this crash without seemingly any other symptoms. perhaps its just the maximize animation that is causing the crash.

**Comment by nathanroark** [comment]
I can also report that I can replicate this 100% of the time when opening a video full screen on discord or from youtube in google chrome.

I am able to control my other displays fine when the freeze happens.

killing the process from the application that had the video (discord or all chrome processes) continues to have the frozen image from the frozen video still on the display

widows can be dragged onto the display with the frozen image but they appear to go under it making the display not able to be used until the system is restarted

the application can be restarted after being killed and works fine on other displays (as long as you dont full screen a video again)

---

OS: Pop!_OS 24.04 LTS x86_64
Kernel: 6.9.3-76060903-generic
DE: COSMIC
CPU: 12th Gen Intel i9-12900K (24) @ 5.100GHz
GPU: NVIDIA GeForce RTX 2080 Rev. A

**Comment by mmstick** [comment]
Have you tried installing the latest version of cosmic-comp that was released this morning?

**Comment by nathanroark** [comment]
I have not. I'll report back after I have tried that

**Comment by mmstick** [comment]
The update contains fixes for fullscreen X11 applications on NVIDIA graphics. It may also help to manually enable Wayland support in Chrome's settings to improve compatibility overall.

**Comment by nathanroark** [comment]
> Have you tried installing the latest version of cosmic-comp that was released this morning?

Yep, no longer experience those issues myself now. 

Would be interested if @jasonwitty is still experencing their issue or if this can be closed now

**Comment by jasonwitty** [comment]
i held my breath, checked all my open applications and tabs to make sure everything was saved, made sure i had no running scripts or updates in process. I remember thinking ok Im ready, but I wasnt ready yet, i took a quick sip of my coffee and paced across my room a few times, ran my fingers through my hair and now I was ready.

I opened up a new browser tab in brave and went to youtube, chose a video, closed my eyes and hit full screen, when i opened them video was playing full screen, i clicked to minimize it and try it again, still working, omg!

bug seems fixed, thanks all !

**Comment by Department-stack** [comment]
if it's fixed then you can close the issue
