### ISSUE TITLE
Game launcher doesn't load fully

### ISSUE THREAD

**Issue by igeljaeger** [pop-os/cosmic-epoch#625]
Basically doesn't show the "play" button to launch the game (I think it's electron based?). 
Works on KDE Wayland without issues. I'm on 24.04.

Example screenshot:
![screenshot-2024-08-11-22-08-31](https://github.com/user-attachments/assets/1acf4f1f-f38c-4bfb-86be-cef9d419f343)

**Comment by mmstick** [comment]
Do you have more details on the game¸ launcher, and GPU configuration? Have you tried the latest cosmic-comp update from this morning?

**Comment by igeljaeger** [comment]
The game uses a closed source launcher by the developers and is installed via lutris with this script:
https://lutris.net/games/install/38671/view

Not sure what the exact difference of COSMIC to other Wayland Desktops is here or how that effects this game launcher, but it does. I always have to switch to KDE Plasma to play it because of this bug.

**Comment by igeljaeger** [comment]
Updated again today and still the same issue. I will post again if anything changes.

**Comment by ghost9742** [comment]
@igeljaeger  I had similar issue with a custom launcher. I have disabled the "13.3 Unknown-1 External Display" (not sure what that is, I don't have 2nd monitor) and then I dragged the display 0 from the screenshot to the middle (it was a bit to the right - causing the app to cut off).

**Comment by igeljaeger** [comment]
@ghost9742 I dont see any displays that don't exist. Seems like a you-thing in that case/unrelated to this. My assumption is theres an issue with how COSMIC displays certain windows still.

**Comment by igeljaeger** [comment]
Update: I can see all UI elements now with the newest version of COSMIC but I can't click on anything still:
![image](https://github.com/user-attachments/assets/e5ef3f1c-e301-4196-b4b2-7cc8d2572442)

**Comment by igeljaeger** [comment]
The launcher was now intractable and the game launch-able! Thank you very much for your hard work. I will close this issue now then. (popdev:master repo)
![image](https://github.com/user-attachments/assets/d160d14a-f5f2-499e-a914-b0a44a6caace)
