### ISSUE TITLE
Slightly specific problem with Dark Souls 3 Archthrones

### ISSUE THREAD

**Issue by igeljaeger** [pop-os/cosmic-epoch#630]
Dark Souls 3 itself launches without issues. Also the modded version does. But only if you remove the "launcher" it comes with entirely via the settings within the "archthrones_subsystems.toml":

[LaunchMenu]
enabled = false
do_updates = false

Otherwise it gets stuck there and just turns into a blackscreen. I am not sure why this is COSMIC specific as it does work on KDE Plasma Wayland without such issues. Also worked fine on Pop Desktop based on GNOME before. I am on 24.04 now so can't test that anymore though.

**Comment by mmstick** [comment]
What hardware do you have, and have you tried the latest cosmic-comp update released this morning?

**Comment by igeljaeger** [comment]
Hi @mmstick, I have updated to the latest version today. Same result. Here more screenshots for context:
![image](https://github.com/user-attachments/assets/5425ff46-a09b-4f61-aa09-80e6d41080ca)
when image is moved/untiled it becomes black:
![image](https://github.com/user-attachments/assets/72e912b9-4041-4dd5-a26f-fbe64ef3a17b)
My hardware is as follows:
![image](https://github.com/user-attachments/assets/49954ae7-a068-4b58-95d9-b2a14ef58fba)

**Comment by igeljaeger** [comment]
This has been fixed with the latest version via popdev:master repo! Thank you for your hard work! I'm closing this issue.
