### ISSUE TITLE
error[E0425]: cannot find value `PW_KEY_NODE_TARGET` in crate `pw_sys`

### ISSUE THREAD

**Issue by julanth** [pop-os/cosmic-epoch#64]
error[E0425]: cannot find value `PW_KEY_NODE_TARGET` in crate `pw_sys`
   --> /home/ja/.cargo/git/checkouts/pipewire-rs-60faa9e340c48539/3179b91/pipewire/src/auto/keys.rs:164:28
    |
164 | key_constant!(NODE_TARGET, PW_KEY_NODE_TARGET,
    |                            ^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `PW_KEY_NODE_NAME`
    |
   ::: /home/ja/cosmic-epoch/xdg-desktop-portal-cosmic/target/release/build/pipewire-sys-6cc6d6d8c2ce6e7a/out/bindings.rs:151:1
    |
151 | pub const PW_KEY_NODE_NAME: &[u8; 10usize] = b"node.name\0";
    | ------------------------------------------ similarly named constant `PW_KEY_NODE_NAME` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `pipewire` due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:33: xdg-desktop-portal-cosmic] Error 101
make: Leaving directory '/home/ja/cosmic-epoch/xdg-desktop-portal-cosmic'
error: Recipe `build` failed on line 26 with exit code 2
FAIL: 2

**Comment by Drakulix** [comment]
This is currently an upstream bug.
- https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/issues/55
- https://gitlab.freedesktop.org/pipewire/pipewire-rs/-/issues/57

**Comment by User8395** [comment]
I found a temporary solution. 
Comment out these lines:
```
key_constant!(NODE_TARGET, PW_KEY_NODE_TARGET,
    /// node wants to be connected to the target node/session
);
```
at ~/.cargo/git/checkouts/pipewire-rs-60faa9e340c48539/3179b91/pipewire/src/auto/keys.rs:164

**Comment by wash2** [comment]
@julanth This should be resolved in latest, is it alright if I close this issue?

**Comment by User8395** [comment]
Yeah, it's fixed. You can close it now.
