### ISSUE TITLE
Pop!_OS 2024 Sound issues

### ISSUE THREAD

**Issue by robertstrom** [pop-os/cosmic-epoch#655]
My first install of Pop!_OS 2024 was a VM. I played around with it a bit but then I decided to install it on my 2016 Dell XPS.The install went was without issue but I went to YouTube and found that I have no sound. I tried to play an MP3 file and also have no sound there. I ran lspci and I see that there is an Intel audio controller listed. There is a sound icon in the top bar (task bar? top panel?) and when I click on it all that is listed is "Dummy Output".Does anyone else have sound with the new Pop!_OS? If so, any thoughts on what I need to do to get sound working on my system?

Also - Bluetooth headphones work. Audio jack to wired headphones does not work.

```
$ inxi -aA
Audio:
Device-1: Intel 100 Series/C230 Series Family HD Audio
vendor: Dell XPS 15 9550 driver: snd_soc_avs v: kernel
alternate: snd_hda_intel bus-ID: 00:1f.3 chip-ID: 8086:a170 class-ID: 0403
API: ALSA v: k6.9.3-76060903-generic status: kernel-api
tools: alsactl,alsamixer,amixer
Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse
status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
4: pw-jack type: plugin tools: pactl,pw-cat,pw-cli,wpctl
```

![image](https://github.com/user-attachments/assets/b2b45b7e-78f5-4606-88d2-1996122f55b8)

**Comment by NahsiN** [comment]
This happened to me recently on my galp3 (Galago Pro) laptop. All of a sudden, my audio card was no longer detected even after restarting. For me, following some of the instructions in https://support.system76.com/articles/audio/ worked.

**Comment by robertstrom** [comment]
> This happened to me recently on my galp3 (Galago Pro) laptop. All of a sudden, my audio card was no longer detected even after restarting. For me, following some of the instructions in https://support.system76.com/articles/audio/ worked.

Thanks, I had already tried all of that

**Comment by robertstrom** [comment]
Updated information:

I have downloaded both the standard and the Nvidia ISO's and checked the sha256 hashes on both. I have done a full reinstall using both of the ISO builds and both still fail to have any audio. The available output is **Dummy Output**.

Here's where it gets interesting. On both of the installs when you boot up into the first GUI install screen you here the Pop!_OS **pop** sound and the audio shows an internal, built-in audio device.

So the audio works when the **Live Boot** from the USB is active but does not work after the OS has been installed.

**Comment by robertstrom** [comment]
FYI - I just updated the OS and the onboard audio devices are now seen and I am playing a YouTube video and it actually has sound now! Yeah!!! Thanks for getting this fixed. Not sure if I should close this issue or not.

**Comment by leviport** [comment]
Thanks for the update. If it's fixed, it should be closed. If it comes back, comment again and we can reopen it.

**Comment by robertstrom** [comment]
@leviport - what is extremely strange about this is that sound does not ever seem to work on boot. The system (Dell XPS 15 circa 2016 / Dell XPS 9550) is left up and running for many days at a time and at some point in time the sound starts working and seems to work until I reboot it. I will try to see if I can correlate it and or / se if there is any information in logs. Is there a particular place that I should look for log information on this? Is there a log collection utility like there is in the supported version of Pop!_OS?

Thanks!

**Comment by robertstrom** [comment]
UPDATE: Still not working on the 2016 Dell XPS. I was doing a bunch of other testing and I ended up installing Cosmic on a 2013 Mac Pro (not MacBook Pro, Mac Pro - the trashcan) and the onboard sound worked fine on the computer. Been updating the Dell XPS regularly and the sound is still flat out broken. The only sound devices I see is **Dummy Output** and **Monitor of Dummy Output**

Lack of sound is the only thing that keeps me from using the computer more frequently. Surfing around and then come across an article that has a video or need to watch some YouTube tech video, etc. Need to stop and go to another computer to do that.

Thanks!

**Comment by bhh32** [comment]
Pop!_OS 24.04 Alpha is working fine on my Dell XPS 15 2016. I’ve been
updating regularly as well. Running my web site and Immich photo backup off
of it for testing purposes. No audio issues.

**Comment by robertstrom** [comment]
@bhh32 - I wish that were the case! I have installed Cosmic from scratch twice and have had the same issue both times.

I imaged the Pop!_OS Cosmic install using Rescuezilla last night and reimaged the same Dell XPS system with an install of Pop!_OS 22.04 and the sound is working just fine so this is not a hardware issue.

I will play with this install of Pop!_OS 22.04 for a few days just to validate that further but I definitely do believe that the issue is a software issue on the Pop!_OS 24.04 side.

My Dell with Pop!_OS 22.04

![image](https://github.com/user-attachments/assets/f38532d9-f0dc-462b-891b-a772c8ffa60f)

**Comment by robertstrom** [comment]
This is what the **dmesg** output on the Pop!_OS 22.04 looks like (sound works in this Pop!_OS version as opposed to the 24.04 Cosmic version)


```
rstrom@pop-os:~/Downloads$ sudo dmesg -T | grep audio
[Mon Oct 28 17:09:19 2024] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC3266: line_outs=1 (0x17/0x0/0x0/0x0/0x0) type:speaker
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:      Headset Mic=0x18
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:      Headphone Mic=0x1a
[Mon Oct 28 17:09:20 2024] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12

```

**Comment by robertstrom** [comment]
UPDATE: I don't know if this information will help but here is an observation. I had left the laptop on with it just sitting there for a couple of days. Logged back into it today and found that that sound was working. There was a sound device. I captured the dmesg output to a file and then I rebooted. As suspected, the sound is not working. Dummy Output is all I see. I captured the dmesg output of that so that they can be compared. Hopefully these might have some clue(s) about what the issue is.

[dmesg_sound_working_2024-11-06.txt](https://github.com/user-attachments/files/17649895/dmesg_sound_working_2024-11-06.txt)


[dmesg_sound_not_working_after_reboot_2024-11-06.txt](https://github.com/user-attachments/files/17649899/dmesg_sound_not_working_after_reboot_2024-11-06.txt)

**Comment by robertstrom** [comment]
UPDATE: I also saved my existing Pop!_OS Cosmic install using Rescuezilla and did a fresh install from ISO of the Alpha 3 build and I had the exact same issue with the sound. No sound. Dummy output and input devices. But now I restored from a Rescuezilla backup form 10/28 and then updated the packages, rebooted and logged in and I have sound. I could almost guarantee that I will have no sound if I reboot.

**Comment by robertstrom** [comment]
Ran the command `sudo reboot` right after posted the comment above. Absolutely nothing else done. Rebooted and I have have no sound now.

**Comment by jkpjkpjkp** [comment]
I'm having sound issue as well. my fresh installed pop!os 24.04 does not detect asus motherboard sound card. the dual windows system on the same device works fine.

**Comment by robertstrom** [comment]
Updated to Alpha 4 and I am still having the issue. No sound for the **built-in** sound

 I can connect the Dell XPS 15 (9550)  to my Caldigit TS4 Thunderbolt dock and I have sound then.
 
 The sound issue is specifically with the internal, built-in sound. Behavior is still the same as it has always been. It will work very occasionally (worked right after I updated to Alpha 4) and  stopped working after I rebooted).

Posting some information that may have already been posted. Posting again to put all of the info here.

```
rstrom@pop-os:~$ lspci -v | grep -i audio
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31) (prog-if 80)
```

```
rstrom@pop-os:~$ lsmod | grep snd_hda
snd_hda_codec_hdmi     98304  0
snd_hda_codec_realtek   200704  0
snd_hda_codec_generic   122880  1 snd_hda_codec_realtek
snd_hda_scodec_component    20480  1 snd_hda_codec_realtek
snd_hda_ext_core       32768  2 snd_soc_avs,snd_soc_hda_codec
snd_hda_intel          61440  0
snd_intel_dspcfg       36864  2 snd_soc_avs,snd_hda_intel
snd_hda_codec         204800  6 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_codec_realtek
snd_hda_core          139264  8 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_codec_realtek
snd_hwdep              20480  1 snd_hda_codec
snd_pcm               192512  8 snd_soc_avs,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_compress,snd_soc_core,snd_hda_core,snd_pcm_dmaengine
snd                   143360  16 snd_ctl_led,snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi
```

```
rstrom@pop-os:~$ lspci -nnk | grep -A2 Audio
00:1f.3 Audio device [0403]: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller [8086:a170] (rev 31)
	Subsystem: Dell XPS 15 9550 [1028:06e4]
	Kernel driver in use: snd_soc_avs
```

```
rstrom@pop-os:~$ lspci -v | grep -i audio
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31) (prog-if 80)
```

screenshot of **pw-top** command results

This screenshot was taken while connected to the Caldigit TS4. Sound output works to both the Cadigit (which has some Logitech speakers connected to it) and the Jabra Engage 75 headset. 

So, sound fundamentally works, but only on external devices. As previously posted, I have installed a few other Linux operating systems (including Pop!_OS 22.04) and the internal sound device works fine on those OS installs.


![image](https://github.com/user-attachments/assets/2a95476a-f8f8-4a86-b007-13187a8a4648)

**Comment by robertstrom** [comment]
I tried running through these troubleshooting steps ... no luck. The sound still periodically works. There seems to be no rhyme or reason to whether it works or not. I have played with some settings in the BIOS and that has not made any difference. Just to clarify again the sound issue is only with the internal / onboard sound. External sound always seems to work. Link to the results of the `alsa-info` command

https://alsa-project.org/db/?f=e2401eef98f9e079ef86956497de726bdab87ac0

**Comment by jkpjkpjkp** [comment]
i fixed my issue by simply resetting all sound settings
```bash
systemctl --user restart wireplumber pipewire pipewire-pulse
rm -r ~/.config/pulse
rm -r ~/.local/state/wireplumber
```

**Comment by robertstrom** [comment]
It looks like I was finally able to get the sound to work consistently (so far though at least 5 combined instances of reboots and power offs).

What I saw in this screenshot of the results of the `journalctl -g audio` command run on my machine (and a post about blacklisting in an Arch forum - [[SOLVED] Audio Issues on Dell XPS 15 9560 (Intel i7-7700HQ)](https://bbs.archlinux.org/viewtopic.php?id=294655)) is what pointed me to what the problem might be

![Image](https://github.com/user-attachments/assets/0b5cb446-c252-4147-abaf-9fddccef58c2)

I honed in on these lines in the output of the `journalctl -g audio` command


```
Feb 01 12:36:23 popos-cosmic kernel: snd_soc_avs 0000:00:1f.3: ASoC: error at snd_soc_component_probe on hdaudioB0D0-platform: -2
Feb 01 12:36:23 popos-cosmic kernel: avs_hdaudio avs_hdaudio.0: ASoC: failed to instantiate card -2
Feb 01 12:36:23 popos-cosmic kernel: avs_hdaudio avs_hdaudio.0: probe with driver avs_hdaudio failed with error -2
```

Then I edited the `/etc/modprobe.d/blacklist.conf` file, adding the line shown below:


```
blacklist snd_soc_avs
```

The sound is still working after several reboots. I am hopeful since that has not happened before. The output of the  `journalctl -g audio` command also gives me hope since I can clearly see the multiple reboots and do not see the audio errors in any of those reboots after making this change.


![Image](https://github.com/user-attachments/assets/6155ec9a-39b5-4f67-abea-c1f83f42b65e)

**Comment by robertstrom** [comment]
Unfortunately the saga continues.

Everything that I stated in the last post above is still true with one major caveat.

I left the computer on last bight and came back to resume watching a video and the sound was not working. I still had a sound device (not a Dummy Output like I always used to have) but there was no sound (using Firefox and watching a video on YouTube).

I tried a fix that @jkpjkpjkp mentioned above and that seems to work occasionally but is not anywhere near a reliable fix.

The problem seems to be whenever I move to another application or even change focus to a different tab in Firefox. As soon as I do that the sound output stops.

I know that this is an Alpha release and I know that this is probably not the highest priority but honestly, sound seems like a pretty basic requirement to me and the problem has existed since August.

Prior to these two posts I have been running either Debian 12 with KDE or Manarjo with KDE on this same Dell computer for the past two weeks or. Zero ... Zero sound issues with either of those. The problem is definitely not with the hardware.

![Image](https://github.com/user-attachments/assets/1932faaf-0503-4597-958b-ad19ce3d0b65)

**Comment by dougkeiller** [comment]
Sound works well.

However, randomly it seems, a regular beep starts playing. Muting doesn't stop it. However, if I increase volume, then mute, the beeping stops. 

I use my Cosmic DE PopOS daily, and this started happening last week, and happens about once/day.

![Image](https://github.com/user-attachments/assets/58c0eb3a-73ac-410d-aae8-b9d9a8f8d97b)

**Comment by robertstrom** [comment]
No sound at all now except for when using Bluetooth headset


![Image](https://github.com/user-attachments/assets/2f0b1834-aebc-44e1-a25a-2d2966626035)

**Comment by VHRanger** [comment]
Just posting this here for posterity:

I had an issue (pop os 24 cosmic DE) with a usb-c DAC where changing the output profile to `Digital Surround 5.1 (IEC958/AC3)` would corrupt wireplumber. It would make anything except the speakers not work. The normal `analog output` works, and the `Digital Stereo (IEC958) Output` works as well.

The fix is like @jkpjkpjkp said, reset wireplumber:

```bash
rm -r ~/.local/state/wireplumber
```

**Comment by awalvie** [comment]
@VHRanger that was the fix for me too! Thanks!
