### ISSUE TITLE
Right-click desktop doesn't show option for Settings > Displays

### ISSUE THREAD

**Issue by aarongerber** [pop-os/cosmic-epoch#676]
This is so hardwired into my muscle memory my brain assumed the OS was locked up. After literally a minute of waiting, and clicking, I tried to hit the settings button. Please add this in.

**Comment by mbacch** [comment]
In addition, I think it would be good to consider some of the other defaults that typically show up when right clicking a desktop. For example:

- Open Terminal
- Change Background...

**Comment by Department-stack** [comment]
im kind of 50/50 on this

**Comment by aarongerber** [comment]
I can't see a downside to structuring a UI so that those coming from other popular UIs (Windows and Mac) can find what they are wanting easily. Obviously we need to limit the context menu to relevant items. Terminal is a little odd for the desktop for me, but if it has a place in other OSes then maybe. It would be nice to have a place where users could dump extra items into Context for the File Manager and the Desktop.

**Comment by Department-stack** [comment]
This feature is already added and the issue can be closed
