### ISSUE TITLE
Settings > Desktop > Appearance > Changing settings freezes UI

### ISSUE THREAD

**Issue by aarongerber** [pop-os/cosmic-epoch#677]
When I attempt to change appearance settings, the entire UI freezes temporarily. This includes Style, Window Management Settings, and probably more. 

I am running PopOS COSMIC DE in Virt-Manager, but with GPU enabled: 
- Display Spice:  Spice server, none, OpenGL (Intel Corp) 
- Video VirtIO
- qemu-guest-agent installed

**Comment by peterkrull** [comment]
This is a known issue: [cosmic-settings/474](https://github.com/pop-os/cosmic-settings/issues/474)
