### ISSUE TITLE
All the XF86Audio keys don’t work on DELL G3 3500 Laptop

### ISSUE THREAD

**Issue by CarameowCookie** [pop-os/cosmic-epoch#690]
My laptop's `XF86Audio*` keys (including 3 volume controls, 3 playback controls) do not work.

In contrast, the 2 `XF86MonBrightness*` keys work fine.

OS: Arch Linux x86-64

**Comment by CarameowCookie** [comment]
However, all the `XF86*` keys work well in Pop!_OS 24.04.

**Comment by Sustolic** [comment]
Similar issue on my arch install as well (although I haven't tried Pop!_OS 24.04 yet)

All of my media keys on my Keychron Q1 MAX keyboard including the volume wheel do not seem to work, minimal installs of gnome and kde work perfectly fine so I am not sure if it is an issue with the AUR missing a dependency or package that is required for media keys to work or if it's another issue.

All of cosmic-epoch's core components and apps are updated to the latest git build.

**Comment by alphabitserial** [comment]
I updated my COSMIC install to the latest git commits, and XF86Audio keys are working on my Arch Linux installation now!
