### ISSUE TITLE
changing the timezone freezes COSMIC Settings

### ISSUE THREAD

**Issue by daJ0nas** [pop-os/cosmic-epoch#698]
Changing the Timezone in COSMIC Settings freezes the application. The change can't be applied.

OS: Pop!_OS 24.04 Alpha
Hardware: Lemur Pro 10

**Comment by mmstick** [comment]
Did you install system updates?

**Comment by irishgordo** [comment]
fwiw, I didn't encounter this last night when I:
1. [downloaded the nvidia iso](https://iso.pop-os.org/24.04/amd64/nvidia/9/pop-os_24.04_amd64_nvidia_9.iso)
1. performed a full install + erase on an nvme
1. did an apt update & apt upgrade
1. rebooted
1. changed the timezone from UTC -> America/Los_Angeles

**Comment by daJ0nas** [comment]
System is up to date. The timezone changed after multiple reboots...
