### ISSUE TITLE
[2 Feature requests] Notification when low on battery; battery icon shows percentage

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#700]
I have repeatedly had my system shutdown because I was not aware that the battery was low. It would be nice to have a visual notification of sorts as the current battery applet isn't very percise and is very easy to miss. It would also be nice for the battery applet to show the percentage if possible; even be colored on top of that!

**Comment by pagmatt** [comment]
+1 regarding the possibility of showing the battery percentage

**Comment by mmstick** [comment]
There are sound alerts that play when low and critical

**Comment by Department-stack** [comment]
does it work for bluetooth devices? my laptop speakers are present but isn't properly recongized by the kernel and I dont know how to complie it to do so. ( I am not interested in regularly modifing my kernel because of fedora's regularly updating kernels anyhow) unless if there is a way to persist it. anyhow i believe sound simply isn't enough to notify users about a low battery percentage.

**Comment by Department-stack** [comment]
moved to https://github.com/pop-os/cosmic-applets/issues/617
