### ISSUE TITLE
[BUG] High performace mode isn't respected

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#707]
Expected behavior: When clicking on the "high performance mode" in the battery applet it should change and stay that way until explictly undone by the user.

Actual behavior: When I do this, the applet does change, however once i close out of the applet it resets back to either "battery" or "balanced" this also applies in settings.

Steps to reproduce: Try changing to "performace". I would of had expected to be already be an issue as it would seem easy to spot. So i am not sure if this is only a "me" thing or what.

Potential conflicts: I do have tlp installed. So this could be a reason behind this behavior.

Distribution: Fedora KDE 40

Desktop environment: COSMIC

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Network adapter: Qualcomm Wireless-AC 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo, non-vPro

Laptop model: HP Chromebook 11A G8 EE

**Comment by Department-stack** [comment]
Actually, when pressing "high performance" in settings nothing happens. regaurdless if it is plugged in or not

**Comment by wild-fruits** [comment]
same problem

**Comment by Department-stack** [comment]
moved to https://github.com/pop-os/cosmic-applets/issues/615
