### ISSUE TITLE
`cosmic-launcher` not marked as executable possibly being the reason cosmic session crashes

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-epoch#71]
```
thread 'main' panicked at 'failed to start launcher: Process(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })': src/main.rs:124
```
^ the important part of the back-trace

**Comment by Vixea** [comment]
I think this is where the issue is coming from:
https://github.com/pop-os/cosmic-launcher/blob/ee93fdd4b217f93a3c4cb5393e2b887a9dfc3e7c/justfile#L44

**Comment by Vixea** [comment]
After making it an executable, I try to log in with COSMIC I receive Failed to submit buffer for display.
https://pastebin.com/6X4APtzE

**Comment by Drakulix** [comment]
> After making it an executable, I try to log in with COSMIC I receive Failed to submit buffer for display. https://pastebin.com/6X4APtzE

That log looks heavily truncated, could you upload a full log of cosmic-comp please? While the error is clear, there is no way to infer what caused it with the limited informations. thanks!

**Comment by Vixea** [comment]
Great now it works all of a sudden good thing I uploaded a log but it contains a lot of junk in it
https://drive.google.com/file/d/1ONcwSvt3gnRhoyDKXfVbU-CA19au6DrJ/view?usp=drivesdk
Also I can never seem to get the task bar to work or whatever it's called

**Comment by Drakulix** [comment]
> Great now it works all of a sudden, good thing I uploaded a log but it contains a lot of junk in it https://drive.google.com/file/d/1ONcwSvt3gnRhoyDKXfVbU-CA19au6DrJ/view?usp=drivesdk 

Thanks! Unfortunately still not enough to really tell, what was going on.
Would you be able to upload a log now from the working state? Maybe there is some meaningful difference.

> Also I can never seem to get the task bar to work or whatever it's called

You probably mean [`cosmic-panel`](https://github.com/pop-os/cosmic-panel)?

The log does contain one error related to that:
```
cosmic-applet-graphics/src/window.rs:124] err = MethodError(
     OwnedErrorName(
         ErrorName(
             Str(
                 Owned(
                     "org.freedesktop.DBus.Error.ServiceUnknown",
                 ),
             ),
         ),
     ),
     Some(
         "The name com.system76.PowerDaemon was not provided by any .service files",
     ),
     Msg {
         type: Error,
         sender: UniqueName(
             Str(
                 Borrowed(
                     "org.freedesktop.DBus",
                 ),
             ),
         ),
         reply-serial: 2,
         body: Signature(
             "s",
         ),
     },
 )
```
 
But I believe that is not critical, I also don't have the power-daemon installed on my system and I can launch the graphics-applet just fine despite the error.

Can you be a bit more specific what you mean with "can never seem to get *it* to work"? Does it not start? What happens if you run `cosmic-panel` from the terminal?

@wash2 Might be able to help you, maybe she can find another error in that log regarding the panel?

**Comment by Vixea** [comment]
I'm not sure if the reason for the panel not working will be in that log as that for when cosmic wasn't uploading buffers without fail I can give you an updated log for that.

Not working as in it's appears for a second with no apps on it before going hidden and never really showing up again even with what I think you're supposed to do like on many other systems (move the cursor to the bottom of the screen to make it visible again

**Comment by hojjatabdollahi** [comment]
I think Vixea Is talking about cosmic-app-list.
The config by default has no apps on it and it auto hides.

**Comment by Vixea** [comment]
https://drive.google.com/file/d/1N1_-yUqIChPwd4opUCx4sy8pkwSihOkL/view?usp=sharing

**Comment by Vixea** [comment]
> I think Vixea Is talking about cosmic-app-list. The config by default has no apps on it and it auto hides.

where can I find the config file for this or do I have to create one?

**Comment by wash2** [comment]
Right, I assume the top panel is working alright, but it's the dock / bottom panel that is hiding and not reappearing for you?

It should reappear if you move your cursor to the very bottom center of your screen, but if there are no apps on it, it may be quite small.

**Comment by Vixea** [comment]
yes it doesn't reappear, also is there an app to search for apps to launch them or no?

**Comment by wash2** [comment]
> yes it doesn't reappear, also is there an app to search for apps to launch them or no?

Yes, there is a launcher and an app-library. The default shortcuts for them are 'Super + /' and 'Super + a' respectively

**Comment by Vixea** [comment]
Actually it does it's just so small you have to be in just the right area 😅

**Comment by Vixea** [comment]
> Yes, there is a launcher and an app-library. The default shortcuts for them are 'Super + /' and 'Super + a' respectively 

Both do not seem to do anything

**Comment by wash2** [comment]
> Actually it does it's just so small you have to be in just the right area sweat_smile

Ok, I'm glad to hear that :smile: ! If you open some more apps, the area will get larger (not all apps support the protocol properly yet so some may not show up in the dock).

**Comment by Drakulix** [comment]
> > Yes, there is a launcher and an app-library. The default shortcuts for them are 'Super + /' and 'Super + a' respectively
> 
> Both do not seem to do anything

I am actually not sure, cosmic-comp currently installs the default config file somewhere and without a config file, there are no keybindings.
You can try copying the [default config](https://github.com/pop-os/cosmic-comp/blob/master_jammy/config.ron) from the repository to `/etc/cosmic-comp/config.ron`.

**Comment by Drakulix** [comment]
> https://drive.google.com/file/d/1N1_-yUqIChPwd4opUCx4sy8pkwSihOkL/view?usp=sharing

Also thanks for the second log, but they are almost identical, one just fails and the other.. doesn't. If you ever find a way to reproduce your initial error, I would be very interested in hearing about it. But for now I am going to assume it was a weird fluke.

**Comment by hojjatabdollahi** [comment]
Yes. You need to manually copy the config file. Also since the pop up menu for the icons in the dock open below the icons, which is outside of the screen, I had to move the dock to the left side of the screen to be able to right-click on an icon and pin it to the dock.

**Comment by wash2** [comment]
> Also since the pop up menu for the icons in the dock open below the icons
Ya this is a bug that I've been meaning to look more into for a while now :sweat_smile:

**Comment by Vixea** [comment]
We'll the original issue is solved, though I can't seem to launch the launcher once a app has been opened is that expected?

**Comment by Vixea** [comment]
I should add that it's Fullscreen and or maximized application but I'm assuming you know that so I'm going to close this issue.

**Comment by wash2** [comment]
> I should add that it's Fullscreen and or maximized application but I'm assuming you know that so I'm going to close this issue.

If I had to guess, I'd say that maybe the launcher is hidden behind the full screen app, but I'll double check, thanks. 

Btw @hojjatabdollahi the popup issue you mentioned is fixed in latest cosmic-comp, and I'll update cosmic-epoch to include the fix soon :)
