### ISSUE TITLE
[BUG] cosmic app store sometimes doesn't show updates however discover does

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#715]
Expected behavior: shows updates

Actual behavior: sometimes doesn't show updates

Distribution: Fedora KDE 40

Desktop environment: COSMIC

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Network adapter: Qualcomm Wireless-AC 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo, non-vPro

Laptop model: HP Chromebook 11A G8 EE

**Comment by git-f0x** [comment]
This is likely because cosmic-store doesn't yet support system-installed Flatpaks, which are the default in Fedora.

**Comment by Department-stack** [comment]
that would explain things as I mainly use flatpak. But there has been a couple of times where discover would show updates for cosmic and the cosmic app store wouldn't

**Comment by Department-stack** [comment]
Haven't encountered this issue since so I will close it
