### ISSUE TITLE
[2 BUGS] trying to open btop does nothing; (works in konsole) btop graphical issues on COSMIC terminal

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#716]
Expected behavior: btop should open when clicked on from the application menu

Actual behavior: doesn't do anything

Steps to reproduce: install btop on fedora, and try to open it via the launcher

BUG 2: heres the photo of what happens when running btop on cosmic terminal:
![screenshot-2024-08-16-01-38-16](https://github.com/user-attachments/assets/9b265eab-977b-47e1-8177-94d1c0db12f7)

Distribution: Fedora KDE 40

Desktop environment: COSMIC

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Network adapter: Qualcomm Wireless-AC 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo, non-vPro

Laptop model: HP Chromebook 11A G8 EE

**Comment by Department-stack** [comment]
I just saw that btop graphical issues has already been noticed; but I will still leave this up because I dont think that the btop launching bug has been reported

**Comment by AMoonRabbit** [comment]
If you check the desktop file used for launching btop from the application menu, can you execute the exec command in terminal and does it open? I am having issues with another app where the desktop file does not do anything at all despite the exec path working fine in terminal.

**Comment by Department-stack** [comment]
launching it from /usr/share/applications/ works but the issue with the application menu remains

**Comment by leviport** [comment]
Pop and Ubuntu's btop packages don't have .desktop files. Can you please share the contents of your .desktop file?

**Comment by Department-stack** [comment]
i am using fedora

**Comment by Department-stack** [comment]
[Desktop Entry]
Type=Application
Version=1.0
Name=btop++
GenericName=System Monitor
GenericName[it]=Monitor di sistema
Comment=Resource monitor that shows usage and stats for processor, memory, disks, network and processes
Comment[it]=Monitoraggio delle risorse: mostra utilizzo e statistiche per CPU, dischi, rete e processi
Icon=btop
Exec=btop
Terminal=true
Categories=System;Monitor;ConsoleOnly;
Keywords=system;process;task

**Comment by leviport** [comment]
>i am using fedora

Yeah, you mentioned that

> Exec=btop

I think this is the reason. In Gnome, this launches a terminal, which launches btop or htop. I think the bug is that COSMIC DE isn't launching terminals for these CLI apps.

Since this is a broader issue that affects more than btop++, I'm going to close this one and open a fresh issue to track that bug. This thread is also a bit messy, so that will help make it an easier bug to track in general.
