### ISSUE TITLE
[Community request] brief changelog or update notes for each pushed update

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#719]
Doesn't have to be detailed. i am not technically inclined enough to go through pull requests and read them. I have tried and i dont understand anything that is being changed. I also think this would help with documentation, resolving duplicate bug or feature requests when something is already added but a user is unaware about it

**Comment by vrihaspati110** [comment]
Yes, I will really help a lot.

**Comment by mmstick** [comment]
This is already done here: https://github.com/pop-os/repo-release/
See this PR as an example: https://github.com/pop-os/repo-release/pull/359
