### ISSUE TITLE
alt tab doesn't switch app

### ISSUE THREAD

**Issue by codegod100** [pop-os/cosmic-epoch#745]
when I'm in an app and hit alt-tab it goes to previous app, but if I do it again it stays on the same app. e.g. chrome -> alt-tab -> some app -> alt-tab -> same app

**Comment by codegod100** [comment]
Duplicate of https://github.com/pop-os/cosmic-launcher/issues/135

**Comment by Department-stack** [comment]
I thought this was intended behaviour. glad to see that this is not the case and it will be fixed
