### ISSUE TITLE
Cant tab back into Lunar client when its maxamized

### ISSUE THREAD

**Issue by TacticalNuke974** [pop-os/cosmic-epoch#754]
I don't know if it's just the minecraft launcher Lunar Client

but when I open it and maximize it, if I accidentally tab out with my mouse on another monitor or with alt tab it's impossible to tab back in without closing the process and restarting lunar client

When I alt tab back into maxamized unar client it appears on the screen for an instance and then shrinks and disapears

**Comment by Department-stack** [comment]
does it still happen even if its not maximized?

**Comment by TacticalNuke974** [comment]
No, it behaves normally when not maxamized, it's just when it is maxamized and I tab back to it it tries to pop up on screen as if it wasn't maxamized and then shrinks and disapears.

**Comment by TacticalNuke974** [comment]
https://github.com/user-attachments/assets/98d10f4d-ac30-4aa1-a4cc-02f89661ed84

this is a video of me showing it off

**Comment by Drakulix** [comment]
This is most likely another minimize-on-focus issue various X11 client seem to have .
