### ISSUE TITLE
[Bug] Random reboots.

### ISSUE THREAD

**Issue by nevdelap** [pop-os/cosmic-epoch#755]
I don't expect much if anything to be done with this since it is alpha, but in case anyone else sees the issue I'm going to add some info, in case it is helpful down the line.

- i3 Manjaro 16GB ASUS laptop with 32GB swap, has never had a random reboot since I purchased it in July 2022.
- I was using cosmic-de from the 10th of August, (having installed it with the instructions [here](https://wiki.archlinux.org/title/COSMIC)), without a reboot.
- Then I think it was Friday (16th of August) that it started random rebooting after I'd updated at the `cosmic-session-git` level, so I don't know what actually changed, if anything.
- My system is an AMD Ryzen 5700. AMD Ryzen has apparently been known for random reboots in Linux, though...
   - I've never had random reboots before in about two years of this machine being on and constantly used.
   - I've tried everything I could find about the known issues with Ryzen, but nothing helped.
   - I ran a pass of memtest86 and it was happy. (Didn't have time to run more.)
- A full reinstall didn't help.
- Before the reinstall it was 6.10.x kernel, after the reinstall it is Linux zen 6.9.12-1-MANJARO.
- The reboots happened under high load - rustc hammering all cores.
- And they happened under no load - computer locked and doing nothing at all.
- The random reboots where several times a day Friday, Saturday, Sunday, and after reinstalling Sunday. Maybe 15 times.
- Nothing in `journalctl` or `dmesg`. Sadly when I reinstalled I didn't keep the logs I'd captured, so I'll add an example (of there being nothing) the next time I log into Cosmic and get one.
- The random reboots happened with not much memory in use.
- I've had no random reboots since logging into i3 last night (Sunday), and using it all day today (Monday afternoon). I need to stay in i3 until Wednesday, then I'll switch back to Cosmic to see if I can find more info, and maybe run a long memtest.

**An update:** I switched back from i3 into Cosmic last night (Tuesday night), it's up to ~~16~~ ~~24~~ ~~48~~ 72 hours without any issues. The difference in what's running is in having had random reboots after a complete reinstall of the machine and the AUR `cosmic-session-git` version installed, vs having removed that and installed `cosmic` from the Arch repos. No idea what might have been released, or is different. So... :crossed_fingers:

**Comment by Drakulix** [comment]
How exactly does the random reboot manifest? Does the whole system crash and start again or does it shutdown properly before rebooting?

**Comment by nevdelap** [comment]
It's as if it the power were cut, nothing in journalctl when it happens, and then it restarts. The next time I'm running Cosmic and it happens, if it happens, I'll show the journalctl. I've removed the `cosmic-session-git` install in place of the `pacman -Sy cosmic` install that came out today.

**Comment by golanguage** [comment]
I use Pop-OS on a old ThinkPad E580 about 2 months.
Sometime it may sleep to frozen, reboot, and often fail to hibernate...
I know it bases on Ubuntu, but seem not includes kernel. Because when I switch Ubuntu, the system is stable. BTW I know Ubuntu test their release on Lenovo PC.

**Comment by Department-stack** [comment]
I have had this happen to me a couple of times too. Nearly the exact same as they have described

**Comment by nevdelap** [comment]
Apparently after uninstalling `cosmic-session-git` and installing `cosmic` I've not had the problem, though I've no idea if that is really what stopped it happening.

**Comment by nevdelap** [comment]
I'm going to close this off. Whatever was going on with my machine sorted itself out.
