### ISSUE TITLE
Right click does not work

### ISSUE THREAD

**Issue by malexous** [pop-os/cosmic-epoch#764]
I have the latest cosmic desktop available in Fedora 40. When i right click the touchpad nothing happens . When I tap the touchpad with two fingers it brings up the menu you would expect from right clicking. 

Right clicking with a mouse works

**Comment by Department-stack** [comment]
I had this issue too, when I updated for some reason the mouse/trackpad settings were changed. you can fix this in settings

**Comment by Drakulix** [comment]
Does your touchpad have a physical right button?

If not, then this might simply be a touchpad configuration issue. Take a look at cosmic-settings to configure right-click emulation.

**Comment by Department-stack** [comment]
@Drakulix you can close this issue
