### ISSUE TITLE
[BUG] "Battery" and "High Performance" mods are swapped

### ISSUE THREAD

**Issue by vvbogdanov87** [pop-os/cosmic-epoch#769]
Games have higher fps when I select the `Battery` mode than the `High Performance` mode.

![screenshot-2024-08-19-20-49-09](https://github.com/user-attachments/assets/15927e2b-d80a-4b35-b67f-ae456380ecd1)
![screenshot-2024-08-19-20-49-47](https://github.com/user-attachments/assets/d7d490e0-4b83-46ff-937f-0be84091534e)

System76 Lemur Pro (lemp13)

Could be related to https://github.com/pop-os/cosmic-epoch/issues/707

**Comment by jacobgkau** [comment]
Can you check the output of `system76-power profile` in a terminal while you have each mode selected?

On some hardware, battery mode actually allows greater performance (e.g. by avoiding throttling), so that would be a case of the modes needing to be tuned better for that hardware, but not an issue with the GUI having the modes swapped.

**Comment by vvbogdanov87** [comment]
@jacobgkau you are right. It is not a UI bug. `system76-power` shows the correct profile.
```shell
~ $ system76-power profile
Power Profile: Balanced
CPU: 9% - 100%, Turbo
Backlight acpi_video0: 0/19 = 0%
Keyboard Backlight system76_acpi::kbd_backlight: 0/255 = 0%
~ $
~ $ system76-power profile
Power Profile: Battery
CPU: 9% - 50%, No Turbo
Backlight acpi_video0: 0/19 = 0%
Keyboard Backlight system76_acpi::kbd_backlight: 0/255 = 0%
~ $
~ $ system76-power profile
Power Profile: Performance
CPU: 9% - 100%, Turbo
Backlight acpi_video0: 0/19 = 0%
Keyboard Backlight system76_acpi::kbd_backlight: 0/255 = 0%
```

**Comment by mmstick** [comment]
It may be that the firmware is giving priority to the CPU clock frequency at the expense of the GPU clock frequency. Balanced should have the best performance in games.
