### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by drazil100** [pop-os/cosmic-epoch#772]
Not sure where to put this but ever since I updated the pop alpha today I noticed that my CPU usage seemed unusually high at idle. Granted I AM on a Celeron so it's not like I had a whole lot of CPU to begin with but I do not recall my idle CPU ever being this high. 

It's possible I am dumb and just didn't notice it before updating but I am PRETTY sure that I had normal idle CPU usage before updating today or at the very least when I first installed the alpha. (I don't know if I have checked in a few updates)

![image](https://github.com/user-attachments/assets/cba0e8d2-b361-4d4a-bee3-41715248bcea)

Even if this isn't new I have not seen a system that uses over 60% of my Celeron at idle, and I am definitely not running anything besides stock cosmic. It uses 60% even from a reboot.

**Comment by Department-stack** [comment]
I am having this exact issue. 
![screenshot-2024-08-20-02-03-09](https://github.com/user-attachments/assets/f14348bf-4950-4fc1-9c9e-781fef04ec1c)

**Comment by git-f0x** [comment]
Should be fixed when pop-os/cosmic-applets#604 is merged.

**Comment by joshuamegnauth54** [comment]
Hi! Sorry about this issue. My last patch to `cosmic-applets` [contained a bug](https://github.com/pop-os/cosmic-applets/issues/607) that causes the time applet to eat up a lot of CPU time. I opened a patch to fix this issue, but for now you can kill the time applet.

**Comment by drazil100** [comment]
@joshuamegnauth54 what better way to kill time than to kill the time applet? xD

**Comment by Harry-W-Haines-III** [comment]
I have noticed an issue with excessive CPU usage on idle with Xwayland running.

**Comment by mmstick** [comment]
Fix will be in next repo-release

**Comment by Harry-W-Haines-III** [comment]
I will be watching for it as it just recently seemed to occur.
