### ISSUE TITLE
Cosmic DE high CPU usage

### ISSUE THREAD

**Issue by Barugon** [pop-os/cosmic-epoch#786]
Cosmic is using too much CPU when doing nothing. It's causing my laptop's fan to constantly run. Here's what System Monitor shows:
![screenshot-2024-08-21-21-55-53](https://github.com/user-attachments/assets/7a95fd3a-f07e-41a5-811e-4ad8868ad115)

Here's what System Monitor shows for the GNOME desktop:
![Screenshot from 2024-08-21 14-52-11](https://github.com/user-attachments/assets/cd5b8bac-795e-4b68-a894-facd4f4d25c3)

This is on Fedora 40.

**Comment by mmstick** [comment]
I heard that they hadn't released the cosmic-applets update yet. Make sure you have version [0d0a13a0627654ebd4f29f22da5eec7f09a22799](https://github.com/pop-os/cosmic-applets/commit/0d0a13a0627654ebd4f29f22da5eec7f09a22799)

**Comment by Department-stack** [comment]
I updated and the issue was fixed

**Comment by Barugon** [comment]
This seems to have been resolved. Closing.
