### ISSUE TITLE
[QaA] what does seatd dependency do?

### ISSUE THREAD

**Issue by soloturn** [pop-os/cosmic-epoch#79]
how does cosmic need seatd? i saw that sway, resp wlroots, needs seatd. gnome does not. there is a discussion on the arch linux bug tracker which kind of goes : seatd or polkit for sway:
https://bugs.archlinux.org/task/73547

(sorry to ask here, even it is not really a forum for such questions ...)

**Comment by Drakulix** [comment]
`seatd` as a daemon is not required by cosmic-epoch.

But one component `libseat` of said project is used in `cosmic-comp`. libseat provides an abstraction to connect to different session managers through a unified interface and safes compositors using it (like sway) the need to maintain the same code.

libseat can connect to `seatd` (if installed and active), but can also connect to `systemd-logind` (which is active by default on arch linux) or through the kernel interface via a tty.

I have not read the discussion on the arch linux bugtracker, but from what I understand arch linux only has a single seatd package. If you are not using the daemon component, a good chunk of it's contents remain completely usused on most systems. I would suggest to split the package into a `libseat`-package compositors can depend on and a separate `seatd` package, users can install, who choose to use the `seatd` session manager.
