### ISSUE TITLE
Zed - Unsupported GPU 

### ISSUE THREAD

**Issue by SlashScreen** [pop-os/cosmic-epoch#798]
When attempting to run the Zed editor, I get this error message:

![screenshot-2024-08-23-02-25-29](https://github.com/user-attachments/assets/429a3872-ad25-4bad-a2d7-ede1a48919be)

I checked, and I can in fact run vulkan on my intel integrated graphics. I remember a clause somewhere about software rendering; is this Cosmic issue, or a Zed issue?

**Comment by Drakulix** [comment]
This is an issue of your install/distribution. If there are vulkan drivers for your gpu, they aren't installed.

**Comment by SlashScreen** [comment]
I tested using `vulkan-tools`, and the cube was able to show up, so I should have vulkan drivers, no?

**Comment by Drakulix** [comment]
No, llvmpipe is a valid vulkan driver, even with zed complaining, but runs entirely on your CPU.

So you might be missing drivers for your specific gpu, which distro are you on?

**Comment by SlashScreen** [comment]
The Pop-os iso with cosmic from the website.

**Comment by Drakulix** [comment]
Please check, that `mesa-vulkan-drivers` is installed (though it really should be). If that is the case and you are still getting this issue, please post the full output of `vulkaninfo`.

**Comment by SlashScreen** [comment]
mesa-vulkan-drivers appears to be installed (at least APT says it is). Here's `vulkaninfo`:
[vkinfo.txt](https://github.com/user-attachments/files/16732888/vkinfo.txt)

**Comment by farhatizakaria** [comment]
I face the same issue, I've reported that to Zed 

https://github.com/zed-industries/zed/issues/16491

**Comment by SlashScreen** [comment]
Looks like that works. Thought it was a Cosmic issue, turns out it's a Zed issue!
