### ISSUE TITLE
Settings > Regions & Language is empty

### ISSUE THREAD

**Issue by blwtxc** [pop-os/cosmic-epoch#810]
(Alpha installed in KVM)

When I go to `Settings > Regions & Language`, I get an empty pane.

...and `COSMIC Screenshot` isn't working/does not open, otherwise I would have attached a screenshot :)

**Comment by git-f0x** [comment]
That page isn't yet implemented, and the screenshots not working is probably due to the VM.

**Comment by blwtxc** [comment]
@git-f0x Thanks for the info about the screenshot app and, yeah, I suspected that it's simply not implemented yet :)

**Comment by jkpjkpjkp** [comment]
is there a workaround to change system language post-installation?

**Comment by git-f0x** [comment]
The Regions & Language page has been implemented, so system language can be changed there.
If you're not on Pop, or not using the Fedora Copr, or the git builds on Arch, then it'll be available with Alpha 4 on November 28th.
