### ISSUE TITLE
[Feature suggestion] Optional desktop icons

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-epoch#820]
What it says in the title.

Right now, there's not an option to have desktop icons. I think it's probably the point of the COSMIC desktop to be clear of them, but some of us actually like having some icons back there, for example for mounted drives, trash, or similar. This is why it would be cool to have an option for whoever wants it (off by default, since it's what people have come to expect from GNOME).

**Comment by git-f0x** [comment]
Desktop icons are currently in the process of being implemented, though I'm not sure if it'll be possible to disable them.

**Comment by DavidHaltinner** [comment]
It appears to be implemented now, as after updating I now have desktop icons. But I cant find any way to disable them. This should be an optional feature as was originally suggested (many of us do not want them).
It is also showing my entire home folder, not the Desktop folder as expected, so it is quite a mess on the screen.

**Comment by git-f0x** [comment]
You might have a misconfiguration in a file. Check that XDG_DESKTOP_DIR in `~/.config/user-dirs.dirs` is set to use the Desktop folder.
If you don't want desktop icons, you can just remove everything in ~/Desktop.

**Comment by leviport** [comment]
Tracking desktop icons in https://github.com/pop-os/cosmic-files/issues/547
