### ISSUE TITLE
Cosmic is now in the official Arch repositories, need to update the README.

### ISSUE THREAD

**Issue by monomere** [pop-os/cosmic-epoch#829]
I might make a PR in an hour-ish!

**Comment by taivlam** [comment]
I believe you can close this, as this info is already in the topmost README - this [section](https://github.com/pop-os/cosmic-epoch?tab=readme-ov-file#installing-on-arch-linux) specifically.

**Comment by monomere** [comment]
yes, I unfortunately forgot about this 😔

thank you!
