### ISSUE TITLE
[FEATURE REQUEST] An option to hide all title bars

### ISSUE THREAD

**Issue by psimovec** [pop-os/cosmic-epoch#852]
Is there an option to hide title bars in general? It has just "close" and "maximize" buttons which I use by shortcuts only anyways, so it is a waste of space for me.

If not, could you please add it to cosmic?
Or possibly also some some toggle bindable to shortcut for hiding/showing title bars.
Thanks!

**Comment by Department-stack** [comment]
I think that an advanced option like this should be limited to the configuration files

**Comment by rmarquis** [comment]
I believe a status bar appplet that displays the title of the currently selected window would also be a perfect complement for that feature request.

**Comment by leviport** [comment]
I think this is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/275
