### ISSUE TITLE
[BUG]  using dd or yy in neovim causes window to temporarily shrink to half size

### ISSUE THREAD

**Issue by psimovec** [pop-os/cosmic-epoch#854]
There is some weird bug with cosmic + neovim + [astronvim](https://astronvim.com/).

When I use dd or yy in command mode, window usually temporarily shrinks to half size from right side to middle and then returns bumps back. (If the window is taller than it is wide, it happens from bottom to middle).  Happens ~60% of times (1 time = 1 doubleclick of button y), not always. 

It is quite annoying as I use dd or yy quite often in nvim.

steps to reproduce (with some clean user) :
1.) install neovim
2.) install astronvim for neovim.
```bash
git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
nvim
```
(simplified from https://docs.astronvim.com/)
3.) `nvim anyfilename`, wait for astronvim to install, proceed
4.) inside new file you are writing: <ESC> and keep clicking button y -> window keeps shrinking to half size and returning back.

If I do it in pure neovim, it doesn't happen. It never happened to me in any other DE or window manager than Cosmic.

I am not sure what exactly causes it. I have tried it originally in `kitty`, but it behaves the same in `cosmic-term` too.

Behaves the same in both bash and zsh.

I have tried to reproduce it in podman fedora container, but was not able to reproduce the behavior there.

I have installed cosmic on arch from extra repo, as reccomended. (My guess is that it is not arch linux specific)

(But overall I have pretty good experience with Cosmic, good job :beers: )

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-epoch/issues/344
