### ISSUE TITLE
Icons are missing on my setup

### ISSUE THREAD

**Issue by BinaryHarbinger** [pop-os/cosmic-epoch#863]
I installed cosmic from chaotic aur and most of the icons of DE apps are missing and cosmic shot and any other similar apps are not working =D so I'm unable to drop photos of error.

**Comment by git-f0x** [comment]
You're might be missing the correct vulkan drivers (if you're on AMD graphics, `vulkan-radeon`). Also ensure that `cosmic-icons` are installed.

**Comment by BinaryHarbinger** [comment]
I'm on Nvidia mobile GPu also cosmic icons are installed.

**Comment by BinaryHarbinger** [comment]
WARN  Key-Binding 'Period' only matched case insensitive for "period"
    at /home/main-builder/.cargo/git/checkouts/cosmic-settings-daemon-8f1ce050cb107471/add1cb3/config/src/shortcuts/sym.rs:26 on main

   WARN  Key-Binding 'Comma' only matched case insensitive for "comma"
    at /home/main-builder/.cargo/git/checkouts/cosmic-settings-daemon-8f1ce050cb107471/add1cb3/config/src/shortcuts/sym.rs:26 on main

   WARN  Key-Binding 'Period' only matched case insensitive for "period"
    at /home/main-builder/.cargo/git/checkouts/cosmic-settings-daemon-8f1ce050cb107471/add1cb3/config/src/shortcuts/sym.rs:26 on main

   WARN  Key-Binding 'Comma' only matched case insensitive for "comma"
    at /home/main-builder/.cargo/git/checkouts/cosmic-settings-daemon-8f1ce050cb107471/add1cb3/config/src/shortcuts/sym.rs:26 on main

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Mode
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Panel
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Dock
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicBackground
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTk
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Dark
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Sunset subscription error: A portal frontend implementing `org.freedesktop.portal.Location` was not found
    at cosmic-settings/src/subscription/daytime.rs:16 on tokio-runtime-worker

  ERROR  Failed to create the settings proxy
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/src/theme/portal.rs:20 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Dark
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Mode
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Panel
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Dock
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicBackground
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTk
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create the settings proxy
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/src/theme/portal.rs:20 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Mode
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTk
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Dark
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicBackground
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Panel
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Dock
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create the settings proxy
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/src/theme/portal.rs:20 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Panel
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicPanel.Dock
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Mode
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTk
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicTheme.Dark
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create watcher for com.system76.CosmicBackground
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/cosmic-config/src/dbus.rs:109 on tokio-runtime-worker

  ERROR  Failed to create the settings proxy
    at /home/main-builder/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0a1922d/src/theme/portal.rs:20 on tokio-runtime-worker this is output from cosmic settings

**Comment by git-f0x** [comment]
Are all the necessary COSMIC components installed (e.g. cosmic-settings-daemon or xdg-desktop-portal-cosmic)?

**Comment by BinaryHarbinger** [comment]
Yes, on pacman (package maanger of arch) installs dependecies unlike apt. I also checked those to make sure they are downloaded.

**Comment by mmstick** [comment]
If your icons are black, then you are missing the necessary Mesa Vulkan dependencies. You must have `vulkan-radeon` and `vulkan-intel` installed. And for AMD specifically, make sure you are using RADV (`vulkan-radeon`) instead of AMDVLK.

> Yes, on pacman (package maanger of arch) installs dependecies unlike apt.

Every debian package has defined Build-Depends, Depends, and Pre-Depends. There is also a Recommends section for defining packages to install by default that can be removed.

**Comment by BinaryHarbinger** [comment]
> If your icons are black, then you are missing the necessary Mesa Vulkan dependencies. You must have `vulkan-radeon` and `vulkan-intel` installed. And for AMD specifically, make sure you are using RADV (`vulkan-radeon`) instead of AMDVLK.
> 
> If you are simply missing icons, make sure the `cosmic-icon-theme` is installed.
> 
> If you are using Arch's official packages, you may need to switch to the `-git` packages from the AUR.
> 
> > Yes, on pacman (package maanger of arch) installs dependecies unlike apt.
> 
> Every debian package has defined Build-Depends, Depends, and Pre-Depends. There is also a Recommends section for defining packages to install by default that can be removed.


oh god damn thanks.
