### ISSUE TITLE
Forceful minimisation of fullscreen apps when focusing in another workspace

### ISSUE THREAD

**Issue by GetPsyched** [pop-os/cosmic-epoch#871]
Focusing on another window in a workspace A causes fullscreen window in workspace B to minimise. I'd expect for this not to happen.

**Comment by Drakulix** [comment]
This is not something cosmic does, it is something a lot of games do, when loosing focus.

**Comment by GetPsyched** [comment]
Ah, I should've digged more into this to find out before filing an issue. Apologies!
