### ISSUE TITLE
[Feature Request] Add option to hide top bar for use with OLED monitors

### ISSUE THREAD

**Issue by NickelCoating** [pop-os/cosmic-epoch#89]
It would be an anti burn-in measure and it is an important one for OLED monitors.

Since over a year now a lot of OLED monitors came out for PC in addition to those few who used TV panels as monitors. You can expect more people needing this feature in the future. New OLED monitors are released yearly and with new features. So it is not just a single company that does that for the sheer fun of it.

At least these big companies are on the OLED train for workstations and gaming alike:
Gigabyte
ASUS
LG

**Comment by Drakulix** [comment]
Auto-hiding the panel and dock is on the radar, though I can't give you an ETA yet (remember this is pre-alpha).

**Comment by trytomakeyouprivate** [comment]
this feature is now implemented, but instead of the top bar there now is a dark grey bar instead.

Would your solution resize windows touching the top, so that they cover the whole screen?
