### ISSUE TITLE
None of the media keys (shortcuts) are working

### ISSUE THREAD

**Issue by Gr3q** [pop-os/cosmic-epoch#895]
I added a shortcut to "Mute microphone input" as `Ctrl+Backslash` because I don't have `XF86AudioMicMute` key on my laptop and I wanted to have something like a global push to talk feature, but it didn't work.

Then I tried other things that that also didn't work:
* dedicated key on the keyboard for "Mute audio output".
* dedicated increase decrease volume
* set same custom keybinding to "Mute audio output" and try to use it

Is something hijacking the media keys, and if so is it my fault?

I'm on Arch Linux.

**Comment by alex100306** [comment]
I am having a similar issue. None of the physical media keys (volume up, volume down, pause, skip, etc) on my laptop's keyboard are working. I tried to just set a different keyboard shortcut to do volume controls, but that didn't seem to work. My volume keys work just fine on other desktop environments, so it seems to be a Cosmic issue. I am also on Arch.

**Comment by desmond-git** [comment]
I have the same issue on Arch Linux but on Pop OS it doesn't happen so maybe something needs to be installed on Arch to make it work?

**Comment by Gr3q** [comment]
I'm using pipewire with wireplumber but I don't think that's the problem because I can control volume etc from the applet just fine.

`sudo libinput debug-events` also show the correct keys pressed

```
-event5   KEYBOARD_KEY            +0.000s	KEY_VOLUMEUP (115) pressed
 event5   KEYBOARD_KEY            +0.108s	KEY_VOLUMEUP (115) released
 event5   KEYBOARD_KEY            +0.645s	KEY_VOLUMEDOWN (114) pressed
 event5   KEYBOARD_KEY            +0.785s	KEY_VOLUMEDOWN (114) released
 event5   KEYBOARD_KEY            +1.085s	KEY_VOLUMEDOWN (114) pressed
 event5   KEYBOARD_KEY            +1.193s	KEY_VOLUMEDOWN (114) released
 event5   KEYBOARD_KEY            +1.594s	KEY_MUTE (113) pressed
 event5   KEYBOARD_KEY            +1.658s	KEY_MUTE (113) released
 event5   KEYBOARD_KEY            +1.782s	KEY_MUTE (113) pressed
 event5   KEYBOARD_KEY            +1.866s	KEY_MUTE (113) released
 event5   KEYBOARD_KEY            +1.994s	KEY_MUTE (113) pressed
 event5   KEYBOARD_KEY            +2.071s	KEY_MUTE (113) released
```

**Comment by yari-dog** [comment]
I have found, for me atleast, that prev song, next song, and play/pause work on my desktop with my corne, it's just volume keys that don't work on there. However, my laptop (lenovo legion 5) has no working media keys, nor the backlight keys (the airplane mode key, however, does work, for some reason XD). like @Gr3q all these keys show correctly in libinput, and I have confirmed that setting an alternate shortcut does not fix the issue.  Both my laptop and desktop are able to fully control audio, both volume & media play/pause/skip, correctly from the applet.

Both my desktop & my laptop are, now, arch based (for the most part) using pipewire. the only difference between the audio systems on these two are that my desktop has both ``kpipewire`` and ``qemu-audio-pipewire`` installed over ``-alsa, -audio, -jack, -pulse``.  

My laptop, does, however, use the colemak mod-dh layout in settings, compared to my desktop's keyboard, which uses qwerty (US) in settings (as I have defined the key layout in the keyboard's firmware). I have tested on the default US qwerty layout on my laptop but that doesn't seem to make a difference.

**Comment by Drakulix** [comment]
The system-actions are installed by cosmic-settings-daemon and by default require `amixer` and `playerctl` for these actions (see here): https://github.com/pop-os/cosmic-settings-daemon/blob/master/data/system_actions.ron#L19-L27

It seems like the AUR package `cosmic-settings-daemon` installs that file without touching it and doesn't require either `amixer` or `playerctl` in it's dependencies, so these binaries might be simply missing on some arch installs.

Try installing packages providing them and if that fixes the issue, ping the maintainer of said package. That would be a downstream packaging issue.

**Comment by yari-dog** [comment]
.....
i been dealing with this vague annoying for like 2 months at this point, and if i had put in any effort past "well it works in the applet so it's not a dependency issue" i would have had it all sorted way back then XD
ty

**Comment by Gr3q** [comment]
Thanks, I'll report it to the packager to add them as dependencies.

**Comment by Drakulix** [comment]
> .....
> 
> i been dealing with this vague annoying for like 2 months at this point, and if i had put in any effort past "well it works in the applet so it's not a dependency issue" i would have had it all sorted way back then XD
> 
> ty 

Honestly this is a fair guess, as cosmic-session-daemon really should be handling this itself, with code shared with the applet, so it works the same everywhere.

But shortcuts were originally implemented in cosmic-comp, which simply called binaries, given I didn't expect it to be the component responsible for the keybindings in the end.

It will be fixed eventually, but this works for now and we have more pressing bugs to sort out.

Catching all of that is obscure and even though the dependency is encoded in the debian packaging somewhere, it is very easy to overlook...

**Comment by desmond-git** [comment]
I installed alsa-utils which contains amixer and also installed playerctl. Volume up and down buttons on keyboard still doesn't work, haven't tried play pause button yet.

**Comment by Gr3q** [comment]
For me `playerctl` and `alsa-utils` were enough, I'll open a bug report with them when I get an account.

> It will be fixed eventually, but this works for now and we have more pressing bugs to sort out.

I don't mind as long as it works. An another open issue would be nice in case the package maintainer wants to follow it when it's closed.

**Comment by sandr01d** [comment]
Installing `pulseaudio-alsa` did the trick for me (I already had `playerctl` and `alsa-utils` installed. `pavucontrol` does not seem to be necessary @desmond-git.
