### ISSUE TITLE
Hide applications

### ISSUE THREAD

**Issue by desmond-git** [pop-os/cosmic-epoch#905]
Hello,

I am trying to hide applications by modifying desktop file but it doesn't work.

cp /usr/share/applications/avahi-discover.desktop ~/.local/share/applications/
echo NoDisplay=true >> ~/.local/share/applications/avahi-discover.desktop

Also tried to modify  /usr/share/applications/avahi-discover.desktop directly but it still shows up when I click on applications. This is how I would hide applications on other desktop environments but on COSMIC this has no effect.

Can I hide them some other way or has this not been implemented yet?

Edit: I know that I can create a new group and move them there to hide them but they will show up in search which I don't want.

**Comment by linux-universe** [comment]
Uh so this still doesn't work for me on archlinux. No matter if I cp the .desktop file manually to  ~/.local/share/applications/ and add the NoDisplay=true line manually or by using [libremenu](https://flathub.org/en/apps/page.codeberg.libre_menu_editor.LibreMenuEditor)

If there is a way to provide logs tell me though I don't know where to search for.
