### ISSUE TITLE
[Bug] Stacking a group doesnt work

### ISSUE THREAD

**Issue by Riggs9715** [pop-os/cosmic-epoch#922]
using focus out to select multiple tiled windows and then stacking them no longer works. toggle stack is still functional on a single window, and stacking using mouse is fine, but trying to stack multiple windows using only keyboard input has stopped working. unsure when this broke but it was working fine on the initial alpha launch

using arch aur package

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/b111c9ff486d37395d9fcb3702d71140627e9919
