### ISSUE TITLE
[Feature Request] Infinite tiling

### ISSUE THREAD

**Issue by xiaguangbo** [pop-os/cosmic-epoch#929]
Horizontal infinite extension

**Comment by Koranir** [comment]
They probably mean something like [niri](https://github.com/YaLTeR/niri), where windows are placed along an infinite strip that can be scrolled.

**Comment by xiaguangbo** [comment]
@leviport @Koranir 
Yes, like niri, paperwm. Allow windows beyond the screen, no horizontal limit

![image](https://github.com/user-attachments/assets/abec25a9-8cd4-4359-965a-a92497909561)
![image](https://github.com/user-attachments/assets/0126e5ac-a00c-47be-a5f5-8fc474a1022a)

**Comment by jokeyrhyme** [comment]
Possibly a duplicate of #322 ?
