### ISSUE TITLE
[Suggestions/Feature Requests] Application Theming, libunity integration, and other things

### ISSUE THREAD

**Issue by CosmicFusion** [pop-os/cosmic-epoch#93]
I have a few suggestions that I myself would really love for cosmic, and i think most of the community would appreciate them as well!

Suggestion 1:
~~A "developer settings" section in cosmic-settings that gets shown when clicking kernel version in "about" 10 times maybe (like android)~~
inside this put Custom Theming Section along side anything you wouldn't want to show to normal users
Here you can allow power users to choose themes and fonts and integrate with Dark/Light mode switching (That Would be Awesome)

I have concept art (Sorry for not being able to resemble cosmic-settings)

![Defaults... whoops forgot fonts](https://user-images.githubusercontent.com/83735213/231832543-b1e3cdb2-dc31-4eea-a6fc-493bdbad93df.png)

![Some other theme](https://user-images.githubusercontent.com/83735213/231832569-37fcc85b-4eb7-4e6a-9513-ec108433e282.png)

Suggestion 2:
Libunity integration
the original gnome based cosmic had libunity integration meaning the dock was able show nautilus/chrome/firefox/blender progress bars and discord notification counts, have that in this cosmic too would be sweet.

Suggestion 3:
For the love of god don't follow dash-to-dock stupidity and fix it's drag and drop (When some is dragged to an app menu on the dock it should be focused)

And Thank you
I hope i wasn't to bold keep up the great work
And i wish the best of luck :)

Edits:

Edit 1:
This solves https://github.com/pop-os/cosmic-epoch/issues/28 and https://github.com/pop-os/cosmic-epoch/issues/21
https://github.com/pop-os/cosmic-epoch/issues/103

At least for the UI/UX side, not the actual backend implmentation of course

**Comment by CosmicFusion** [comment]
After discovering system76 is really theme friendy

I think this instead of a dev page is more sensible ![zx6qfhzxg5i71~3.png](https://user-images.githubusercontent.com/83735213/233502620-ed12bb52-77ab-4c9d-b49c-4550ddeeb74b.png)

Like linux mint ![mint-styles~2.jpg](https://user-images.githubusercontent.com/83735213/233502647-8786918e-af8e-462c-bcba-12af4e37c25c.jpg)

**Comment by yochananmarqos** [comment]
Libunity is long dead and does not build with recent versions of Vala.

**Comment by CosmicFusion** [comment]
> Libunity is long dead

Don't think that's true

The latest version of

Geary
Nautilus
Firefox
Discord

All work with libunity


And

> does not build with recent versions of Vala.

https://aur.archlinux.org/cgit/aur.git/tree/libunity-7.1.4-vala-053.patch?h=libunity

**Comment by yochananmarqos** [comment]
Dead means the project has no active development. The latest upstream package is 7.1.4+19.04.20190319-6build1 from 2019. `libunity` was dropped from the Arch repos to the AUR in 2015 for a reason. It's dependency, `dee` is also dead and the latest upstream package is 1.2.7+17.10.20170616-7build1 from 2017. 

You're linking the AUR package, did you happen to notice my name there as a Contributor? :wink: 

I just tried to build `dee` and it fails to build. Perhaps [this patch](https://aur.archlinux.org/cgit/aur.git/tree/dee-1.2.7-deprecated-g_type_class_add_private.patch?h=dee) needs to be adapted to Glib 2.76.1.

**Comment by CosmicFusion** [comment]
> 
> 


> Dead means the project has no active development. The latest upstream package is 7.1.4+19.04.20190319-6build1 from 2019. It's dependency, `dee` is also dead and the latest upstream package is 1.2.7+17.10.20170616-7build1 from 2017. `libunity` was dropped from the Arch repos to the AUR in 2015 for a reason.
>
> I just tried to build `dee` and it fails to build. Perhaps [this patch](https://aur.archlinux.org/cgit/aur.git/tree/dee-1.2.7-deprecated-g_type_class_add_private.patch?h=dee) needs to be adapted to Glib 2.76.1.

Sadge but i think if there's any chance it works it should be in cosmic



> You're linking the AUR package, did you happen to notice my name there as a Contributor? :wink: 

Oh Awesome TY

**Comment by yochananmarqos** [comment]
I think Libunity is a little too _rusty_ for Cosmic. :wink:

**Comment by jacobgkau** [comment]
I'm not in charge of UX, but just a few thoughts from a QA perspective:

> A "developer settings" section in cosmic-settings that gets shown when clicking kernel version in "about" 10 times maybe (like android)

That would be too undiscoverable. A visible toggle would be better, if this existed at all.

> Here you can allow power users to choose themes and fonts and integrate with Dark/Light mode switching

The idea behind the light/dark mode switcher is generally that it changes all of the options for you so you don't have to go and select a dozen different drop-down boxes.

I could imagine a list of drop-downs within an expandable/collapsible section (collapsed by default) underneath the theme switcher, named "Select custom themes..." or something similar, separated by dark and light mode. This may need to have a reset button since this would undermine the current theme switcher's behavior of resetting everything to Pop light/dark defaults.

However, the UX team has had custom theming in mind when designing COSMIC, and they might have other ideas on how to handle this. Engineering might also know better what theme options can and should be combined and which ones can't be.

> This solves https://github.com/pop-os/cosmic-epoch/issues/28 and https://github.com/pop-os/cosmic-epoch/issues/21

This would not solve either of those issues. They are for tracking the actual implementation, not just coming up with design ideas.

**Comment by CosmicFusion** [comment]
> > A "developer settings" section in cosmic-settings that gets shown when clicking kernel version in "about" 10 times maybe (like android)
> 
> That would be too undiscoverable. A visible toggle would be better, if this existed at all.
> 


I edited and said scrap the idea and do it like linux mint


> > The idea behind the light/dark mode switcher is generally that it changes all of the options for you so you don't have to go and select a dozen different drop-down boxes.
> 
> I could imagine a list of drop-downs within an expandable/collapsible section (collapsed by default) underneath the theme switcher, named "Select custom themes..." or something similar, separated by dark and light mode. This may need to have a reset button since this would undermine the current theme switcher's behavior of resetting everything to Pop light/dark defaults.
>

The intention of this is for custom distros to properly integrate dark mode and light mode

i think a reset option under the advanced settings that i proposed would be perfect


>> This does not solve either of those issues. They are for tracking the actual implementation, not just coming up with design ideas.

I will edit the post to fix dat

**Comment by jacobgkau** [comment]
> The intention of this is for custom distros to properly integrate dark mode and light mode

Fair point on Pop/COSMIC not necessarily being the default theme, but distros wanting to default to a different theme would need to do this via default configuration files in their packaging, not a GUI settings app.

I understand the GUI use case of making the one-click dark/light theme switcher work with custom themes/theme sets.

**Comment by CosmicFusion** [comment]
> > The intention of this is for custom distros to properly integrate dark mode and light mode
> 
> Fair point on Pop/COSMIC not necessarily being the default theme, but distros wanting to default to a different theme would need to do this via default configuration files in their packaging, not a GUI settings app.
> 
> I understand the GUI use case of making the one-click dark/light theme switcher work with custom themes/theme sets.

yeah i think a gui is easy enough to do (i know nothing is easy, many thanks to the devs, but I imagine it's not tooo annoying to implement) solves both issues

**Comment by WatchMkr** [comment]
Theming and libadwaita integration has been completed.
