### ISSUE TITLE
[Bug] Right clicking files on COSMIC files doesn't open the context menu when the toast is being shown at the bottom

### ISSUE THREAD

**Issue by bobcat141** [pop-os/cosmic-epoch#944]
Steps to reproduce:
1. Open a folder with 2 files.
2. Delete one of the files.
3. Notice the toast at the bottom, saying "Moved 1 item from [folder] to Trash".
4. Try to right-click any other file.
5. Notice it won't work until the toast goes away.

**Comment by l-const** [comment]
I think this is being tracked here: https://github.com/pop-os/cosmic-files/issues/363 .

**Comment by iamkartiknayak** [comment]
I think this issue can be closed as this was fixed in [de08823](https://github.com/pop-os/cosmic-files/commit/de08823052fe1d04f3552c86b3ff26554a6948d8)

**Comment by bobcat141** [comment]
It's fixed after updating for me as well. I'm going to close the issue.
