### ISSUE TITLE
Cosmic files up directory button

### ISSUE THREAD

**Issue by joewood9364** [pop-os/cosmic-epoch#958]
Just need a button to go up

**Comment by leviport** [comment]
Any reason you're not using the breadcrumbs to do this?

**Comment by leviport** [comment]
These:
![screenshot-2024-09-16-19-53-31](https://github.com/user-attachments/assets/35fa893f-2735-4e1b-a976-e4597a93c1fa)

I can go up a directory by clicking `src`, or up two by clicking `cosmic-store`, etc.

**Comment by leviport** [comment]
Thanks for the suggestion, but our designs don't account for this button. It adds additional clutter without adding additional functionality.
