### ISSUE TITLE
reduced full screen

### ISSUE THREAD

**Issue by JoaoBortolace** [pop-os/cosmic-epoch#960]
When I change the screen volume or brightness while watching a video in full screen, the screen is reduced.
Before:
![screenshot-2024-09-16-22-24-10](https://github.com/user-attachments/assets/19ce43dc-c650-444a-90b6-82c43ff0f89f)
After:
![screenshot-2024-09-16-22-24-24](https://github.com/user-attachments/assets/0715615e-a0a1-40f1-8adf-15342ef3c71f)

**Comment by leviport** [comment]
Which browser is this in?

**Comment by JoaoBortolace** [comment]
Google Chrome 128.0.6613.137

Em seg., 16 de set. de 2024, 19:31, Levi Portenier ***@***.***>
escreveu:

**Comment by git-f0x** [comment]
This might be the same issue as pop-os/cosmic-comp#487.

**Comment by JoaoBortolace** [comment]
That's right

Em seg., 16 de set. de 2024, 19:47, Vukašin Vojinović <
***@***.***> escreveu:

**Comment by leviport** [comment]
Thanks for the report. Closing in favor of https://github.com/pop-os/cosmic-comp/issues/487
