### ISSUE TITLE
[BUG] Onboard Speakers not working on Thinkpad Lenovo P1 Gen 7

### ISSUE THREAD

**Issue by johnnyq** [pop-os/cosmic-epoch#970]
Have newer Thinkpad P1 Gen 7 Intel Laptop but im not getting any sound output from the onboard speakers. Works with PopOS 22.04 just not the new cosmic 24.04

Ive tried all the Output options in the sound settings with see below

Profiles
![image](https://github.com/user-attachments/assets/f243927d-4f2e-4016-9c81-99639c14c183)

With the Play HighFi Quality Music Profile

![image](https://github.com/user-attachments/assets/c321b5c9-a2cf-4c14-8364-43dc48ec8eb3)

If I switch the Profile to Pro Audio I get these option however none of them work either

![image](https://github.com/user-attachments/assets/6d6c8ad2-5e95-45dc-ba7b-c14849a9682c)

Audio Out seems to work with Bluetooth Headphone and when I dock it to my monitor

**Comment by hatemjaber** [comment]
Just curious since I'm receiving my today. Does sleep work on 22.04? Any issues at all? I was considering staying on Windows and using WSL2 to avoid headaches. Seeing your post encourages me to go with pop. Have you resolved the audio issues with the latest version of pop? Thank you for sharing!

**Comment by johnnyq** [comment]
Hey @hatemjaber
PopOS 22.04 Stable works just find it just the Cosmic Epoch Alpha 24.04 does not

**Comment by johnnyq** [comment]
Looks like this issue has been resolved after updates from the last 2 weeks
