### ISSUE TITLE
Wifi settings of any SSID isn't opening

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#976]
In "Network & Wireless" settings of the Cosmic settings app, list of wifi networks is displayed.
It is possible to connect or disconnect but it isn't possible to enter any wifi SSID setting.

**Comment by mmstick** [comment]
If you are not on Pop!_OS, make sure network-manager-gnome, nm-connection-editor, and network-manager-openvpn are installed.

**Comment by Thatoo** [comment]
It does work. However, it doesn't look integrated then.

**Comment by Thatoo** [comment]
![image](https://github.com/user-attachments/assets/02df5c3f-0123-4740-91da-2f977872d93e)

It is the first window not displaying with dark mode.

**Comment by mmstick** [comment]
You have to enable GTK theme support

**Comment by mmstick** [comment]
Make sure cosmic-settings-daemon is running

![screenshot-2024-09-20-12-27-44](https://github.com/user-attachments/assets/5685bfed-ab9d-472c-b3b9-c952befabdb3)

**Comment by Thatoo** [comment]
Apparently, it's not and I don't know how to start and enable it

```
:~$ sudo systemctl | grep daemon
  accounts-daemon.service                                                                                               loaded active running   Accounts Service
  cosmic-greeter-daemon.service                                                                                         loaded active running   cosmic-greeter-daemon.service
  power-profiles-daemon.service                                                                                         loaded active running   Power Profiles daemon
  rtkit-daemon.service                                                                                                  loaded active running   RealtimeKit Scheduling Policy Service
  libvirtd-admin.socket                                                                                                 loaded active listening libvirt legacy monolithic daemon admin socket
  libvirtd-ro.socket                                                                                                    loaded active listening libvirt legacy monolithic daemon read-only socket
  libvirtd.socket                                                                                                       loaded active listening libvirt legacy monolithic daemon socket
  nix-daemon.socket                                                                                                     loaded active listening Nix Daemon Socket
:~$ sudo systemctl enable cosmic-settings-daemon
Failed to enable unit: Unit file cosmic-settings-daemon.service does not exist.
:~$ sudo systemctl start cosmic-settings-daemon
Failed to start cosmic-settings-daemon.service: Unit cosmic-settings-daemon.service not found.
:~$ cosmic-settings-daemon --help
Error: NameTaken
```

**Comment by Thatoo** [comment]
Well, I have been said : 

> cosmic-settings-daemon is not a system service and runs as your own user. But it also has no systemd user unit either because cosmic-session starts and manages its lifetime itself
> 
> Given that it says "NameTaken" it almost certainly is already running

so it would be already running.

**Comment by mmstick** [comment]
Make sure you have adw-gtk3 installed.

**Comment by Thatoo** [comment]
I added it but it didn't solve the issue. For some reason (after this install, but I tried also to uninstall it and it didn't change, after update...), I can't open `Comsic Settings > Desktop > Appearance > Experimental settings` anymore...
