### ISSUE TITLE
no lock screen after waking up from sleep

### ISSUE THREAD

**Issue by Thatoo** [pop-os/cosmic-epoch#984]
Hello,

When I wake up my computer from sleep, it displays directly the work I was doing without asking me to enter my password on the lock screen.
Is it a setting i could change somewhere or is it a bug?

**Comment by jokeyrhyme** [comment]
Maybe related to #172

**Comment by Thatoo** [comment]
A solution is to lock the screen first and to make it sleep after.

**Comment by Thatoo** [comment]
It looks like it has been solved. When I ask my computer to go to sleep, when waking up the screen is locked now. Thanks.
