### ISSUE TITLE
[Feature Request]: Resize with right-click when holding Super

### ISSUE THREAD

**Issue by green7ea** [pop-os/cosmic-epoch#992]
I would like to be able to resize windows without having to hit its small border with my mouse. I'm usually able to accomplish this by holding the super modifier and using the right mouse button to resize the window. The left mouse button moves it around.

I have limited Rust knowledge and would be willing to try to implement this feature with a hint as to where I could start looking at the code.

**Comment by Drakulix** [comment]
This is already implemented.

**Comment by green7ea** [comment]
I can confirm that it's working, it seems that the app's context menu still opens, so I didn't think it did.

Should I change the issue into a bug where the right click is still passed to the application or close it?

**Comment by git-f0x** [comment]
The right click being passed to the application is also supposed to be fixed. What version of `cosmic-comp` do you have?

**Comment by green7ea** [comment]
I have `local/cosmic-comp 1.0.0.alpha.1-1 (cosmic)` installed from arch extra. I'm glad to hear it's fixed in a future version  :-), it confused me a bit.

**Comment by git-f0x** [comment]
Yeah, Arch hasn't updated COSMIC packages since the release of Alpha 1. They will likely update them after Alpha 2 releases (26th September).

**Comment by green7ea** [comment]
Sounds great, closing the ticket, thank you for the excellent work :-)
